apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nfsprovisioner
  namespace: mgd-default
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: k8-sigs-charts
        namespace: mgd-default
  interval: 10m
  values:
    nfs:
      server: 172.16.0.108
      path: /mnt/2tbhdd
    storageClass:
      name: milano-v3
      reclaimPolicy: Retain