apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nfsprovisioner-metrics
  namespace: mgd-default
  labels:
    release: prometheus
    prometheus: prometheus_servicemonitor
spec:
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
  namespaceSelector:
    matchNames:
      - mgd-default
  endpoints:
    - port: http # The default metrics port name is usually 'http' or 'metrics'
      path: /metrics
      interval: 30s
