apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_middlewares
  - _repositories
  - namespace.yaml
  - pvc.yaml
  - jackett
  - plex
  - radarr
  - sonarr
  - transmission
  - jellyfin
  - pterodactyl
  
namespace: mgd-entertain