apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany  
  storageClassName: milano-v2
  resources:
    requests:
      storage: 100Gi