apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sonarqube
  namespace: mgd-devbench
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 2025.4.3
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    community:
      enabled: true
    persistence:
      enabled: true
      storageClass: milano-v2
    jdbcOverwrite:
      enabled: true
      jdbcUrl: "jdbc:postgresql://172.16.0.106:5432/sonarqube"
      jdbcUsername: "sonarqube_rw"
      jdbcSecretName: "sonarqube-credentials"
      jdbcSecretPasswordKey: "DB_PASSWORD"
    postgresql:
      enabled: false
    elasticsearch:
      bootstrapChecks: false
    prometheusExporter:
      enabled: true
    monitoringPasscodeSecretName: sonarqube-credentials
    monitoringPasscodeSecretKey: MONITORING_PASSCODE