apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: mgd-devbench
spec:
  interval: 10m
  releaseName: sonarqube
  chart:
    spec:
      chart: sonarqube
      version: 2025.2.0
      sourceRef:
        kind: HelmRepository
        name: sonarqube
  values:
    community:
      enabled: true
    persistence:
      enabled: true
      storageClass: milano-v2
    jdbcOverwrite:
      enabled: true
      jdbcUrl: "jdbc:postgresql://myPostgress/myDatabase"
      jdbcSecretName: "sonarqube-jdbc"
      jdbcSecretPasswordKey: "jdbc-password"
    postgresql:
      enabled: false
    elasticsearch:
      bootstrapChecks: false
    monitoringPasscode: "define_it"
