---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-credentials
  namespace: mgd-devbench
spec:
  encryptedData:
    DB_PASSWORD: AgAL7mM0hECPNlf6jrorsI+rTF+EjSum7qMr2LDBanD2jSD0Ay4YjleFvferSwRr8FKcK7Wu8kA7tR5TLpr9kSEgmjz5bqoqgDzfs8nFK3lpxrL8LyFe3qBKCZ63eZHlSVvV8zjU95xpNsz2iiAusW0+bZnCX0b6ZL/3hVIn9uZqv796w/5xVk0UudVXuyiOvayks98xLWPrh+yRa+dOGtboOxsFlSo2K0Rw4PACxAuDHWIOye9KJvzbzG4dV/CKYeVLu/LoJzMh7Axv0o429UOXUje7pKmmmwn3iWXJFufiSWTozW9AqidSqyV/wEKYxO5D3FAhVq7NLlRacJTd7pAAoTRtUyvCE4/iGdnwqNlC2uZMP3yXnHyikZxX/6elYZ0eziBEsIW6q7TMHjtVgJqzv6HEMyusrB4ZoxFPhE171ECgwymnkpH2qHUHEu2KMowVPEpJ/LM6eVJoutkqIibFSnSjaT9CU1KLq1Q9G3ckTWlPojZ09fpLxQaRkhorikDCLnsHgICGL8pu7p75Qq4kKG/utFWfIrNJh7H8JgHO7qfaoOVUt0KvL5yZ5Y9NcsndSvODYbAayYmnR63HOuxYpEDtKv7uHS5zrrEEHQy0xJtD4wSAzN750EkaZhDvbd6vqT6pQBiZYyKT5ExWQW+O4TA17W8eWGhuSkeT4IfMg8Ivw92ksNBREc2DKnNakPSG4VA1oDfGshb5PxnM
    MONITORING_PASSCODE: AgBhXKPzxexyZ1k0m+Dzj7+zh5pFhKMuPXJ2IkP24AK4QWXTEWCCWf77BUUnk0Wg+H+YA8TD4kDxwY+XraBk+dprYRTa/gTlCQuwzeh3dJAjmTAUxJiS8BxQL5VSHgKJ79CtqYz5iSQduqu7wJZqZCS3U+H4VUAznTXOpit5LTFU6OWYp5CKhMUVQzhaLfZXgUvztJ2/H2etlG4nkbJmeeCywwE/N3nuqxORTa6uSYJoPf4WXe0fOZq9W2psboclM5+SjGGu+1fp4ajjnBUunC4dW7gE8PLZ9AdovjNVbiPW4Vx/zbkelRATw7hQDXvoX5KVBd0FDsuC9y0JN9O1nHfqQf5jOVXLm70RGZNsl1oHFRdpHSSzKFfyon+hRMV1Wu0FXQe3y4XoxejZSKKttqo6McVA+/GOBrAETk5cobxV3NgMZEjYPuJOg03rjPA9QjuqUAlqaErCV3qqMj86BS88bHJNy8p1ZZNILtv7VXzHCK0KB1UV3dKO8LVWvunPS21B5r4HrCF6ZWjDxwMVIBxzhY/i3QqJQQJiX42AZVi15c0K6GhGJpBoKWON3Ln8DPS8VlUsK3qjSlqkk/fPljkCerfWEuCc2xaflRqGPYdqseJJaN3kSn9K8XV7zW33qKwOAPnK307A6s9DjOSEtOUbZUmnV2YIfcmfH+i57vIDj9eDEqrMiMqxAYg+bdlhEMHWJCXTJ9MB9bMLWK+IbjKNRmXz/zXga3Crb17MWVpSDIBmxLhJxn9y1+hMoQKO7m0RY4Qo+w==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-credentials
      namespace: mgd-devbench
    type: Opaque
