---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-secret
  namespace: kube-system
spec:
  encryptedData:
    MONITORING_PASSCODE: AgDN9Uww5YX/h6UwSJLzfR0avPFx9Pk9AROoQ1jVHdab3w1s4hxJq9fyZXBzKKP9NNZaGuRNXEQoHAg90mRu1iErpHt2br/M7KvfZdoe+dpT6qO45IoICphjKMKL9vD+ghvOaueOMVMxc/g02QAOLCX0sRCkTrIce93+EuE/9b5fk0WJXhwx/M5pQ0oJ04iHVH5dNJBTlHJGi8qI52MXQl9gHWQFIuDQ4BcA6B+FEmeapuGL3BNgIAK8HUdmCc3wbCUnE4/1FqBjZ+d8ZhdtANrUydnSNtJpwcKeNmQPA5VFmc2qcAolkF+r2f4BA3tSuzoRzDzI75qYgBBJTL5dRxFh6ADs2DLegz258xmBeXuFZRGQy3+S3UTUOsgy6n43zTN8xNBCrOdEeSHXgIauCY0ofhepRQCAam0IvHOMNkdWNY8JP7Z7hvt5pkzflrqbjT/H4f9nvEwi4itrR9aO9lde89MeTL/cCd11jitn4R6RfXEl4a2WgPn/nAFC/lGUkd0hIVDjFKYmxe3x2fR35MFTqjEsjUCmxgEpG0AZvcHL1yQk6j+mSnqNIowC8jAS+uQqclUFGjqB5Y6KBUA9J0JkEzQhAOOs9dhLsoYTHfBta+xOEbjajqIIm0sanFnxvMpr1UCzZfVZkAW1vHhVQvI136/yk8J4fT+rtB2ZHDXHbiSZL4MLu15GtXfMiJwwIp5zU2Vh4QtL72zyAyZ93hoU/WomIVzG6ecuVsxYRWxBfx8aJdINCNeE0DH7pR/T+pwpiZoe1A==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-secret
      namespace: kube-system
    type: Opaque
