---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube-credentials
  namespace: mgd-devbench
spec:
  encryptedData:
    DB_PASSWORD: AgCB/liFzGCy0y1JWpcsgGUhBYPxeWk2+wVfxZlP+5AFaEDSkSnOjnKFUDYfhfU6VkfXXj7it6bXVk8Wi8FaXBrquEu4neCrU1Mk4gWfd9lvZTYiL6Xoagf9vVTbbflZCWi1GGlSpKrYUs+tD214D/A3KagCJFNomB2bh7HTnDpdUJZW/vr0Zd34bQ7dxaWUbDR4EfxKrAktwmyGOfHNCr7k87CtCAfS2rxm+cHxE35nj9NTWe0YKIDkdQxxtUycluX+fWQfcrlZnZhS0Du9wdPIHEI4HFCMRXmvSBFlQxkXdbxUY6Q0hEL+Qa5NV6NsUcZOYUyj7FC+qfc87QA30BGMqqPx71f/wcVlM519PRG5yLUrKXcupPXwMQ1yZZi5QKftZNG3v70Q7wc5vbA0kYEsadVdHyUSHP3ibw6U47r8gDksw66oghgcx/m47NsN7RxBuhox+/fHIaz09lfEzSmyL9Qmq5dezNhY6VtbcPysR+XDa8PaPqaI0z+sCIGnvftGBJw22SXACm4NNbTqto90Z9AR4VR09VFebLfuh5C66G13J66BSCXjCG0kGBTIzGhdtUsw/PkCmaeQqSwiBPl0EvoFzX6cG8/vjAy1DKYb5z2D0GQ3mGMcl14bzyo6rZAW+iHbDicxBYJEasHGnrVVOIb2/PAku/xaphcuGPMf9ZVmajtqftO5cS4sB3/CAK3tAY1+SmKpUuBDVfnbn912Sg==
    MONITORING_PASSCODE: AgC4+R9PoVxT3qxSZT/XP/U9W/ONAdzWiE1kAqRc+C4wfsHhVtmhby2a8SdoiXrHIVGjIFQy8I1qh+QfGVZ2PZdJc5M/8Qr9GkrnZlHUu/o+Xw+QAWssRKBPFSUuR+XDuRbNh917Xtt+148uKQWJkVfNMJNY4qzf6agcSnVQAAvj0zMVeaAFeopD9jDwDN8MVu+Wy1GFCFp87t56wl8iaqq71OKK6mDxj5KxUOTtONne3UrH9jCxBIyiqlSyn98OP0UirjabADXKciMI5uZDRwx9AARa5ZzSuOZWdU/epOn2yoY/f2PYZJmQkaEjEFhDvcWr+nspf2V1zBzuAp6n8I4OWPjJVcWTNAcxEwnyXOyg8l8ShEZpbji4o2VZwvZKa/AZIygMoYzL5ndQ04v7HrH29Dmdn1vQzT3r2dBvA5LEhSSIGTM1ndbK7lfhn0sJeAFRNVWhsXEPmgF+7ipkSfP9XCAfrdGp2eXM0WOyfgvY5PfPsXbXov2qKp7YrJqPxsUikaEtggLfH0HxPv/rSrHe31iCC26C+0IxwhoZddT95rMn6qz5SoKQ6sHnx+tnms7Mjgia0GBSjD8Rsdw0WsSSxkgb/f7S1CPqcXrmpHVtoC7U2vSCp3bk6qvoOR22z/FMyp//cWbFl8R51bnWIp3pyvSz+MZGNJ3i0vrLQjZ9X0FerOHXnom98KqxfYS3n8bzuO6iWGvUN7WpFzGFK8TIQmdNURBX+k2KzxwWTgrL5hMc8H2Zg9R0/qNiNNkPZqkhysKQ7A==
  template:
    metadata:
      name: sonarqube-credentials
      namespace: mgd-devbench
    type: Opaque
