apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"