apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-certs

resources:
  - clusterissuer-prod.yaml
  - clusterissuer-staging.yaml
  - secret.yaml
  - helmchart.yaml

labels:
  - pairs:
      milano.app: certmanager
      milano.level: managed