apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-ks.yaml
  - ../_middlewares
  - _repositories
  - namespace.yaml
  - bugsink
  - gitea
  - locust
  - sonarqube
  - tools
  - touca

namespace: mgd-devbench