
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-cert
spec:
  secretName: homepage-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "home.trusted.nirmalhk7.com"
  dnsNames:
    - "home.trusted.nirmalhk7.com"