apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-default

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - ingressroute.yaml
  - service.yaml
  - serviceaccount.yaml
  - certificate.yaml

labels:
  - pairs:
      milano.app: homepage
      milano.level: managed