apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: touca-cert
spec:
  secretName: touca-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "touca.trusted.nirmalhk7.com"
  dnsNames:
    - "touca.trusted.nirmalhk7.com"