---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: touca-credentials
  namespace: mgd-devbench
spec:
  encryptedData:
    MONGO_PASS: AgBZlYIwZDb3BV0xc8ajqRgrv+b8I2bd6LyKeVVEf6KE8bIhUqEWdaN6EcrXb/PvZwI24a4NniVBcYBRyQZSj8NBw1twngKgwXacBn0sRR0l8AWTqD6c6wbBkdBm8oit3J8bSa0Walm1TC4n5LCF//hGt7lQy0iA9MyCRlrZnh3wrA50SmZfeTh8+aLwd7xkPenO3pLrtVqQUmcpZ/x7gnAgAyU7EBZSb9sAa4o2oUcpafDvIFcMqTdpTLmQyCOND73rLv0GJKBpEWrFAzxj/z0rKk16UEa+eETmknsI0S1lK82GI//pY6q8/zndGjUlVbQWJ/k9oIDrUbuc+PmZwSWyEhTJhe2wlvGGVyWzfKcb51uXN6qeEa0zvv/2GBq8EKGtkOeDhld6hdfT+FXyPV7w+3244IhwiZW7mAuSs6wMbV6//r6AcOales6O5cnSTJ+I82VurNd2d5Qy3Jq9RmgAttKABXtk3Zmo4aA5QWhmy7mV/mJ7L1U1baBoWGUO016geX6Gdwfwh1Y6oGZj9gLH4QQ34Tn8fjvhXelOIb6O+FCcg4G0E+U4/4msoSYDVTI+dUFohoqhDNt5bqTr+qJcB1rZ2wQy3L1UZVGCgaLLEiK0A5IgYm5Fnl4AkaG/rv4uh8z8lTFnaolB1u2UGv0m2R7YCS9Qokp8tSQ3iZfQfz4i1VZrwuv5RMn/grKkbLCL1L/bN487Mrue5BNl
    MONGO_USER: AgA3d/JL23lWV8AT8LSJWwJorodzGkGXCLjcYfhX1Es9RUfliNZMsMkgb5bwf/W1QD2lhuxFiP+KLlKx2+21CWYHu00XIUsqwsTzqalTd7dUgLpwuFIM4UapXU8hnOscyuf3BIPaB+QhzsxdNFqoQXz6wR0cdFJE5NtnNErkqGZz1ZLjMMZa9vcFtPkSi6mPkBomw5G46CDFIymSXnwBt9byBmyK8DTV6EgRFNSaCUsoKocooKKFa0+1kqefcZh2M88Ha+hLxHjitZVsala7ncjzBgCyIORIIeRBGrJGj0uX0wkSjrieWZ2TSBUSWB7eeqwpgqbmPQLq0Tmt4UVX7qyM5DaqlroSjJC3zXu19Ai6ZL0CK8pT1+GAJpwi3EboKTHXmwALMRt3POQ5eDcyQ6PXzl3NqdO6bA3TaiLuPuOotgpMbbYOnmkDoVCiWdARrI/4ZSO1HLiycy8pj2TRfKWCn9fUYdgVDzF+S7JCQ24L/NHbnYUzeEJobd03gxIHKtt/CxvOYq+YdNqc7aR3TjYsNUeVHe/ZBbfjFG8Qv/1SgRt1Ib2ipj3kWUCP9I6735wqOetfp2flnr8JmDmV8ghrCykU4DBVDpOrNumStIA+ftTkG196uyZjf15HPbNZ2/dU3B+zmRGHqnKE6t0iPMI1Mi3gZQLT10pkx0CIJZvGc9TbfX3o6+f07D5jHAN8LpU636hJ8IxYTg==
  template:
    metadata:
      name: touca-credentials
      namespace: mgd-devbench
    type: Opaque
