apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: &app immich-helm-charts
  namespace: mgd-multimedia
spec:
  url: https://immich-app.github.io/immich-charts
  interval: 1h