apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: cn-mariadb
spec:
  storage:
    size: 2Gi
    storageClassName: milano-v2

  username: root
  rootPasswordSecretKeyRef:
    name: abc_secretname
    key: abc_secretkey