apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - mariadb-operator.yaml
  - mariadb-operator-crds.yaml
  - dbcluster.yaml

labels:
  - pairs:
      milano.app: cloudnative-maria