apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mgd-db
spec:
  chart:
    spec:
      chart: mariadb-operator-crds
      sourceRef:
        kind: HelmRepository
        name: cnmd
      version: "*"
  interval: 10m