apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-initdb-scripts
data:
  create-database-and-user.sql: |
    CREATE USER 'svc_nextcloud'@'%' IDENTIFIED BY 'K5fL*s9Cok!cqTsW^o6m';
    CREATE DATABASE IF NOT EXISTS nextcloud;
    GRANT ALL PRIVILEGES ON nextcloud.* TO 'svc_nextcloud'@'%';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON nextcloud.* TO 'nirmalhk7'@'%';
    FLUSH PRIVILEGES;

    CREATE USER 'svc_bugsink'@'%' IDENTIFIED BY 'K5fL*s9Cok!cqTsW^o6m';
    CREATE DATABASE IF NOT EXISTS bugsink;
    GRANT ALL PRIVILEGES ON bugsink.* TO 'svc_bugsink'@'%';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON bugsink.* TO 'nirmalhk7'@'%';
    FLUSH PRIVILEGES;

    CREATE USER 'svc_vikunja'@'%' IDENTIFIED BY 'K5fL*s9Cok!cqTsW^o6m';
    CREATE DATABASE IF NOT EXISTS vikunja;
    GRANT ALL PRIVILEGES ON vikunja.* TO 'svc_vikunja'@'%';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON vikunja.* TO 'nirmalhk7'@'%';
    FLUSH PRIVILEGES;

    CREATE USER 'svc_pterodactyl'@'%' IDENTIFIED BY 'K5fL*s9Cok!cqTsW^o6m';
    CREATE DATABASE IF NOT EXISTS pterodactyl;
    GRANT ALL PRIVILEGES ON pterodactyl.* TO 'svc_pterodactyl'@'%';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON pterodactyl.* TO 'nirmalhk7'@'%';
    FLUSH PRIVILEGES;