
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maria
spec:
  releaseName: maria
  chart:
    spec:
      chart: mariadb
      version: 20.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  values:
    global:
      storageClass: "milano-v2"

    architecture: "replication"
    auth:
      rootPassword: "xey!rB3rN&Gy&LCLBs%i"
      database: "default"
      username: "nirmalhk7"
      password: "$CivwzbNdt%GTBBs27VH"
      replicationPassword: "JMCQpvHK6i"

    primary:
      persistence:
        enabled: true
        size: 5Gi
        storageClass: milano-v2

      service:
        type: NodePort
        nodePort: 32000  # Choose a port in the range 30000-32767

    secondary:
      replicaCount: 2
      persistence:
        enabled: true
        size: 5Gi
        storageClass: milano-v2

    initdbScriptsConfigMap: maria-initdb-scripts