---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: maria-secret
  namespace: mgd-db
spec:
  encryptedData:
    mariadb-password: AgBb0ETCl93hmzjPijFAAkva4qHrhzPMsaXgiG8i+n1sm4BD0V1c/K+gfz/AG+csSHo6UBvfKMIU0IvIIwFwUH/95crgxYaE78aHk1AVkbTKckhgsHiT2uNLBitDUR7SbzzcQpW/90EIOSWf3O9BcVMdyEzHWGl1Z1SfaodXWi45sE7pwC67hkq8MrR6jskgexI5WsFhlgRGXue41iJG1k9e4CFCFvs5agyCHkjIoiIsxYzrN2SF2YEH8zDtZn4m99sw8+oaVkiTJGCyTgliVacpzsnXNGKeuzqtF4+bdERxn3BuUs7IIGLga2AIqn8jDw6FrSXTP+pI03hmiH9ZOhbobgPD6dYXP9WpP17VddDi6VdvWs7UWGp2w3I5YFDMumEGhThjoHdZNZJ6b7ZmGuszqBAjf2xUjzbaMbhIdetmjkMfvoUWDS+2IlGNWA1dbUsMBlwkMz72UMMzrx2cwkoq8AA1RoXbFsOpOPRpcZ/y/D3EBsmv2n0WUTSfYcfOF0Iq0V1TCaNU6b6lk7TYwWmgj4PX9GCxHwB7lUGTM9oSqQwJIltUZPl66DEvrC22TyyJbew5EyCWRxxIZ/bXkh4IuJX3yPP0UfWTxfpTz3m96EPEyH3zwZzbaG44fHNX7BI3xNTipncvPu5JZMq5fy/3sEkhwVm6JZRnUeEBEJDMQ2Bqyd3EGmeKcSAdGrboqWw=
    mariadb-replication-password: AgALfCOip58h84Phx6PEEQW35MSl6y5DcFEwXzBqXAAfAtXADaUyEOhyxLomn/HmAq/GlaKjQkH7OmfYRtybeSaMGe4XL9wOgBX8UvQVg4bcOuIedRDHRCQG1wJEL3CFIdLgUOW03SSPubIVZ6ebIsKbeD67WB9fRdYjz9jV7d4wRKUGQoC5Lr7vkhq1IHeNeV+zNa74MUDujd4N0zVNNbdRUogxIbNJdhLQIxrU5s3Ov25rWQJFurGIJZ1vNe0IHEku3DI9u8CD3X87y+qag03oOAC4rSVEJR9U7rXX6nU/oQSkI4jNOqt9Zpqe1DXr5G1yQELDe3OyfkWx3YLuC2wCjIJtcMZf/GUsSBFRJ5IH9/HB/l2U/7ztGtIvYFAUVHJTp3G+v+e6oMePXtJx1TKFk+dNAl1Nl/ple2ID79Af62++ebM2/FBhINEDYUEpuxENHZ7NVGl1E8oagEgaPWduvvGjMN1f2czcjcQJm1lyIzcFkpPePWpuGjUWYlSMbsgI5bw1kb1OohHqKw3hMxaAAKuqmUdLI3WEJeDkIbZXLDwSeX7MRVSbUmf63Eq6jQiRJiCTHLo/obt8jM93deqOGNN28nTCO8mdJO1vs/8fQt/Bu1FsDxkIi1liJ08UbqNf/GMkZEckO69wVroP+2G+L9OXC/OmG9qSE0JbCkiY9/Wshs/rAojix4A4iaUvjqa8Gbxbt6qArQuagkZltylxQDiKLw==
    mariadb-root-password: AgA4Wi2SdrrSgE5SALYMS6F5bcUvMYIeUctqp0ZPmMgm/22UtxfzkZxUHsizle7+weFlw7v1lfkpZXi1CComH7QoSqRNRCNU2VDsZXX40kjtau5GYB13QcPkvsESAKPX3A9cXzOknBWU5VHdCtbERSBDXmGoXfKb9c+dndcYfgfAgTnCFC0KsewTFMapSBFmR4mAew3BGavlNkQHVmP21eBGDyFtYp1ieOltA4njNgrVD/oOY6B46/q0xa8+u/ICcU3WrcFKNb6/h/IaaXLPnQs7T+zHkfObU2DLBu+uUmoUzvi1OQBj079xLYAEDc8Ok5Hle1TwFvIqS8g1TTWiWeOuf8VXOR3gk57SfcM5TTOm73PWgiQGUGnyZqgcqjVL6x9Jo70QZxvzqW8ojDRXLEH/FJ4dFm7xIjAjMGDl323DqBVKc6SUDPpnPQTi10ecaP/YdQrFMpdv2TRJ5Djzq9Vg5DAW6lvxJOzQdrMJ4ecjuQ6qHtkQytMCZmoM1JNOZ1e2jroPAlH/6Awq1SkIGGV2sIWdy7JUbtwnDNZL6DAP1eEjLPMeJT+26HqlNiawytJS+NwhP5lp2u2ZQrh0fKl5Gs2XRqn4Am1/0Uw31i1F7odlPJ74tjZeEg18Lh2rnBJbLdEHM5JFinbFsqOq0H7h1TMkxjkiuOjJA9uUsdUNx65+HiVBImZoTwI047zmsiRMVuw1WVU0/ZdOPHOSh4DVUcZ00w==
  template:
    metadata:
      creationTimestamp: null
      labels:
        milano.app: mariadb
        milano.level: managed
      name: maria-secret
      namespace: mgd-db
    type: Opaque
