apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-devbench

resources:
  - certificate.yaml
  - deployment.yaml
  - ingressroute.yaml
  - service.yaml
  - secret.yaml

labels:
  - pairs:
      milano.app: bugsink
      milano.level: managed