apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml # deployment definition
  - service.yaml # service connecting pods to cluster network
  - pvc.yaml # pvc used to store cache and attachment
  - ingressroute.yaml # ingress definition
  - secret.yaml

configMapGenerator: # will parse config from raw config to configmap,it allows for dynamic reload of application if additional app is deployed ie https://github.com/stakater/Reloader
    - name: server-config
      files: 
        - server.yml

namespace: mgd-monitoring # select namespace for whole application 