---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ntfy-secret
  namespace: mgd-monitoring
spec:
  encryptedData:
    AUTH_USERS: AgBzVUM+oIr0viDJ9bltAeVMlC5bFGBIQzdnxz3z+Uir0qigdRsiUSiXwghnRwLO9gfnX0RBIadIV+6KLHrHk5QTp5ECpHVCXdyrKRxSjH5/vJo+d9AN6Gwx4oLw5wngwRagCWPABSNv+ajmCd6SWYo8k/OhRmdw/fcrtAyfoKRrxF1S1lkK+nx3/2eDXDj2Z/b+Eox/dA56CFVLhKkXDcnKQbUwS9EoYnz3m27D5VWM5EAp6ODWEP/DfxMoswfITpuS7mRivomV2c7wAnvGAWKulrbUQhRyofx04OS00GtQob66jeChv/FyujDqaQXHtHxPTWAvrt7BdX/JXQETzdggo/t+kcfS1Nu6rPkOZe7mEBtVZ2Xybow6qjnMGicCgnTw+hzgTXzMv8qdJDpTdaYS9CxPftl6l2q+Y05FzADmKE0soQyLLzKDnrzrJq8wKaEPRv+uIrVhXA3fFSyZ2FUYfI+LYqWcqpeKJeoulDZTIsXcbIzOKwSlNbgmbXp0lfF5nt7KkE+WxTYYHmikdrtVljPdh5wNF9o3nrFJmQKqWBLYUXQtk7bePCN0FHmE4A4BtazLfKWrgBNRHhfeJUWrY9TKl3uCtcGwxWqE7zNvmN95y5FaGSJnfcWtm3xanW6ZmQ7WXid8/dRbpxkbUHEYDM8VD9WtFkjZRda2DTXL2lt9/SxhZBPoo/uxo84lWisuCOmIGQkcpc250SAgZ3UCQfwG0Tb+DOZaPlFqu3yUzLPc9C/pFgA6y4f7HDyJxn2mBvLrpb76W61cBRIIFxAnNrJDhlcwuvgH
  template:
    metadata:
      name: ntfy-secret
      namespace: mgd-monitoring
    type: Opaque
