---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ntfy-secret
  namespace: mgd-monitoring
spec:
  encryptedData:
    AUTH_USERS: AgAhZEpqI6JLKCGD5UnQTU1gmWoY+SRHghkh+j/tBiFkkVpoZM1lNkaitqVAi2h7y4fOuA8HWQYiFH3eD6lf2DaiUuH6eXSAaCvtg3raXiU41WSU6HEK77lbzi/HdT6gnj2vwZ5dLsfdS6UnLF13AswTJz8lAuu3dnsIjBxxswN8og59NJYKb62QPGQoQncJr2N/Lh+9j1beFBZUnvf7kbzCNU0BHtkHVOEch3iYQwsed25aXV6aVuaHdffHS6S3rcZhn5GkN6qXytmu8h6qkqO+VQ0u6TfCXHB7puD+pRWLCZlNttFf4Fd8lrs2O5O8VMcxA9ygcQovRZZgQ2HE+Eu6p/9w470Q4N7aUCb504o+UbfrbNlKEL0dEIrt3iZGaRTvmr6w5kO2IAyUAM4xKHhxFiBO7ENmzGMPOc1/QL2Z1Eo22LRJjPlx43siX7Ch6ujgzOekvNkQT2ewaD4sq1yg7NrJbbrMZELKfZSjkE49OHSnq0zKyWI9uJCx5mqzVSboFKWobY5e8l+hJsHyxcjfqMN5U/uwflSUCNjQ9b932NFO+M8CI1odc30Mwqx6l5X5PfdV7cDVI361KUBAT4TCVg3kamD31bJ4Bzcr5DCNEl08gIN6+w3vCfLfesCGilLNvCH5g6bL0j2l6X4yYc5Fbp65l8DWLDjtVPalL4yXf9dKoyYqelHrRmYWZ1RXK5NnnuiT+JruB3ZsVs1LbVxHHiqaYnggMiyl9YLAtrNma0t914LL7c5r4Av6a8YRPGdyTmgq6lUItWxX73mKjBOVdfLecnDs6VpX
  template:
    metadata:
      creationTimestamp: null
      name: ntfy-secret
      namespace: mgd-monitoring
    type: Opaque
