apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "vault.trusted.nirmalhk7.com"
  dnsNames:
    - "vault.trusted.nirmalhk7.com"