apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: hashivault
spec:
  chart: vault
  version: 0.29.1
  repo: https://helm.releases.hashicorp.com
  targetNamespace: mgd-security
  valuesContent: |-
    global:
      namespace: mgd-security
      tlsDisable: true

    ui:
      serviceType: "ClusterIP"