
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hashivault
  namespace: mgd-security
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      namespace: mgd-security
      tlsDisable: true
    ui:
      serviceType: "ClusterIP"