apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llm-cert
spec:
  secretName: llm-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "llm.trusted.nirmalhk7.com"
  dnsNames:
    - "llm.trusted.nirmalhk7.com"