apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main
spec:
  chart: open-webui
  version: 5.19.0
  repo: https://helm.openwebui.com
  version: 5.19.0
  targetNamespace: mgd-llm
  valuesContent: |-
    ollama:
      enabled: false
    redis-cluster:
      enabled: true
    podLabels:
      milano.app: open-webui
      milano.level: managed
    persistence:
      storageClass: milano-v2