
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  chart:
    spec:
      chart: open-webui
      version: 5.19.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    ollama:
      enabled: false
    redis-cluster:
      enabled: true
    podLabels:
      milano.app: open-webui
      milano.level: managed
    persistence:
      storageClass: milano-v2