
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
  namespace: mgd-llm
spec:
  interval: 10m
  chart:
    spec:
      chart: open-webui
      version: 5.19.0
      sourceRef:
        kind: HelmRepository
        name: open-webui
  values:
    ollama:
      enabled: false
    redis-cluster:
      enabled: true
    podLabels:
      milano.app: open-webui
      milano.level: managed
    persistence:
      storageClass: milano-v2