---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-secrets
  namespace: mgd-llm
spec:
  encryptedData:
    TAVILY_API_KEY: AgAI6eKQjj5pPSR4DIEKj9dMRFKPunsp+5SaEAj2PCDswpMyzZNtYHvdK/dCYDIHGBblw3CjlyiaO0dnxske875LWgR8tezSF/Aa7oEU+iO9klO1eq/pL9YhwcOeM4NvBC8MKxc2jOmCkQlKT1IOm7zINMq3+Cl40CZYndY7GdZgI2iWWG8z/+rBj4Sxv7/w9E01HhqZ7lZ7/hQaYifMnO2PA7dHGfjJ6bzNXekPNuv6yLJP2DzO5sh7M1ZuagxRe/0tQtw2dccEe+gzVN5y84lVYw315+WNJ98CUJetbxjQ2/p34JpVGU6EZtTmFb21V0TybxysxSy7s1MS1K7PMS/hBGEph9AEnL1vQqTxSW4dh44LUbsLNiytHx4oAb+zwZzAsgYSw+1VTgfs8ZureznGHgDVsX9mDLhTsXem8jvdehMh+hdXCEBNGjQoCADafizp8SThsh/ylztFfkFrEFo1be4V96acDIEMFdUDh8JqGkpCJhWI9R61F6UeI2EusZ+bY0h1s/AwzzIY8YIkLsWXR5a+BA9OQppbvmCLJyqOzJKfvIEBB/Gt4YLZmx7Kx/mMnbTwtSedMTY2qee55R275BBRWYsOPAPuw+amJ7yswDBim/rePi5QqJHpVVi7IyVo1NTDhyhZIBCVjLJ4yT1KyYRPEPuUk/sAff/DRBkSI9oHqn3MMJk0t6oOQpL8npzokQ5HTMUfIBxOh6x7atdQi6TkSMJjmST07e6ZKhVb9aG5/Remrnrw6jUehEGLy55U8yGAGGMVmznq
  template:
    metadata:
      name: open-webui-secrets
      namespace: mgd-llm
    type: Opaque
