---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: mgd-llm
spec:
  encryptedData:
    OAUTH_CLIENT_SECRET: AgB1hxISkjn23VPVt0H8La44Xq1q/ph9XcOMSs7gC89MrdJUL7C7Cn4hrEl2GCMU9peLG27ob/7AZRHtZYXeMZ0XAPjdT8LF4t71q9DwKdGnWLma5gjSLOMlkpDYckh5ZaOcOGFhIr5aqUC94Py8VMT0PSodTRV0HGozwF8+t3ZYc6xTiMQwYA8DCgvjk+tr0kNghB4aQK4TrmyzzRTE9aPnJN5XQlGe3x4poRTLlllQ3zf3bHUy1saaJMVR9KGnj4IaqRI/34UaUCAcAq9MvBIQ6BEl1Pb/rEvZ8oFfVwOBzdZuKlWZHVxgA39fdnLwU+3hRS+9F9H4imxc/Uk0nhfXQyTY/gDBGVs/CKUQxohT1HYZEkuzpLV3VFYpcVIl9ngUDBxeUKi5213MMKhFqRvRXy3tEh0tWMoJXCGrmvEN9BvRfu2S8BfKdxg7gclytJNbiJlyqfmu21m2VaOok2XNiyWaIyJtwtO4cWvgEvBXnWoqM3tkBa6OJujCFMfObpT821jOS852qkPvh4mNfU4s3ik4/wt8VCfg6gMRHDW/6iUqYnM+5kAuRW6VQMr2JGmMdOd92DuRu0AsFbMDaFMfrsMWN8k8NxPLE7clO0VOrcJoZN3Kv8mSyPm9B4Nl0pKdzFlEqz/4PBwm1ujXwUhFuLc/7Yxw5xMExJ0rDJZXxYP5HQcuU/3Koowzds+zb/TVgDrAN4pwaFTyoFIN61ZgpQDXZFSAOpLKH0myDK9Tb0GVkhmYDm2WVnc5CGFVX6GPIkA14lEn23yILUR0ieva
    TAVILY_API_KEY: AgB9FTcZVB+/hL3uNMn6+hqPEhKobsY4vb9v5wkr8FL8jYjTU1Lq8e/bba0hFGW8rfex+A6bA+XcozM9awbP9Jd9mFaiqQqD7uMfxMbb3m8YEpaDwNJr8nhwDDlA6yvHhA15EqpJEMAgdfLm75EpPdgmsVeMcjxhb/9ejQuUIQw99PFDZdn5cU855MNNs0Jz5gUciIqltJh+Pr6ie72JFkSaD4ukHsW1binfDuziR4XFXbQmx3ZJixtFxzbVkLg3xwhAT0a+hL7u+KuL5xclpZax1DrxsnQcxR024KomLAt3vS2aRKSt6L0FtR2WwFTbFtSxAtUiZf1HLUe+Ycb2sfAEovigyQOcmHhSQiYeoIe8jemmDuS+J1xnmnIHvqP0MtmytzU5lx1glIXQjgkIyWrBAGOma4Yj6CUysG7u7rDXF4WFxPdb3SBMFe48aqeVwSUGnCfc1vNkGYAT7qnCs35g3eQPXzYaXe7c+W4WPqGNnaZgnuhnMGB9nQditBvXh+GtxbFenK+TyzW4vMHMi8pQjUMef70FuOwhmamoI4/ASF8mmGdzHGLiczAUZj9vOCUyBVRnPGkwwvYNc0+BkQADIJmGr1JJ5WSMpI0Q+XzqlsU6Kg4YIEQj1fR43tBEAz9ghW4PjmKXN4W01s7erZKlnVTnKjcQQODafm3tSTASgppxXgDL1OzsAlbg+UA55K1khANg2lzd1LDiz2kyWSOwpxPhVgShiHgAOQ2O7MfNaW6d35RZkIjw79abfnE6AP8gas/W/eQZIGvY
  template:
    metadata:
      name: open-webui-secrets
      namespace: mgd-llm
    type: Opaque
