---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: open-webui-secrets
  namespace: mgd-llm
spec:
  encryptedData:
    TAVILY_API_KEY: AgBSjnNKWUd3aeVm1ukoFcG47NiRz6z1i8CtN3ZZIpJXmEBm76ehzbkyGFQkipOoo/xtGdlhoiPL8TzbJgTeTmw4JsH+JprfpdZZrn2S5efnQ1nrz5Vq3iefkG7N0oqxYIMSI0mE45+FzkQrqC7WKaWrQK2Q7MJK3OuJq3nX7WhiJOmbNAveckgWJXd3ya3LICjxFBpn0fqaiJHdDZe9Uf7SWv7WwTYVA3XVUDF6S3SuIdi2/2AtWzrrG4ZN3gmK4jAvkp9a7EaxJD3/5CPDJyN4/XRF0YtgddB/pf6Cs+9Fw7QmI8qC903QSYq7DNpbpz32nsGWLO4voe6PmMZZ7e0F5fKZaaeg1eDAN8tr2PSEhrZslVffKOF+5sYx2YNSB1LZfFiB06LpveL4H1VUSQRqKIDk+CIBKFCZsUZcyXBQCA9bZNglVxoqfbp/lRp/DnjpiKvJwAGN/goDz5G0/5Li4JaBF6PA7seqYrcM9thppng86viiOI4hirtyECgzxjSFTt0nZbN5YP+od6AVMsfGW5YG5K5uovfJDHYto27SZY3axwVYDfTzjvGers6jxJDL8xHb/NXr9P12JunUrCvzqn9vCr4EpH8gfI7FHE4V/biRITrS5lyr14WmDetNVIygpkrXxk/Ga4434Whp2edUUb7HjcgM2+GZ/9kZ8sG9w5mozK4McgrLBtB/PygY/52ymiWnRdKvyk9xjl3Cp+1xQ7175y0nKqZx8VcOzlfBoU+wqVJQnr0sIlaOmjViJrWF41fkm64sPpu8
  template:
    metadata:
      creationTimestamp: null
      name: open-webui-secrets
      namespace: mgd-llm
    type: Opaque
