apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
spec:
  chart: app-template
  version: 1.5.1
  repo: https://bjw-s.github.io/helm-charts
  targetNamespace: mgd-entertain
  valuesContent: |-
    controller:
      type: statefulset

    image:
      repository: jellyfin/jellyfin
      tag: latest
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 8096

    persistence:
      config:
        enabled: true
        storageClass: "milano-v2" 
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media