apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 10m
  releaseName: jellyfin
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
  values:
    controller:
      type: statefulset

    image:
      repository: jellyfin/jellyfin
      tag: latest
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 8096

    persistence:
      config:
        enabled: true
        storageClass: "milano-v2"
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        existingClaim: media-pvc
        mountPath: /media