apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mgd-kube-system
  namespace: flux-system
spec:
  interval: 24h
  path: ./clusters/managed/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: operationscenter-git
    namespace: flux-system
