---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-oidc-credentials
  namespace: mgd-default
spec:
  encryptedData:
    N8N_SSO_OIDC_CLIENT_SECRET: AgCYzNwspYYETvINAnEHV48XMirhWFVCl7kMNUG+JnXybS+bcws55LlBMr90ftry8f0W90YQ9Vdr9f0BYVHCSJzuUVZuXLNejRxr2Py4Eue9ynKUnqLDywIavRXg0+7DfvmKPK2CfuHKz+52uiDrOioqJ5MJMpu+McoBALqUCI+M8AkQETbPnXqoW9q+Ug/kBJa5nIrqUR4lWn0Z5TdY5Wvtn27/gUpSYDqQaXS8ClJ3b7Yn0u76QK9HnUWLb3o5R0bDUHXTx5HYvU4Q772kkGb6XwuN3V/pgY4Xxrzl1Ho1EEqoRy07KwKiNJybw5KCkN0/R9QdsPSPnG2pOpxwuqnRUVqn8fbeYo2UZ6woSt3ddHnBfad4+r0+9XO2wjs+flUTnBb9SpUygSq+2HjB6eUPqQFafUEihFPTV+Z8EIoFq5uWSG6ewN8szyYOuR83bQeLx3V9lMZ1wfuO2kx/Bl4phSGQgbYY2+fEZ6xJFwi4+ZPfCpTOrLMsEn7aOg9VEv3uGtbObJwPZkFCaAPqtyzBXIRgAf+WofJr5tGjOLS9IwdRHN6ORzB0ARURg0F1pnIAnF8OA7SoC6U52fxhEsv9foFiUOCRqJfJyo3CqrLUKNLQke8n7N3MMwsftDPSbu8sYdBZG/ELo2WB4kvX1XFLTK+hM6ne7x8nqLiARHuIis3TwYHPmE7I5pbBZS1YjzbA5AbKoYkcdOKUNSRTC+AHyiNqIpobyR+IAZDPiXTjhNyalDQeIuVF8pYWmlP1RmEdPQ4LU6FfleUwgS6qfU0N
  template:
    metadata:
      name: n8n-oidc-credentials
      namespace: mgd-default
    type: Opaque
