---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-oidc-credentials
  namespace: mgd-default
spec:
  encryptedData:
    N8N_SSO_OIDC_CLIENT_SECRET: AgCJMhYbz5+lnhwWk5K4wOyLEkJbgiKe4FPukN/87fPP0seCLPxFPZHW5Ts6R8jneZ9oXeGlaYARRB6IA7nt8HYx00ulUGiMQYcn9IDq6piCBS2w68s85zM7Bw+XGEAbl9xn8LoGinwBvCfMVzVLx0XMA8aKcCtCAPskjVJYj8yq1ynZbIiczPzk1ag0+fNpdDikrnSREzb5WutI+VZRpxpfPdreO8TryH45skdk9KqqTKwh4SFMBYHs3mgmGZ7M3XzfZnWOqFgLlC8WZYDviXj7MQJ/9ZVQZagUxy0ymzkY7aQueDoQ0Gz9mKHjpJ49noKCZyiqvmZwgcCCTzOc84N013HvOEXEldlkeEz62txxwUqEdBJSy3y4UPUJsoRnrNi1mO1O189o9M97POkXDZ/lnSJIutkasMyYwfA1yuAfvy2c8TLR62V5zOrOdjdbQmVl0AkVOYrzrb9RbPEyt7enVAGm0g4REWlGjiygaRPAZrGwdDndSsjrRnnVzKo4xtzVW0Rzjeaqv0yMpz7rF57uvujodUqBIwHRMF3Pfj+WaLm8g3eYeY+6sT/psTHqaMuOyhjtEL79R2bpujvz/Tx1dWPiBqs5wvvepFaRbSqnN5Ge199/H8EfI86Ec0dwPXjn5UXUQBfcekqFszSHOXYh9Z9CsgTZAkqkVWjVPXyVUlbTZ8gFV43M9t61DtnRR00NosRMd3OuMkG0MxlFAOQb9iEFifj0Wag+ZSrBBrWgWOyyW6pxhnZrvyR9B6x1dSwPMBrBETmnOU2ll5CNPyng
  template:
    metadata:
      name: n8n-oidc-credentials
      namespace: mgd-default
    type: Opaque
