---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgDKm/r3W1jKVuWDSzz4XxTCCmp2H9+ieT+A85S2iaexZgHee3+gIjVrK94eu6uTo7Ou4WCGn40Dkcftv8lU/3GLNjgnXFEkr6OaPN4rVsZY88iiY5vrjlpjIz2yaChUARaP2mztd2uK8FbctoqMhK20UTCww5RRvLAzlwsF+tl59BRIoipJvLq3XSy+y1ZeY1n9IINT119NS+28tbXuLbHtRAPtQjX3Z5D+BBj0Y7O0EL1IiC2B7e68NXzWHcZr1oTgl/VnEJ/7B0EfBKDis6mPZk6jMR7Vt9y5rdS7GxuwWAp5UqEWXDguZgDHoSkPiya7WaDDhXbSDXxYZypoQQ7DpeJA8fwXuELu6aYjyITZG4Yhfqt6ZnxZSrH7ioaWNL6MoZQJp04fMBZs0L04BPu7xbEMs2OyI+FJyHzFboIQectvKJDItEbTBSrZY0WU9wBj2lrQC8aMzs/9DcK87BKoeMs+5AdGiKPusWWRYlPUQdTNMsUUHqOxbDeZhkVdAyEgQxeWsZp06pisfByOLQOAV0uK8U8o9hnWRPDV6Rc8BKQX3PY0yAvfz8d3Ttxj6uZiP0SlnZPvc/ZSqN5QKDsJIJsIrM/ycRgojV7L6BaUbisue2tx4h3Jma1jKvpNaSHrLlTRFe171yZcoP9WJUOmbWmEDnLF10hP6pzeDE8CWl9/lMrIJdDnzd+2lUQOPVw=
    DB_POSTGRESDB_USER: AgC5Kjh0ou7L69NRUjjaFbdxFbHwGwHZExUIlvaRrwN/m+PAW+2Lj+YEn08XrOKhcQWbd6YrlbsAd2IkxMDDn7K5VUjOg8Imxhnr7BLcB4VUHG4mB13tquUOgNVl4ofPRKWa/yOZHJiXdP+XcCOLwBa/xUK+f58zd2vjaIaBpExZ4rOUsj5nb3fWlibHKsSU+WfnVKE7+hi3868PMLFQwOG+hyFag9SX1Td72cf5WNe/TQauIOvJXAY/kzNg57whArPfAXXuprkBMWMGa5vwIxVJopRQery89xo3e8Hytabv2EDvLJkLpFD6LYM5e8kbj0pX5YpYp+b5SDrQaUUwW1rxK+hPmAF5ry3/oEcGKfe7i3e8WBdgleAJR2pkN8ebquFP8F3enZcqIReS4BLwGuuRaOWYwCZXNuj2PeCRXMfpQLACqaEimoSyZwocDQJOJu3T4B8q+TDedUqJstzCqvnQJUJON9OTOPHw0YR/o0E2wI/ypYHFAKVFAVCnrlZj+m0vy/bsc1MAH8sSNLXr3K2mTMlEQTfGfYiyPBFHzTciUgWpOFeQtnNYiaC+xp9POiXXCcYHkQyxzNDpau3OZiCOUG7vmrFNQ6KOFcmncFG1nzAC8BPWw9Xc8ri2x2qcJ+eURYFj8aOPzdm2kJproAVkIRB0tkxHP2Q03h5J5yuuPhA72BIOHAmrcsiZBClwwCCw34kyDAA=
  template:
    metadata:
      name: n8n-credentials
      namespace: mgd-default
