---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_POSTGRESDB_PASSWORD: AgBlW2yLcfC0d+yYG1ex0f8herv/BNC3FA21do40SiD0aI2SRlz+MA+DuXlYSdx9eMeAav4SskSHdqbS9G6Azo1B+X9LsTbMExZsaAuQLGL3g/U2a2Th7t1xszLhhaabhqJGaqlOZIqve9zIiGYMp0CH8dXWhIT71cfwYXwZxX5lnMMcwvS09uYvxSbQl/l0bLhFvDBIQcHkjANiQlLpnfuapJ6/VOVJR0C+Hy44BIIWQpuCVKaIrgnwEbjYpHid1q9EshxxQG9o4Mr5gRz7yyEHc8GrnvKH1XMrZNmBpn28KAL7iLyFiAPI+59ZDqDaO5xXbqk8Hg2L3EzIvyvzFjwLhxnijOA6jG6mV99fXAayvbKzGVX9iVGk0E27yRCEefSvIISz/Jgvw0G5/AUctK9BaoeDUefmQTk2joGzDTiTvhQkMexlNG8aEfEdFAmI4ju8wGXWZxUbN8PFtQG1FShoiNdtUDhxS83yI9rAT+p8LrxdI+ApqikD5HV2/aiX6/jwBoHYS9vC4ueuRkEC+CKpi+anye5CUyMmoZfbmW4Adv+QJLWG7AK2IC5sBNJQn6sCPqwHmI8hm33lv/Rte64+Mn8WoaymU3nX9iZz29EtbTvT9o5P6h0fpnA033qB20X66VtpuypyTPgH5kTWEAPK3xS1bIBs84XeWskxAwRATAB4VvjIw+DZHs1cH8Z+TbTHGXFqvlwdJD+k5zUR3gDE1lpUl3AEvVTfvL8kyHenXMoxx6WfkdVW
    DB_POSTGRESDB_USER: AgAfY7vy95rfopGIK6JaFaM0CYex2wc7OyVqwlNE5p5njlTWK9ubkRxkuQNQF/5jv1EXlTNbDOzScJjt3smQ3nNvNtwbPb4EYWYX9bV/EhmbET5fLJ50wegnQtbxLXCm2TjpAg5hulLekfaJPZJiACg0XoXXV0Ua/3gFstolX2QqQIUx2IvUwr5SWBXXvfiyupR+blx9k51+ORbF0OUWUwiRLIYA+9yhkZ8skmo/n1/gjivkyNkxFmwPMbDCcHBmEpf0TsXGj3aMomV7AdFDlPKWQ8jQ+emrYhF5qfBZmkwH4NkwW0KSyZStW5eBx+mFqb6Qv5Qo7YQItVdq0PZS3H4Bl9BIxYtH5z9HWjKRytHa10DnEJGZ2HnpzGRJPNYM1aAuFOpb5HZ+7MVzllYsJl70Jr4UJHqWlJ9J27ixKZ3f32basuGM+dWQb3a7Fb62xlaPrCvMNxvUNlcF9dpE/0b1M+Kf89DJWOKie/eCgr9QbG/RnOVavXbXAOA1ctsdq/PVytonGd+XKY2VzjX/D8Pul0jMt+fm4i73RWntWLLG7SxhV8wkRy+0H04O+cb9h3du7AlYDxXfbpx7sOodH4GgG1z7OPZTr0TnJ/YdbtB380GD40jxt31WspHbLMlfg8uBNwOQ7RX7BK9lfOzn+VBW3N4p3sfN07lr1wqOz9F63MyOMfbnnTA//IKX3JZZhWhJo44jqDs=
  template:
    metadata:
      name: n8n-credentials
      namespace: mgd-default
    type: Opaque
