apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-touca-app
  name: {{ .Release.Name }}-touca-app
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.services.type | default "ClusterIP" }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-touca-app
