apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert
spec:
  secretName: prometheus-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "prometheus.trusted.nirmalhk7.com"
  dnsNames:
    - "prometheus.trusted.nirmalhk7.com"