apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: main
spec:
  chart: kube-prometheus-stack
  version: 69.4.1
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: mgd-monitoring
  valuesContent: |-
    grafana:
      defaultDashboardsEnabled: false
      env:
        GF_SERVER_SERVE_FROM_SUB_PATH: true
        
      grafana.ini:
        server:
          domain: "grafana.trusted.nirmalhk7.com"
          root_url: "https://grafana.trusted.nirmalhk7.com"
      
      sidecar:
        dashboards:
          enabled: true
          # ConfigMaps with this label will be mounted and loaded
          label: milano_grafana_dashboard
          # Look for dashboard ConfigMaps in all namespaces
          searchNamespace: ALL

    prometheus:
      prometheusSpec:
        externalUrl: "https://prometheus.trusted.nirmalhk7.com"
        routePrefix: /

    commonLabels:
      milano.level: managed