apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app main
  namespace: mgd-monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 82.13.6
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: mgd-monitoring
  interval: 10m
  releaseName: *app
  values:
    grafana:
      defaultDashboardsEnabled: false
      env:
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
      grafana.ini:
        server:
          domain: grafana.trusted.nirmalhk7.com
          root_url: https://grafana.trusted.nirmalhk7.com
        auth.generic_oauth:
          enabled: true
          name: Authelia
          icon: signin
          allow_sign_up: true
          scopes: openid profile email groups
          empty_scopes: false
          auth_url: https://secure.trusted.nirmalhk7.com/api/oidc/authorization
          token_url: https://secure.trusted.nirmalhk7.com/api/oidc/token
          api_url: https://secure.trusted.nirmalhk7.com/api/oidc/userinfo
          login_attribute_path: preferred_username
          groups_attribute_path: groups
          name_attribute_path: name
          role_attribute_path: contains(groups, 'grafana_admin') && 'Admin' || 'Viewer'
          use_pkce: true
      sidecar:
        dashboards:
          enabled: true
          label: milano_grafana_dashboard
          labelValue: "true"
          searchNamespace: ALL
      envValueFrom:
        TELEGRAM_TOKEN:
          secretKeyRef:
            name: grafana-credentials
            key: token
      assertNoLeakedSecrets: false
      alerting:
        contactpoints.yaml:
          apiVersion: 1
          contactPoints:
            - orgId: 1
              name: telegram
              receivers:
                - uid: telegram_1
                  type: telegram
                  disableResolveMessage: false
                  settings:
                    bottoken: $TELEGRAM_TOKEN
                    chatid: "-1003812665515"
        policies.yaml:
          apiVersion: 1
          policies:
            - orgId: 1
              receiver: telegram
              group_by:
                - namespace
                - alertname
        rules.yaml:
          apiVersion: 1
          groups:
            - orgId: 1
              name: Sample External Alerts
              folder: Infrastructure
              interval: 1m
              rules:
                - uid: example_up_alert
                  title: Endpoint Down (up == 0)
                  condition: C
                  data:
                    - refId: A
                      datasourceUid: prometheus
                      model:
                        expr: up == 0
                      relativeTimeRange:
                        from: 300
                        to: 0
                    - refId: B
                      datasourceUid: __expr__
                      model:
                        type: reduce
                        reducer: last
                        expression: A
                    - refId: C
                      datasourceUid: __expr__
                      model:
                        type: math
                        expression: $B > 0
                  noDataState: OK
                  execErrState: Alerting
                  for: 1m
                  annotations:
                    summary: "A monitored endpoint is down or unreachable."
                  labels:
                    severity: warning
                    namespace: sample
                    alertname: EndpointDown
    prometheus:
      prometheusSpec:
        externalUrl: https://prometheus.trusted.nirmalhk7.com
        routePrefix: /
        scrapeConfigSelector:
          matchLabels:
            prometheus: prometheus_scraper
        serviceMonitorSelector:
          matchLabels:
            prometheus: prometheus_servicemonitor
    commonLabels:
      milano.level: managed
