apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - ingressroute.yaml
  - nginx_scrapeconfigs.yaml
  - tailscale_scrapeconfigs.yaml
  - docker_scrapeconfigs.yaml

labels:
  - pairs:
      milano.app: prometheusstack