apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - secret.yaml
  - ingressroute.yaml
  - nginx_scrapeconfigs.yaml
  - flux_podmonitor.yaml
  - tailscale_scrapeconfigs.yaml
  - docker_scrapeconfigs.yaml
  - proxbridge_scrapeconfigs.yaml
  - homesecurity_scrapeconfigs.yaml
  - k8docker_scrapeconfigs.yaml
  - k8docker_prometheusrule.yaml

labels:
  - pairs:
      milano.app: prometheusstack
