apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: openclaw-node-metrics
  labels:
    prometheus: prometheus_scraper
spec:
  staticConfigs:
    - labels:
        job: openclaw-node
      targets:
        - 172.16.0.104:9100
  metricsPath: /metrics
