---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-secret
  namespace: mgd-monitoring
spec:
  encryptedData:
    token: dGhpcyBpcyBhIGZha2Ugc2VjcmV0Cg==
  template:
    metadata:
      name: telegram-secret
      namespace: mgd-monitoring
    type: Opaque
