---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: mgd-monitoring
spec:
  encryptedData:
    token: <encrypted-token-placeholder>
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: mgd-monitoring
    type: Opaque
