
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
spec:
  secretName: authentik-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "authentik.trusted.nirmalhk7.com"
  dnsNames:
    - "authentik.trusted.nirmalhk7.com"