toucaApp:
  dockerRepoName: "touca"
  dockerImageName: "touca"
  dockerImageTag: "2.0.0"
  webappRoot: "http://localhost:8080"

volume:
  scName: "milano-v2"
  size: 4Gi

ingress:
  enabled: false

services:
  type: ClusterIP
