toucaApp:
  image:
    repository: touca/touca
    tag: "2.0.0"
  webappRoot: "http://localhost:8080"

mongo:
  embedded:
    enabled: true
  host: ""
  existingSecret: ""
  image:
    repository: mongo
    tag: "4.4"

redis:
  image:
    repository: redis
    tag: 6-alpine

minio:
  image:
    repository: minio/minio
    tag: RELEASE.2021-03-17T02-33-02Z

volume:
  scName: "milano-v2"
  size: 4Gi

ingress:
  enabled: false

services:
  type: ClusterIP
