apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  chart:
    spec:
      chart: grafana/loki
      version: "6.44.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: mgd-monitoring
  interval: 10m
  releaseName: main
  targetNamespace: mgd-monitoring
  values:
    loki:
      useTestSchema: true
      storage:
        use_thanos_objstore: false
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
 