apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      version: "6.46.0"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: mgd-monitoring