apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app credentials
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: vaultwarden
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: mgd-security
  interval: 1h
  releaseName: *app
  values:
    database:
      type: postgresql
      existingSecret: credentials-db
      existingSecretKey: DATABASE_URL

    vaultwarden:
      allowSignups: false
      verifySignup: false
      requireEmail: false
      allowInvitation: false
      showPasswordHint: false
      enableWebVault: true
      enableSends: true
      orgCreationUsers: all


    persistence:
      enabled: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: "milano-v2"
      annotations: {}

    podLabels:
      milano.app: *app