apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: credentials
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: vaultwarden
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: gissilabs
  interval: 1h
  releaseName: credentials
  targetNamespace: mgd-security
  values:
    database:
      type: postgresql

    vaultwarden:
      allowSignups: false
      verifySignup: false
      requireEmail: false
      allowInvitation: false
      showPasswordHint: false
      enableWebVault: true
      enableSends: true
      orgCreationUsers: all
      
    persistence:
      enabled: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: "milano-v2"
      annotations: {}

    podLabels:
      milano.app: vaultwarden