apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: credentials
spec:
  chart:
    spec:
      chart: vaultwarden
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: gissilabs
  interval: 1h
  releaseName: credentials
  targetNamespace: mgd-security
  values:
    database:
      type: postgresql

    vaultwarden:
      allowSignups: true
      verifySignup: false
      requireEmail: false
      allowInvitation: true
      showPasswordHint: false
      enableWebVault: true
      enableSends: true
      orgCreationUsers: all
      
    persistence:
      enabled: true
      size: 5Gi
      accessMode: ReadWriteOnce
      storageClass: "milano-v2"
      annotations: {}

    podLabels:
      milano.app: vaultwarden