---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authentik
spec:
  chart: authentik
  repo: https://charts.goauthentik.io/
  version: 2024.12.3
  targetNamespace: mgd-security
  valuesContent: |-
    global:
      podLabels:
        milano.app: authentik
        milano.level: managed
      additionalLabels:
        milano.app: authentik
        milano.level: managed
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_POSTGRESQL__HOST
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_POSTGRESQL__NAME
        - name: AUTHENTIK_POSTGRESQL__PORT
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_POSTGRESQL__PORT
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_POSTGRESQL__USER
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_POSTGRESQL__PASSWORD
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-credentials
              key: AUTHENTIK_SECRET_KEY

    server: 
      podLabels:
        milano.app: authentik
        milano.level: managed

    worker:
      podLabels:
        milano.app: authentik
        milano.level: managed


    authentik:
      secret_key: "dummy"

      error_reporting:
        enabled: false
      postgresql:
        password: 

    redis:
      enabled: true