apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - ingressroute.yaml
  - secret.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      milano.app: authentik