---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
spec:
  commonName: nextcloud.trusted.nirmalhk7.com
  dnsNames:
  - nextcloud.trusted.nirmalhk7.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: nextcloud-tls