---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-credentials
  namespace: mgd-devbench
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBTdXpNFivy82GZrDn01gJa5iN+0IZpfM211jWimhguZBRiT+RDe7pkxTZAEAha5lDPXBA4Jq5N7UcyzRqQwcZNjjT7s3Rg2hS2nEn3/BKrapNLdZiDa0OQ5Eq5ZJSV04Qat3jkUvDwq4cbIp6gih27gqRQfU5ceTIXRfD/C4kAi3UTIdWfvW2ioNxbRWifoOyAuPx6BM79ZcpxfShHnEcWBOYwzq0MNcaXCdNZTAkT3gFb/38qHq5V9w5sjUq6rtCt3ma8oAD36Qwbx/mgLlZrFIDgkMMeeRBQ3FCzVAc97ZqoybY58nuB1CX6/iBF1fA0hSvae8BrBDMHHowwW4Pr63lyO/+EzScLn/8OTTR7ubyU5T1qe4HwKlIWKR4E+XSjhdK6Ahnid7odIf7c72XQFWQ0xZMXeP74OSbn9on1HyEXv11PJVHngt04JUJg3ly9sfMgNUId7NnRYliKHjoaw5mn9Aq/5qrwbp/SNotHeQ/Rl2MjV8L1mcUndaDDfUrRoVZHkifWY+20buk9EQqJ0eNg6EQvSl6pXfho/Xom+5TpOVicdAOLc4WBU9tJtgQpAOX1zeFhChegyr6+WSWKUDtbS7R0BKI1ioZINT6ZPxzu3ns8L26/eG31rVqdHnpD6w5oe7PmCSfThC/piSaPnG02m9mvYGkpLLJKXnrTqpjWqa6tvJfbwl/X4vR1ipizW3e1rQiPnf7JN63myIwW5MoeWbWN1oB+PFxkVcoSQJ4aEO5U/0qV
  template:
    metadata:
      name: renovate-credentials
      namespace: mgd-devbench
    type: Opaque
