
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  labels:
    gethomepage.dev/enabled: "true"
  annotations:
    gethomepage.dev/href: "https://grafana.trusted.nirmalhk7.com"
    gethomepage.dev/group: Observability
    gethomepage.dev/icon: grafana
    gethomepage.dev/app: grafana
    gethomepage.dev/name: Grafana
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=grafana"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`grafana.trusted.nirmalhk7.com`)
      kind: Rule
      services:
        - name: main-grafana
          port: 80