
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: mgd-multimedia
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: immich-helm-charts
  interval: 10m
  values:
    image:
      tag: v1.142.0
    env:
      DB_HOSTNAME: 172.16.0.106
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich_rw
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: DB_PASSWORD
      REDIS_HOSTNAME: immich-redis
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: REDIS_PASSWORD
      IMMICH_LOG_LEVEL: verbose
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          enabled: true
          existingClaim: immich-pvc