
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
spec:
  releaseName: immich
  chart:
    spec:
      chart: immich
      version: 0.9.2
      sourceRef:
        kind: HelmRepository
        name: immich-helm-charts
  interval: 10m
  values:
    image:
      tag: v1.130.3
    env:
      DB_HOSTNAME: pgvecto.mgd-db.svc.cluster.local
      DB_DATABASE_NAME: immich
      DB_USERNAME: nirmalhk7
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: DB_PASSWORD
      REDIS_HOSTNAME: immich-redis
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: REDIS_PASSWORD
      IMMICH_LOG_LEVEL: verbose
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-pvc