apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
spec:
  chart: immich
  version: 0.9.0
  repo: https://immich-app.github.io/immich-charts
  targetNamespace: mgd-multimedia
  valuesContent: |-

    env:
      DB_HOSTNAME: pgvecto.mgd-db.svc.cluster.local
      DB_DATABASE_NAME: immich
      DB_USERNAME: nirmalhk7
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: DB_PASSWORD
      REDIS_HOSTNAME: immich-redis
      REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: REDIS_PASSWORD

      IMMICH_LOG_LEVEL: verbose

    immich:
      metrics:
        enabled: true
      
      persistence:
        library:
          existingClaim: immich-pvc