apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
spec:
  chart: immich
  repo: https://immich-app.github.io/immich-charts
  targetNamespace: mgd-multimedia
  valuesContent: |-
    image:
      tag: v1.119.0

    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: db_hostname
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: db_dbname
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: db_username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-credentials
            key: db_password
      REDIS_HOSTNAME: immich-redis
      IMMICH_LOG_LEVEL: verbose


    immich:
      metrics:
        enabled: true
      
      persistence:
        library:
          existingClaim: immich-pvc