apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - pvc.yaml
  - helmchart.yaml
  - ingressroute.yaml
  - secret.yaml
  - redis-deployment.yaml
  - redis-service.yaml

labels:
  - pairs:
      milano.app: immich