apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-user-content
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
    - hard
    - noresvport
  nfs:
    server: 172.16.0.107
    path: /mnt/2tbhdd/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-user-content
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: ""
  volumeName: immich-user-content
