---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-credentials
  namespace: mgd-multimedia
spec:
  encryptedData:
    DB_PASSWORD: AgAY7nuKd6UH1dWNk37BFho61XL/MopP9YCMorIjUQaLnolpU7Xar+ErDA6EYcgz6jcEz5a3qHwz4w0S7vai19civk2NosUKdRdYb9KB7tuX+TqQO5a1r0pBAhZVlKcI0k4C7IAlqJLtOPsrMw9gEFzdV8ggZD/EQCCacTfPbNPZXRLYiez/K1bdBAydfnGWTs3iukiQK1WwtOM6DNzi34ZkmGsHq54jjQ4xweKL4cc4J9XowhKl49bp25eC2piMrvi1RSmR8tniXcdpsekeTdZT9rYFXgI1j7od62N/m7C9AzKBcKWDkZieUzPY/wTATUoTQaE58UbBupyiZwM9OYevA084T8Ajxks4ZIUylkJ8HRPndx4wrRs25DjCj7qY0aWA6bmTqoMEMfpQAmNUwIC/Mc4zpOHcPI9GtpHAThLMFfrCJi+Wn4MP169AbXrCQPXtGiMfecm5Z4I/563lkW7WqWVNiwraskQN0kPGX87+gPrsSjLsx4k1AlGboRBrI8Xpoj48I9MaqWVPBYiz/S6p3qH9fg4WLp4jIlnQaHtVLzY9Z7QjWWI6Y6EzTLchVepqGfvpUSIf6ONlQtamogX90gqsFtPyLnNpB6izSmge5PALFyeQ3OsXydU0E6agZRAiJf4PtBQI0cdhfM0/nUjZgUSvXmoexE5jDjguXrEPj8f+qajH3ZJVMkmoi2cNAd2T+SFd5RzVlwhsVUsBf7n6rchGYA==
    REDIS_PASSWORD: AgATa3TvOOAdv7wV2/2GksrY/VoPPJUCx2i5hm8jEEh1fN6s63oiqtDXpkNqKsPMV2oZMr7xPnDQA9E09HsPZQijyYtfruKGR6naAxeI/yyZ15xxE+21V2VByxBueFtgN7nojcnMeULi4iAUrbfZAyr8hXV1k4ZGGoknMDsn+OEflbV6WlqeCCE1qFpI7VX8blVqN5GQRJIE9Y/M57BIRn/KhVg6SdRV8S5CWH4ZsIgMWaoclZNViL4RIeftC1QnV3+B1S6vvxWCmTC1fDgLg75JvXTH6qcrHrQe+bJHRnvMANCtV4HhvewT6VTq3EyuEU/gK030Bwo6/6PWhYjVSKNDKq1pB23igRjuwYrOh29TBObiEDs8r9jzEEPmJtnT3SAVuw/vnH4NA5L0x0y7kTo7ADrLGQ4Q2Xu+Z4MEDDwvvtYSfv/Wz6umVNtHpSOWP2H89EKHptDrMGVa2o/pPWCUDv8Xo9rsmY1V0VGVho3eJAB//eSxAaDHf9QNWoh31IDJUY/eBC7XkBe8XmLJ0wYzvQiHojD0a7+K1+A/3gBuNByLrUw7LuuVhugD/3Q6Qd38KPYD43j54fWbJZNovdjap0YkTQm3EvJI4HByfnTxA9roZRtwXBuuzV2FBP9HOT9Yt18ZLaW8znUaifLE0OyfT9xEx0sndx880A/wMAWDEgEDk5E4Za/sMRdFN16m/ER0MLw0FThS3vog7xSxneg1wi5fcAw=
  template:
    metadata:
      creationTimestamp: null
      name: immich-credentials
      namespace: mgd-multimedia
    type: Opaque
