---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-credentials
  namespace: mgd-multimedia
spec:
  encryptedData:
    DB_PASSWORD: AgBYjffIYTS1PFlDf0SOGOQ3vGbFr5Ap49TdtGdQ1zGKl6IIG3hIbst1467AK6mXz/oGC12noHfRRIMtJE6rI8TFPzPcS/WSUpFC2I2Gj8EKrn5ZSyPILzvLQbCjd/e6sZ83j6N+VQNULF04MKbmXIU0ZlL4PPjQBgd9nSJZYe7KUzdeVUWClj/8RIabGslAhsQ4+KRH465eFkuCPyp2hSGTjd9gOnbpkZv54sQlOCz5yYvEMMGdxNYuhJ44bnkpw9lK83XaY84vlDX4pEsyKdVpJ4TUizcuDVn4BHJiaQbxI+PEXXqU64gOu35DMJldZbghLM4z0EqXuAexFlEQb49fmsdtK/1daylcttoX3ep3HR5By8lXa2bEoHKr7X1SYr0dVpAqSSEWt5vg2N3XEhILWEibZlqjon+W2/8+xJF/lwzQuRTQ07Rm3nyDhvCKjFKOD1QLKXPuPFTfce5C6P7uspYobAfkB1Athm7ieoR4JyGLMdEErdRLH4v4sivt/GkOlbwuH5X/ddxc3uunI/rYEV36Me3Bppr3Tj/Og+BguVOlozwKsybiIyZs6hTKaQHehBpvpMUt+XLi+GygsGmVOPPyQRpcPIWiFNw4LlnbnDZmLGGEme1zPxUiHFIHC395vHt/lcu59jhP1y/YR3puzR9omGBXzE9VPOc9nfqg4pmxDaSl2pH9yQNyD0kizz8/glUU13JWIJ6z
    REDIS_PASSWORD: AgDTQDQJldeWdKCuBwQS0iWxeQGuZMA7XmLnTnHVUnOqftOFjNVKZJTYhmcnqd5XJPsj+etPhOisfi0k+CU9rYmOZyN0dVuSH0QU5/rURML/bdWT+xl2YnI97375nbmib1H7y91X8WCXCAarMe/CraEp4Ep5n1UZK+4QQSD3HEhZx9rOY+/lTpD8eMcgRXAi8DZv5o9pI/R9bWIah7uF3T2XQgOXtawJ5yVJgBEAiQPGaw+4xZ9RY4SHRSOl1BtIXUgXgusXC3JWKJ5O9W6WbRHDeEd1GK5/Xbc6nb7emG8HHJFRGm3C1XKVDXYXlL7x+wHOiUehglp/7g7vchKOFO08CVmhkB0UgnQDwUEB7aUgPneMy8HaZ5V6pO/c+0pJeNZcc1uuBQWYIOicvmz3RjvbeVwuB/QjZcSZxlz8sp5El53x6+FHABdi4xJSdeoq/tMpsFc/eHUFtT+sszD/r2OaDCxhti2patvrYk1D3bjU29aJon8L3pZHeOSwsOQpi6ikboZMiJgx0WZiyQM0rnFVt7Nl7ge24Pk+nJSqz+DLmJLtsjwlTvqUFKGvh7cur04WZBwp2GL4rxW4qjvM16Y7Ct7IwXkyvGOdiapVKEGDxJxKG+tuf9YPfT83q0WwmyGt6ByQtzR90WAMXUeXr5IlQkILfBqL/YP37bHZAj30zRDgWwWfoImqCgqZGFzZMfLgQNePVQOvrNCFNx/rnbwjC0wtCRU=
  template:
    metadata:
      creationTimestamp: null
      name: immich-credentials
      namespace: mgd-multimedia
    type: Opaque
