---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-credentials
  namespace: mgd-multimedia
spec:
  encryptedData:
    DB_PASSWORD: AgCXbOXPw5K94B8DPPO9gejFCr3QTdQZRClWxxW160G/rJ3NFcWJ8g4ABVUTFy+eTKeAPPTl1X+gOOD8cF7GX/mXazd9/Cvwlmzo3jBcMURavf0nkMX8h9lgFQNdFzH9DoZxNJiYJwyM37XcBgPpU5kKSHjy8xxFBjVpEQ0/5d3RvD8XSkIMUW9G9FMlis++zcMfRp/ibQFUQkUh1zbayqpRxT8k4BsH5/uOQVXrpOxZ4SNag4nXCbOwJicG/OB9fTRNtSOjImzpfYNVVNrghzft0TzK/yG+x5Lt2ofXUR6R2yLxLW49XvAhnAVUgbuy/J08kqcCQjsLGKXC4uogDCL5bh44rNrrdVC4irxB288X2/Mg0fylHv2XUzbO+pElkFpaXIpHvupP2w6TuZGao61lEQihflk/beeUDmSyCjkPtMqjHL0CwWzDTEh7OPk7fdrJakSDuKYXMwAeGxl2igQD1U4aFazMqKqwvK6RledG31IL2Zjef9p0Gq/yLujln7ZWiJu30aYZKKcjRiL7McVNacQhBT6bM2YiPWZuPHX39WS7N0hhM2scxpf26CQ0DA9UCGy4cWOQLAj11pc1I0IIfdSarfcHfCyh4JXKLSvBbvrms6wFK+oa/xzAEaCFgWOLfVKARZ95d5q8aDdLLyXMClH//5xJOCF/yd49FX8h2CCLpXmWwmMUCXpEHJ8NYCtknpR1vXP11aaQ
    REDIS_PASSWORD: AgAZnxg81tU97wcxRGfQ7VP733Zh+JQwnXCgZvFf3fL/9CybAC03iMABKsTyu1/MFtQvaDj4eYT//xHV0MEXlrUgoLWKt9L9EiEYMuWiPzm4kjB3wFAOM6xvuJxHTT9+7Is99iQQthulb0/jlirp77eRxfavtqTcCJwu+QnRJN25Ya05lqCRjA78n2gezLaGZGtMpJSV2bt8CV7IEWMlS3U+RyFva9oVNFwjqK1fnOfBffSxK6x+lvJq3ruSOyUuA/zeXa1u8cqEU9tpX/D6FuPwjai4kWQae3PZ30u/JlTotohAPz9QqyzOgpbc9s3+mJ0E8LJUpOhKTmkG8kDQm3QFGiS1uZY0RaxQQf7A8f4gZnOVqFFfkgcQQEqV07ZiiyWx7RqsilM9eyaCUTuq/xfA+mIah81+vNCBzVQ5bzXWSO/OHvCSPFtVYYkO8rfAEz7sosKiLqTyICc3YSAlw44Az9DsGgS9S8JQIoZ4rYU3V29n0mqjEL6FYcG0nbqdenFoqCgt0FJgGyKDYMN71m67qcTHXbYS6omwhBS3QjHnh9qA7t3HlaZ8GgSKrUP/0qOTIyLq0qD/NFthYaQ75kvzvdghlzkIS/JLYx34EPiUCLGZgAMm1hTTixZHCqRwG3sw5dJrLl26dPcothF9BMPgBjH2zvdWwbKJorcz3s1bqFxGnwP1wTPuc+NaaXSnzDcmuRf2+wWIG91axOKE7kI2mbdB1HY=
  template:
    metadata:
      creationTimestamp: null
      name: immich-credentials
      namespace: mgd-multimedia
    type: Opaque
