---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-credentials
  namespace: mgd-multimedia
spec:
  encryptedData:
    DB_PASSWORD: AgBdarrfcjSrG+ra4AgmqP5I5q9VSnnPf9zBfCUDafJwG70cN9Zeh2Fd6R7N0Hoq3HEtSRHFlkxlolgDut8pnocvZmuYpXG4OLNoKh6fVgkYMcuzGPHmZC+ylGOVfAhWDC56WoKdSonOoPzQipduDzyU5EE69s3s6zMOUQVtQe4V4mLYFwLo8Zyx+0dhH0U+cpE+THP6SMxa6JRzijrPbOB9N6bsz1FP93O8U7xj07t89jJLs1BJC0ETztFXpnM/DR4uJXxj05mTU4lycH5FIXlL1z+mGRp7D0vypKZnK2zYYZYvv9L59yn6mcVh50OmTCjrZc+3vbWY/LisDPyY8JOBif0xRCXgD3h0g6mrN5Wm3SpzCeuuofUN4Et0EIxnIsJUbKPy2mg7AC7iX2+9YEQw1Mx39aM0eAcd1p0asCxrW7A1/QpKwzOLqgCApSZgQK2sn7KN5wmuHDVu+PQEwzGoACOUINfYTJxCQY2lRDLFgmP49ZbElzum7VWWK3dAV27w0LkC9H+Som95t3uzr++o7FHfK8Q8o6CGIWbMCnV+2GHoMxG9M3KaizPjvkGzN00UT5w7dw931fBI389JGLxB1Oj7MpjS65GgKB8ozGpFcivBxe1WZ85jqhp+IA4nGci5/3PVGcBepIyH/f4in8Ho6A7MeK2KTSbL6L+EPvrZJJTuPmxLiOlWFgWUY7bixEu+vMRSW2JWE+UDnJg3AvTH5w==
    REDIS_PASSWORD: AgCZce0AMRNv732HNk/bN8Ks4txF5IQ0my/YA1zohEcJ5oHFfxW3lpxJMI/Q0VqIZMoRquirD/tFj4Ihjc+S+KYKPG330FfojaJHh2h2sdPH1u2cQ5SjBDwHBCs6MEiAd3eapoAFTlwg5OECyK/FSOiu4XBzcw6mI1XNPX12+lJgzHSnRmxRYUCSCkMHmDEgCo8JIX37k8XxhR0lMzpowel8hb6750NE+/9aS+HStXlwEMD8tvxfE5eaTDpSGkdXF2TLuYbswNpPPUr5aGwEBmOxd5u82sG6RIcbQE5AFd4UwjOv3CaXGaEAiF6p/JU4MDSE1Q/CD1CrpQcKo9fdVRk2zAltgFi+02MsAov1eZXU6QCDI2aJT0WRos8+Be30CRQsYUpHq5aA/VqPTYW2S76bLGgymvcDxmwnNd86gqUbG//q4NDbedN5r3dL8L4TsDBprAQUo9ICT9mgBKUEQHs1CtmFvlUyc+YkW4+TvG2HukYnB+C3fNZs27ZhbdHQp9gvQhM9UHvsXT2C5tE2sS91QlpSqfrG4wyAgKXPWx0KK6gMkP5FMUvSbv8BZp/OwKrpG9QlFiRxqzUwHzAUQSL9Hg61u+EKZFGLxBKhc2AddWMI+h0qm1QAGt2QxcUzZmojFuuv+cROOy85M0B7F/T0RmXAC30jh8m38YFnJebgDSmjzEyq9/iyyC4pTUiNYQHbGI0GJ/5G3wIXWWQVVQ6mNHAjPA==
  template:
    metadata:
      name: immich-credentials
      namespace: mgd-multimedia
    type: Opaque
