apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: loki
  annotations:
    gethomepage.dev/href: "https://loki.trusted.nirmalhk7.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Devbench
    gethomepage.dev/icon: loki
    gethomepage.dev/app: loki # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Loki
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=loki"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`loki.trusted.nirmalhk7.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000