apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - secrets.yaml
  - wings-configmap.yaml
  - panel-pvc.yaml
  - pvc.yaml
  - panel-deployment.yaml
  - panel-service.yaml
  - wings-deployment.yaml

labels:
  - pairs:
      milano.app: pterodactyl