apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pterodactyl-wings
  labels:
    app: pterodactyl-wings
spec:
  selector:
    matchLabels:
      app: pterodactyl-wings
  template:
    metadata:
      labels:
        app: pterodactyl-wings
    spec:
      hostNetwork: true
      containers:
      - name: wings
        image: ghcr.io/pterodactyl/wings:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          hostPort: 8080
        env:
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: wings-config
          mountPath: /etc/pterodactyl
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: game-data
          mountPath: /var/lib/pterodactyl
      volumes:
      - name: wings-config
        configMap:
          name: wings-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: game-data
        persistentVolumeClaim:
          claimName: game-server-data-pvc