apiVersion: v1
kind: ConfigMap
metadata:
  name: wings-config
data:
  config.yml: |
    panel:
      location: https://your-panel-domain.com
      token: your-panel-generated-token
    system:
      data: /var/lib/pterodactyl
      sftp:
        bind_port: 2022
    api:
      host: 0.0.0.0
      port: 8080
      ssl:
        enabled: false