apiVersion: v1
kind: Service
metadata:
  name: langfuse-clickhouse
  namespace: mgd-llm
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: langfuse
    milano.app: langfuse
spec:
  selector:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: langfuse
  ports:
    - name: http
      port: 8123
      targetPort: http
    - name: tcp
      port: 9000
      targetPort: tcp
