---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-config
  namespace: mgd-llm
spec:
  encryptedData:
    default-password.xml: AgAuzxtUY8k8Nfm58LM+JIATtTFeOCR4zI5n1txFku9KcRNlD5xZup8iw6C81Koz24V6+0elUj0/r+8sSN49cfWmXYLYoHrWTrv/AnjcM2N737mR+v9hWUMXz4D/xxDpEz7dl7ydNgLb/7Eea9KERRfbi0VIOd1gPynwZ5RtFWK8vQKqTqtWRME4d36srNG59/llieA88NmsKQfZEMLSYdiMXO/NHaoje3cL5fxkLAZLj2fpJHgIBTp3jNQiLu/RM9eEyIts9w4261gTs6hvEbwaCJksgC8lYJN7dZWbw3mLgVbmw0RZLin8LPvbSwwGc5LbNs/rBXW36lzrjyOJdsMjayB1pGZ8COsT9ESl6vfE9BIsvNRXbhAWjBFrdJwflHhoyOHzE8ZsjRNoH0xLjwRuVmz8QhaacGr+TuD4aDd/bTRrRgJ8KS94N+o8d2ifoE7H/GfblhL91x4is5pFZU44FNEXPEBtThCDR0/IU29fHeotT1+1O+NqvwmArAC90HeDP2NJlY3YkjwRwL46WQbzcq3Frh5O3hFVUKJJbIbrZybIoT4JjTId2gPP44ZkNK/fKAl2YwJ531bhRsymHmYY/WPimbxxBlzxpSFj71YyOWNgB1LT5EuA6gBiIq1GVWJ8jmYzEa8nPUhWadpmnlhyg9rimmkzJWkEk2YiqX/Y+kTk5f5ybfFSImt7KshBFcUITA3vspt4hQ61SOSqpH1ytzf2ryfB1gR2xbg/OYC8cjQHuzl/zEtQeLkaPaOwGiSNsNDNZlecfT+GpIr1Heh8nJgpweFYFV0awgZBK1IQYhqkmcXO2djMHNjh/C1Su1FFGZTs3hDmbVa7vVMP7ED7BshnpyWRygkxqYU4VkhJEMTqLxBh9tXs19I1RHGaeZVpvYoU7yoxm/DVRLWGPeLUnEuyboT3TKxOG2VZPQAnyLMeutx8FAdTQErv+yVA2gXq59jm8nF3lj+7vihthZ5VERb5To2SIRp9CBxTYPKqL61EC/w0Sn/8Fuf9vqN/Gw5f9KbvgDoNjAXZ2do5z+L0if75rRoN5m9B/R5y1kUTjWTld1oDwfDKcGGLrKLG8Mw35nvJ//mysoSwu6AEMfUz0NQLNWEjPwxEJOpBEYv9sUBi
  template:
    metadata:
      name: langfuse-clickhouse-config
      namespace: mgd-llm
    type: Opaque
