---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-auth
  namespace: mgd-llm
spec:
  encryptedData:
    CLICKHOUSE_PASSWORD: AgA5DRWbSmV+eaEJSHUOQa7xz2Jlrlx14xFfk720s8pHx4eoww3M6/sE33QmMQ7kZaduoVXUfL5p4vvfgc1n9ErSj5hMS8nPcNqu0row/x2noiQ0A8SZOMMOVCvVVWIiE37LW5vRExFoMlz042yY5I+S+HL4XUQ09KafHc/WzpVpMb7IDECZWIJ0mWqp7JJy0cPe05UWOIg3swEY6fCAGLTiyBkn07Dg5JO+yE2+gbJ0eFcLO9goWMM2wxUy90p8cAhoV8KYR9KhKIiCaQO6V/y4Es6a5mbpE/39MyvQ26kE9zfkYa35EqcXCKjXJVpmyxlW7uWQTBykh1+zmYvNgHNvycupL/FS8nFBrdeO/i/tKRhTeNqYHZJG691RB+pnZDTssx1e8c2PHmbhTgEhH1YfcnbpJfotqws+XrbjSPmQVT0Jg+BYJ6VrgxK5sAnPdiWqJxWZ9Px9q2fEs3v7bSnkdSxCjrgEU0FMCejWR/42jSsp68alf4hgiQDcMAQjuGJEtR317IdUK8rVKAyV0OV8OI6laAGyGB7vNoVRf8t3oQtkrgi6J/7Bn6GzXuPr8uT4RQ9Jgr52u+iHDVNuS/ztsfaL5kCy9mNOE/SXyQvkqurokYg60+x3Ih9PgbzMEP8XHYyRTi8Qgd/b8mVdVSIZkB8S/W7lmLVlerEsnY2RFYk0Foe17rlQQUQQsoZLXPDJ1106gk+sS9dkV6BiR+fJNWW83Itrc9g7bmO/+sv+6g==
  template:
    metadata:
      name: langfuse-clickhouse-auth
      namespace: mgd-llm
    type: Opaque
