---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-auth
  namespace: mgd-llm
spec:
  encryptedData:
    CLICKHOUSE_PASSWORD: AgBG2omXyY7jmE3VcJbQbI8OECvicwqR0JIzXxduuGbzZ16hnNYe3kqigUxH6jhcfdBxffRWtc3uHh5CXEqJyGKefsESW1BqtiTWrAYx8DHvPdojiG0WToM3zjDLWdItdaqkdAEbjnkuxnV0jL01WxeJmyfcJkR/rXdkrJDKd0lU0C1KpOwkqC+AxnNtzAD/Qn4BrQ0eOQGfXnPIP7wRjM4nDw840WXfDpMwNiMrdocPIevq2d82nelVVlnhZyhhr56rDFyqlsDGTHqDHCzbSCTNS+S9GUKWW3FP0fexDH5u7vKZRwYBnCxwhNlszCwr8bAxb8d7/ixgZ4Mt7zjAgfa48AncdydyY5pdtA9uUaeGfKU5dU8nhdCZVVRucoGFmu4PMP1+g7pwx5bd6xY9nddYEQ1SLfnjYmYRmwTcYusqM183ekVbrWBTL4UXQJ8yplJnzsPoUNiDez+Oc/8W/SiqhVmD+FHnk04nsosGBZ5/wCpUi2cckqJDrKEF17YEYMkMTK7z1Wv/ly6HkMYAbaiy0vn0D3qrx8uu8QFXKqVHBHzm/4KtvsK997pFmzRn0z5MR29djPJauCfx7oDqkxCeRPX/fVPenBRZj3QjvR8COvS4PvmhzE64TVUHyiTdZuAcr0o/fX2lMSY9clTqbmgsNkG+se27nm4Liv5NEYYOelMXWjbXrFilqy3EV3SzXoaFnyfz9N42vecyhMB3eNmlOQUepH4eMjW6H+t8HT1r2vLLe55vI/pV
  template:
    metadata:
      name: langfuse-clickhouse-auth
      namespace: mgd-llm
    type: Opaque
