---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-clickhouse-config
  namespace: mgd-llm
spec:
  encryptedData:
    default-password.xml: AgAJG+4Iqw1Zyu0sS0Ww+7gzcOxYsr1SgbHOiP+KNR9oNzZvx8hHQo7r6dt3dqEEW8ryFuWfalvJCUlSZSThsvZo0BThK59A30pI+OxnH71g/cHqmWtOBfEnBbT4CfqEWTh3qEJ9c1OSTH5pXgZ4vT7eLLLB+BXYNu+5ogWQA5KguO21qcDY1jdjNItHww3SDk+JMgB3YB8e/5jz9HEuLhLkZ8JLl5fam4rsnfNFSjXQyd9Vb0eKuzpABj3Rs761cdxx8siUGxFyA2F+iJ5ScSApA30NTqeRx53QuqnmYZgoMiRGinHSYz49rcdc22Fn9Hvm6lObvDbo4n9Y274gArqBGAWKRNImSodAR/EB2DQrzxUiKTyn7d73yuze5536EhLYOzhrJCHuXJpmz8cd24zDiNA24oGIXUAoJnnMWA9Fs6dpf6XJqM7IfrdMD505xspnQ+GO/wtTIxutx9WIlyPyejQ/QIJfpdwKJL8U6gxx2AsQTDgQVpV4jqDl7eo5D918rCk3WEY5E+809VPsIf/hx3fGPXjmBR+q6l05C8pwERblWjAv+sUR2fDYrQIE3cE4I78fZgTFo7ZmcOs5OZf8NtivtIOyTksYahVjiyyAcvVujwiIEZ681e4TbadvhwD8Kfv880QiYgKzjX4cRVmLWWPkYg/TtS3NgFqaS6NInUE7DQu4Gh9RCraeFR4rl7v2cdQH7Kg5YB5A/zPiR2qDLuxx+6aOxURb0h0L78Vjzs0XWK1Hv9LQ1kWDTg1HHu5dHs5d68wPy/3weA0AusjB9CBh6WEMpnhNkKkLXiWc3TnMx+ScYyeo6XqdA0xzR47k4yH9w/QLaHbBK1al0FSNk0M4Jl+pwikSiA+6iNObc/aTYJxDcIDvIRCuy6GsV4m2TvJkJIh+UJXRtFnQprKlitciMCx9hkli6dzUGS5cQQp19LbtwmlSOBKug7bcgZPxoNWj/SHHcW1MrSbi9PtZVkeLrXdTI7f55vRhB6ojEO8Ve1DJGloBtsIYml6rNyGQdcPj1C9KSK6zXYcso4IPFHK7CpbYLS9+jsJ89/wxql3GUv24A4BEkFGr+NDYkKrLHVgDdMxFTfXQzBfT1OG7hdxFZYnPwMDH8C4AX8O/LnHs
  template:
    metadata:
      name: langfuse-clickhouse-config
      namespace: mgd-llm
    type: Opaque
