apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-clickhouse-data
  namespace: mgd-llm
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: langfuse
    milano.app: langfuse
    milano.level: managed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
