---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-db-credentials
  namespace: mgd-llm
spec:
  encryptedData:
    POSTGRES_ADMIN_PASSWORD: AgCCvsNEqc8bK8oal5ASjO3gXmvwz8tDUES8lFo6tw9/gZNIHjIbJt6Ez4NMIOFqu+3KhCctansdxGZ6kiz6UfmNbqn40RAUyNUyCLOLo28SvI1admnCiuyWZsF9myRWCnWQdhQSo8YnJik+ZWQYAr1K3yIQP7jiGLiSzHaRRLLV1mFApXk0+Gki66IaY9Hwx5mrazZWtwJWDLZWJ6dV99d9BO1uL3aPeZ18tCE6W/jjxTVNobinyLSpZlGcI+kxMR9n/i8wCkSUEm5DOrIv3ElqxQu1ZCn5xBPCboOleOcyafHEtQtxswAaADNxV4daX8c9RQo2PvNLR43KGvsOYSR/yuqkgtq4+i4GZDlVdASjSM5u1s9fvUidJj80+hJYeLDqhwci61FCzCYTSWIg/ufPI2h0ZLDKppeazR1jHegUn3WP4KL8BPwSpNXOsW4v2s9h1H66rqhvSMFwhbHkOIngf7Vi8DVtaD4ccPU9cvhsd+BOvE4uiosKx7ovnxrCM2YgqF/gFwTFXTBn56Ersn5j2bpp5FYMC8LAk9mIsxhmN30eL6wWEVvqqGMhzhgok1+hOyv+qqLZbIC4nm1KW6XwDjHok7HAWbcR1cH7035Msye/82FN9lqfB8EUhOT6hrdnTjmukF97ZagqOWWMlxJCc3jyqpO7BiTJyhKH07FEokufPKB9SLUArkgIRpa3PbWbrOhaWgZ3Rmfzg//Yj8Lbykpgg0Y8J/UKZANdRZj4ES3Ay1pfhG+N
    POSTGRES_PASSWORD: AgAzBiTkJqzZm2mx9r8w7YHO8rvrzPMlCy5tOUmn7S9g6gyBPO3m9NaDgOZyamTwYJtEqO+OgC3fiQGaouDhQ5p1ETq1a5DzynaQU8sRSI9tnu96nBawa2OQuHPx+w15kTGk9xamf0GBgXShbXrBfcLxLQ+RohngN4qSBSP5kEWzi3rW9yGHYlipDbRMky6/Kw6BNqHxyTQO9r+9UADg6+zEMPFQTFvIFplW36M4ngw+eSm4+TRA2JTZctpT3nCpJXoQlqh4lMdlH7DdiMTqHTQ7+j4vauptR0FsYmIPKk0wv4/GcPEONx+47r7kPRSG3brcEHBR6v52ejOw40p5axZ+/QPUiNOHpUpUHEI0jwCFxrcc18vofYdU+iV4g4e52lDYMw1aS/P/VhTekutj2ezbBDaRF7UTwn0xui8WDZVe74aT503lH9yulM+L7W5FY/ZWNcLw0Th6viL5qG+A+zwSqbpy3ewoCwmZSsSP4E3qfoEMznwJCpnOse/WGCIbH2/sNM3hs1m0ijPMAj1/2SqVY5R8itFs5H/zhqRZG8ZRlw5BTUkemVgrWiHw/hiNWqmu2Op+LRSyBYIMxHIJqRPBCsXUh5RZvjPytksXYTxBl1tX6x91DyF5XJ9SnhHXjzrA3neH0gqUdJAn7YE0O2TFDdZVs/vgRy+prusr1pogP63uPAOJCKNa0MfwJ3XwrpppHmMptc7ipYBZtVpKWI76ndrX7vn/z1yyfiy2vzFK3kDDBbU1V/2x
  template:
    metadata:
      name: langfuse-db-credentials
      namespace: mgd-llm
    type: Opaque
