apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - subchart-secrets.yaml
  - clickhouse-config.yaml
  - clickhouse-service.yaml
  - clickhouse-deployment.yaml
  - clickhouse-pvc.yaml
  - helmrelease.yaml
  - ingressroute.yaml

labels:
  - pairs:
      milano.app: langfuse
