apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langfuse-s3-data
  namespace: mgd-llm
  labels:
    app.kubernetes.io/name: s3
    app.kubernetes.io/instance: langfuse-app
    milano.app: langfuse
    milano.level: managed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-path
