apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-multimedia

resources:
  - helmchart.yaml
  - ingressroute.yaml
  - pvc.yaml
  - secret.yaml
  - certificate.yaml

labels:
  - pairs:
      milano.app: immich
      milano.level: managed