apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: docs
spec:
  chart: docmost
  repo: https://thelande.github.io/charts/
  targetNamespace: mgd-default
  valuesContent: |-
    docmost:
      appUrl: docs.trusted.nirmalhk7.com
    podLabels: 
      milano.app: docs
    redis:
      url: docs-redis.mgd-default.svc.cluster.local:6379
    persistence:
      enabled: true
      storageClassName: "milano-v2"
      resources:
        requests:
          storage: "5Gi"