apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - helmchart.yaml
  - ingressroute.yaml
  - redis_deploy.yaml
  - redis_svc.yaml

labels:
  - pairs:
      milano.app: docs