---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgBZoiWUhyJiGcqVF53lcMKbCXqzqtRTOWOkITN1UVDMTL8bAyxuKwKZvEH2jr6UHyS5L2UuanvyPd1ZEDnMviZyV7aPgot+kBglZcqR6NCo/5Qio+H7KcNIU+BvKNSoyAGw9tThCTfTakw43e6RibObuC8OvBMz80r261qNAqqDeG4YGALN0UlnR246eMUJxpKqxlTnobu5Ce683IJCbSjTvM9LXTR0io34e+W29IPDq1uDqPBu3FOm2KyiaDuEqw7ljvLQ2844oaHFA5stTguVwTF91zeKa1EERZbMeeSDC3EEuZWXr3BgECv/UcolDYIuT5077SMwjjqVYXI3sQiVN+mVowPMGkipKD6GzA9IJ12UaNIPbUBLhKDupy4H6dK1K6T48ltjLEy+i0kbRrc63XRCtO7zLXZ/xLnPDZZ6swnIVxx/KuhfUOMhZ8STQ2QXncU9yOKZWJe9Q2LfitxOpSQUMRwo78H9qSi6tIOLN7BzkYT5JjUgRcdI4WDzNa0BLNH9MFfIkTv1PRe8cXIJcCbLA9LLQ/BymUC2seyA5iyrdUYc0diD961iUcsxiX1gxk7mHUDWbUXTokkkm2y3kn+aP3TdaZg3dtLGz1aG3+XLmcVMfyWoigpA/mpb0MiyHcnwyyKVHV5Tkkz8Oz/7v0U9S/e/eWsssj83RXCze1Z2QFfakzku7hflL4FK+ZlzJBlQRzHakGRIy1boU7KeVYP/mhNgE9oIRbyyBWKAWnA4lLWvd6Zs3W79IjZIrj0=
  template:
    metadata:
      name: discord-webhook
      namespace: flux-system
