---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgCX6wBp7i8f0giXmxu2VUbHbMBX+kuSOOWatvuM6Xaf7G0Pz5ccsZajr77zJdwvhvQm5ObUZxhNPtPS2La93wrzFJBQ0/0odAz2r6K/d5cp07dqiaEEpXTWi7fzZq7yIfUp9bACLsG7OfTgsIs6v9siyoQsEs+DFfpSc7o3tOkqRFK5BXUym0Y1t44EiMTU4/QPqklOG+R9ybffTOT6+MWvJLj0kTQ+w0NJarq4kcxEVGRa1F67VIl/laW1Cyl1zyAKjxlcx3fi1aJx/GbuPU0C5CByFwsACAMEWNfMPj3iyX75sib4AS8VH4JHSwdqKLhHzQmNC2feLBjM3Y/E/HPQQwHO/zT+yMEkEXKaTkRUjaxmjX1GCI/bSsH/e2aSTdFtrGV+JkRpHWjv4Qmm3ziYcQzAULELaEH/OsDtD0vF3KZGPwSFWd4rtWE+37XoZRjQHgMuBHUoB39+Yj5JpXBuxj0vudrW4MVYBxTrcHqxZBlXPb/XSt7bZRTes1Km5x6p+XWfHr7WSPwL56J3fe71lJIsCNSK/H4kVJjlmRi3hv0lYR3sr1eopVfQalTZAnWRlBDC6i0+xTvO0IJuZqMSs9Wc5wre+kELPtkfWs6k3diucF4PJPihNuBjGxX5BD1zgJ3H88tFveJWTRF22VUDC6rBa0mmyl+H3Tel7KrF9F8nBwddjtxiRc1dxYmy+gY5Bo/BCvtrBiSyq8HWoZucetnW968ncALvb6vXpt0hvdkkFEAcyhTcWjnE6Uxxht8jIBXSiiPvXXKAOTabs2BNfiVw+XV3eYhXlokrbPgfvbpwHis2/gFuTuiDjXvVjOi00lOeYCDE/rMYyxbs/U0vixJud6zYiqE9
  template:
    metadata:
      name: discord-webhook
      namespace: flux-system
