---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: flux-system
spec:
  encryptedData:
    address: AgABbXKszah3VAo7cFFE6v5xvEIKkHNRCx+WQqHhO09fDnoYI9qtgshjLpaOl+vxC3kJDuyES2pI4v5jBlpzYlS2PKn6qNVEPG0Ki2IA3X4Snm5Akk9wUX3JJdxZhRQ6NIFYy55PL39IX4XKIQTcksl9Z11dvynPlOP+eOMSNvg7PPHTFu6abYeiFg80MbGG+Uxrx1Lb0eyUjTem/4sdLU1LHSuMHMOr74bAl+TI+8QXX2K95PGCdS4CbueHYY+fcAvUtvHKt/geV2OeTU7X9FEvd4Hgfypd/4BjN4sRvFx9Me+3KPC2pFtwRmLwalPfdmrXAucQIuNXGpoc3M3LCbaOqMAJYiThYXlATDlew1ztrJjcY9u/ye7mulrlELYafdP60VmyDbEGdm/e/i4Z8k5qqBAxsszziZk6Z1zUEHee4Mp+QqruDvKtO5KTqi7x9qyHlVMS1wchkmr0f9ILzbQCnxs7j5fzVdEbEF8RkM24Rx9hRRfdoc5UEY/p7URNanlNUM4MBe44b5DYXdHFmmwtqmx3XC2sdIyKFeGxCD9zvUl5/5kTCDvM5fuID29+zt1owqvxf4HAf1GpG6RTPsclff6jn7/Y/m9kUWg4pfUiLLT2XTWRWqgN3xuAmPHNXTQVlBqlMyUrESB5DB0MedUG/9bJHjBnm94D1Ylz6jiOB75ZiZkxtS1S5MEOMtGTSG1k7DqgTu3BH6w9Dtgg652x59UMF0gn12kDL0RLkV2j74nMUwuIbcKTUdMtc7XtWB0=
  template:
    metadata:
      name: discord-webhook
      namespace: flux-system
