apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app pterodactyl
  namespace: mgd-multimedia
  labels:
    milano.app: *app
spec:
  replicas: 1
  selector:
    matchLabels:
      milano.app: *app
  template:
    metadata:
      labels:
        milano.app: *app
    spec:
      containers:
        - name: *app
          image: ghcr.io/pterodactyl/panel:latest
          ports:
            - containerPort: 80
              name: web
          envFrom:
            - secretRef:
                name: pterodactyl-credentials
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_ENVIRONMENT_ONLY
              value: "false"
            - name: CACHE_DRIVER
              value: "redis"
            - name: SESSION_DRIVER
              value: "redis"
            - name: QUEUE_CONNECTION
              value: "redis"
            - name: REDIS_HOST
              value: "pterodactyl-redis"
            - name: DB_HOST
              value: "pterodactyl-db"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: *app
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pterodactyl-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pterodactyl-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /app/var/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pterodactyl-data
