apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &app pterodactyl-data
  namespace: mgd-multimedia
  labels:
    milano.app: *app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: milano-v3
  resources:
    requests:
      storage: 5Gi
