---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCu9L3TQrpeh9Q6mbeKTdERgHz2BVyF7rkkclNEq+7fEm8A5rrjeKcZtyk9yvF8qs05+RzZ5HOVNf+qfKi2uYXTqEaBPEaA5UtithMYrwjYJB87x9YZJSEunnKAedf95SsNMAux3+FP00DB2rjUYwKlXx2a+8D4jN37a53whCJ3r10Ya7AFs6RynHRIUCPLuL1x/Hsox0UbdMA7UHjw5utTtcPFzqB3HLHbHPDx8mOGPy+uM1Lx0GMukp4/RoUJ/BgEFneE+YeE7wV94quov20SE5WttdR/H/N0a9u5XqX2Wkvf+AKpAduRxbrsebhsQzM+hqDVSYMfyOeuuZuszoDT4ylSb3QtOXDQ6wFe+QbwIaZm98ykAC3L6CiP5S5Cb2CrQdXyIpa5uYFoShLrIFUEl419J8Os2CL3C1N9Aleu2+5uwj3RQ5mIsC3b6heHckEK59vguC6uFCIMfvNRS7hZ29yBtJoNl/VVnF8Lc/XncQ5wiK81niTTtzB73I4TnhvPsgKR3NLsmPU3pZ1DbvHTDaMMuA4gekcLH44K7k6URGVSTH5COLjTB8jSdcoQHbJ2IjvIZy3zQbHsmJq2MhHxuHC4lIl3hhKaf+CIpV8ajwOqthfdbRFgGfvOurr/1sSIseNXJMTZvt6SyzxlTdcWL55s2Bxt4ybWw8Yhiu0FobnJt36e+Q3r75axf1dAIk8ZOJYOR5ShzbefjYdBdoK3PcMClpLjaam5WAMbX/8YKY3nKTPoAI8gXd+gnbmC
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
