---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAhjH0Kr2Q1BM3lBjgpfVxBQViMVEp0r3pf6/CQ4VAaJS7oGqv2i9LW7sMDiJ0PGYzGi5G3lDIJ+/XYhcPh4OU2ExpKFOGvvol7dYHLXJUiCR/MiJJ/zvfGI4Ru+53SI/4GqlB1Hsh0LtnjxqY34FHHzMIrtq2HKTvzvP1sjhmXMh2FZi6wAgO6O3IuD0QdJ7QiyZ2+2pBqSnEG+F7NqdPujSazTWwzN3Wzv8dOn/1fA8Ik8eMnRdEGJYjRGDbDAT6UPQfYcOhp827LcxoGhO7fuCnwa37Qj6sU6bEj85OcBMBfBc8XXAB9UQ4fvc+2vD8MsWYRdA7lUKmeOt4sHD86+IMS96qfWjJc5BtacgiqrKTcEQzWa14YFdV3pAiOqACXa7nhE2j5aKnGevSaLJQ4wco/SawmMOoeLQBnt3/uClD2UjGsct0mJJuK59a4AMwDM4O47hg69UmPbVgMQXXtHwHrWGwW2sTUkeMkZC/jLUzD62goKfWvqHgUr1hqfEBBUsZrI7TU/7fEmCCf4S6vMgMXUMTpvXlznH6E3hdtT2CpgoZhY5KveJPLRXokXSBYkuzxaZOe+/wfreEqVUNrzA+rtcYKSLr0XBIF7FnojJC0F87CRKo26Wup/V1ed1TaLOwDdRSLwJUmYX04hbAR/KJw5JvkOjn5TXAoh9Z+6Cdmj05lk+uz3wf2c7jmfQlrPuob+iOrDTOgu/OYzOkAW2DRJszthbKPApNl+17MUEK+g80jUJgmrigC5atF
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
