---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAA38oB8da29zjeOHuSFISy2pfTJVyig57HYYXpQc5k1uehgyD3HdHKtgfmV/69gDuy+xMg4BT94Xt3GAFyaiLKo1UTQwqUtJ3p7UOhkUbf0B+Xz1Y/rxvMlNx6X1v0D6ni5RBXeS6kV6q5M46te7O10tvIps4W54elQ/sww7TAqlbVbt+LiKNK1rYWhQQne84tDtcoxapmOb6uPas0msVS7ZRkbje+4YLskr3B1TUlNVdM/pr+42sB3vUVNX6n5kBN78whuHo/rqhLu5z74Hq8xM5gxDecbHYOKoe76OSm6CrfGeJdpyyZjyMpc4y85TuhdnMMHGsK6Wj697n1xX9gJkNdCdRF5fo890fE2m/sd7UVJtwjT8V8raL6l/gxqn68PUFAn1zK/I4ikH2LPNv9A72S/KUgKsmnWWY1S6kgQ0CZFjCxaG11ju/0BIMU54xvwLnX5exPOww4Ou7gNMLgbb7v/5f4GmFKfQcYz7aLdF8CJyZQuhfSdv45mgnzC1RAtRIowhW9zD+nfnX3v7pHZwtUPEaA8pjfpDTDm3sLhkOZJ5tKXbj29tigiQ28caJE15+ual4BRkt+70WctzhZKu7+gMZ+vg1sEJWk6xb0ZUOKA++Uvoa5fSPFxPTzFAq98ZSLkDs/+ySlaqQVoKhbse8NuDj+ne0uRC0hskgZmTwzwBK8zAkGy6cUi4Mu2Czi+heVoHRhDZuXTx2pQoySHCSCt1btqjm72wrGxsDe1KxAyEsGPkP9imQXat8D
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
