---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBiwBLFCuFiRCZLjwk/diCPhzALSdBVx8mItpYAya3OO3fCKLqJ91GheCcPHkY5PR1sneWLt/qV4PxXdH4HqZ8tAn/5hWKLnspB/WneXUNbf2cLv8T0opwrghiUI2MJZd5h4L5pqJsrghzhqw2U5toFWKelwAgMVDiTDWErhAr+xhmZigyvnVByVwUghvFNCQUaFsGEicENtXZvfwfwCwwMGY3d1qAO6N6Ks+oPVCZAGUAf0bNIY0Es58k6c/63sYZTNkwnR6dbesREmBFECPNjJHWQECv4WHa3dwBSyAcm3cVZsrHARmTh3xxBFKj0Ykq1UhGHsMHR5+T2QDV6r8HpqeWFtY0FgQzmFGh5Cc8c5YJMASv3cf8/li5gwFAqbaw/FvhOU5WB6HOwfsu6dBzXopfI16gY3T9JklyugaAfF/MePCus9iv7n7GZOuTDlf60y5+lCAFz6ljf+IKNZEGHlVdsHmTS7IFv+AMsFupLNLf1Pxlle9ceb9pFK0TcwyI4nrGJ23EP+lHtuqj9cYY2fNUbBNITToWDRPwy6tXPrsERSSepdCpLp/YTC53oD6Y0W9aInALvBvanM5u0eBb0wKw/TiKrqM04pOX670s+YyMukv7sCf3sR00oGDOG5niwfc88fDaOfhY48py1yScnxvpHZRWvn8i8Qwu9cr5cwQWknncrWh3y5dixtPP6e4RZCa3z0bELqTcxJxmZP3Sb3OqVMdU9NY8jRfIEWTXKpw3rRXqomsNnEyvXw0VI
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
