---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgDHTum3Q/moxPHKDLWviEPtQQYvCsSOHcM8zixv2dxnZpyAzBV2lsywMsaiqCd3M/3nEE986xRGnPGCTGbxrX4koqEkSEKmWAXI2wCc8XP/3Mj0nim5S4UJ9Shp7iDvp0Bn8hxSMuaU9bWis9j2iudoTOmlV+Ehe6NS/jugPMO6exuZfRhKJyOAYC1TYI5w0DSESITV7WJFgCIlLuGc86E5aRNNuhvU2knrlimlXVFwPgRCeyB2Wcmfn5ZoidNxW4/0K+Ajx0U2LwNRxBjK+YJmsfPdDNgSCOeiNfkKZaYGPoLvP2tloWMlCjfjk3bs19jtqCrTZ8Sgm97afW41UYYwl0Q+Xiz7e9p5PNO9Gqr804hxnd+r/quGWPHJ411/47m6VM1d6yZPjB+H+ZyTXRV9/g/f1ldJzDENaYNpKJdGikWdt09xZVmvH9jo5Pv6GMGcdLbNHLc6w9ofSAQhMwRs5qLz9SxxsX9FsInlurluiPgXG6Xl6cUwaZqBc2WbJtou7udG8oHKVqPis99G5iKeHxIwYwaBxXw7jFQAmTsJZiWC5hLgE90gtiueOSM5n/0PEjyKxvnNFh+BHuAh9Dujln+eL29jyRO+K1sA1WhwlmG7t72CFrY5fx0tTrve+MghNN2rMjNIcsl3wYEBx2Ab0QXdP2kXKfXj59Hqc7SWqUmzHL+UuECVYvf1/5cF7DSmRIoaY/xcnSCzYLQTTUokSnT7LujvyVlSPaKkP6gvVbqnaTz2GF29jgKRXBaN
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
