---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCxZT7n9Jrofj++y7xE2AKtkOOFaT2rcZ2/snWK1oU3wxSyD08nrfOP3kkjBlhneuT3VFiag1nNCpWaRx4jC+euaxR9Gyv7qOFlvxL/y3kKE3c0NCZFRRNMJxL+jkrekOjkpjY9J2c4aVHvQEufZhmyS2hrsplcpPgCue1FAaZG04V89aCqz/iKIK5O80cYk2xqiT84LwnS+eiZzFT+IyEma2X31rkqg1AHt4LVaG605/2qiHBBq8BMb2ukRAdtek/YCIUsoziaThDOUA3Xd8rtGgq2YXT0T3om48kyI9+3iRPrfsQLNF4x1wf+84WObdQbVP3aBo/SJ6NevxooKSc5OQEy0VBsM7jUkSedxLZemVMzcVxyc1xDlvwpCzb2N/IXnrZCrrMVQwfzqc+eGYrLxdGG1wzOAQHGCFveU3CFqGPKXZqx51yONt0ak13mMVsyYLdw+N7cKm2iPF0wRH3A1oGvPeaJeX+Kaihbxg13yqP29XW6CMuuqpnBQS024+JznfHTOlV0qzY1p8Q+xBjnSxUO2P7Bt9/Zhes2q2JfE+XFge5xEImthU04IgDxVUdaztXuHTHfQHIGj9/2W3AtXDbsaeAQK7WAgdnIky4izHvK7zhIc7spgU69LuA0EkxfdlREFQ/BMEJcrXjhF6kLyoi6HM2DB261G7ATBlxkwVfrg1xXbAB87YSkem+BBLxoPpvpP0EYsHwkG/fCmSDscXCy97Y4A/EH6eakQO1mXxDVYBhjKD5CvJ9ezr45
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
