---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCWkSNUnThfFwZhV/PUibOpUpkELFZlfNzETZg9FNtgcycUIK5FVxuqgKBlJRIOb4i5ruA21pJcLqdkUa4sVTaHyipNxvI7Iux0KSXiZP4tH0/q2gYjMQ1mELsTeRp4Ip/3G9rRhm7X7fNbRfJjXvCdDz0LG2DaDbV6rRxUNhNAbjRWKSbit/mUu9kWgRktqZKyx0x2D+GRFyLQtmOme7YKGGF8+tSWeOFiNlKY3njPXWusBf06oflQ1W6qcIRbNC+h/M0hGPkoi8d26eVIboOaX367Vnb/alcCJweo478tJ9BXYrbW9sdneOVB6ijaID9et6XBjgOlGjeN8ckyqidx5ynI/oPZHN8sETxPopOachU+Ym1NpQB1mhb08Dy3Gtc08s+E9smUl4HiPMXMi3Ttckf2xT08Mu/SpfzW4IiG7KgLY/4yRgcOtiJYSJvvsvbK0IzCrSg/ynpzKl7WWVq/AHzx7HnkFpVoEFeDHdAFAMtSuahYBT74MIOJ+veEy08vy4To/SshuT/kMngLRk0QHRSjh32cgJTxu6jGDebo/GPGawOogbWBO86Wq0vMQEHMKMy90dcuIVKmsycjRLaMHL/DdUzqq77XPpZdiNZ50G6uFlmEMPazBg5HeESJmaWsUu3zWX7EIzqkZRkLzAlbHiH18Ibqga5qHUUNFhxFau1hxxQbx2Gftqwp2/VaJav708Bx/x19HGwIKI1HFlnLL7rkyPKlTRr/G4ln/LA2WyUI2S8QzTVdbPOwDWCN
  template:
    metadata:
      creationTimestamp: null
      name: telegram-token
      namespace: flux-system
