---
host_ip: "10.0.0.10"
wifi_iface: "wlp4s0"
wifi_ssid: "WiFi-Error"
wifi_gateway: "10.0.0.1"
int_subnet: "172.16.0.0/24"
nginx_ip: "172.16.0.101"
k8s_ip: "172.16.0.105"
nfs_ip: "172.16.0.107"
vpn_ip: "100.87.0.43"
wan_iface: "wlp4s0"
lan_iface: "wmnet"
vpn_iface: "tailscale0"
k8s_api_endpoint: "https://172.16.0.105:6443"
