apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-cross-namespace.yaml
  - allow-dns-egress.yaml
  - allow-traefik-ingress.yaml
  - allow-external-egress.yaml
