apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ingressroute.yaml
  - service.yaml
  - servicemonitor.yaml

labels:
  - pairs:
      milano.app: traefik
      milano.level: managed