apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-config
  namespace: mgd-multimedia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: milano-v2
