apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
spec:
  interval: 1h
  releaseName: vikunja
  chart:
    spec:
      chart: vikunja
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: kolaente
  values:
    vikunja:
      configMaps:
        api-config:
          enabled: true
          data:
            config.yml: |
              typesense:
                url: "http://{{ printf \"%s-typesense\" .Release.Name }}:8108"
                apiKey: "{{ .Values.typesense.env.TYPESENSE_API_KEY }}"
              redis:
                host: "{{ printf \"%s-redis-master\" .Release.Name }}:6379"
                db: "{{ .Release.Name }}"
      env:
        VIKUNJA_API_URL: https://task.trusted.nirmalhk7.com
        VIKUNJA_DATABASE_TYPE: "mysql"
        VIKUNJA_DATABASE_USER: 
          valueFrom:
            secretKeyRef:
              name: vikunja-credentials
              key: db-username
        VIKUNJA_DATABASE_PASSWORD: 
          valueFrom:
            secretKeyRef:
              name: vikunja-credentials
              key: db-password
        VIKUNJA_DATABASE_NAME: "vikunja"
        VIKUNJA_DATABASE_HOST: "maria-mariadb-primary.mgd-db.svc.cluster.local:3306"
      persistence:
        data:
          enabled: true
          size: 5Gi
          storageClass: milano-v2
      ingress:
        main:
          enabled: false
    redis:
      enabled: true
    postgresql:
      enabled: false
    typesense:
      persistence:
        data:
          storageClass: milano-v2