apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - ingressroute.yaml
  - secret.yaml

labels:
  - pairs:
      milano.app: vikunja