---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vikunja-credentials
  namespace: mgd-default
spec:
  encryptedData:
    db-password: AgApNmecGovjz5gnvqtS6cRqbqE8TuEk1wsVVF9+D/S++9CK8UICw5Bl32sSvMZxUR4AXrk+RvQnnVGWzPbQpAeunYGRci4ML7+Vgz7tCKx67QAmE89GRPQGSj2J7KVlYeuOKtKbNnD1jB/7Df7Oc4+z0pKeoUiNqj+qnE3BlK67Ku/Hg9soTc88KryugD5iDetAjAbr9i5A+KYUVTVrmdRB/rjpbdIfyxPNSYFAadiv/b6jrcH8jPlaw0EuPKw1L+hlwgs3h+ruCifApIevTjgDm9R1yJqVmA+WisillpLzJeFM4tGsgkRX23Inmohiau+Fh/HdvCfCN08+DeFfHjSvyvuULjpIkL851WWQuOTmx5idT61kOOYPdTK0aobooQbJLwiaGiPOwcJdADEThePa3INJQmG8VFzusPa5ZdlaJZtWUn5gt216bXjwshZeUVPvzedmCIgMrEjl1y0+aXf7q8Q3VbdzUS6uh5mBoQiSghW6FDIkZ5sKUQ4StMCT7yvTWM78LdWxenrficegw1VzfMmlxKlBQdirWhvJ6ytm5pWtYW19aF8+tqVa4/ahW4WwLytaXO//yKLyBx9vPhWI2Jgolqt3B3uZNC1WWeHuuD7Qgz+vWiD7wOD4X41VBjjBrDIKAug3Mr00MqxshhWSEWU79CLbJMQmaSPNRvZnBIJBY8S+JuqqNOAAJtDn9bgCKwIRUStf+YnS8sT1YtMAxYtQ9w==
    db-username: AgAsswl2grKult5jORH+i8Youhx2C3NVO2j6Xp2L9a6eYIv83VS3Hx/hm2HWtDPh8EJGGxgMowlesHROAPeV9YfpuofoG7NtBXbgf0qcKLfRsQK1rv9P4+xZGOUQkdhxzp/nGXeOHCyEPBFmGPzQGZzdF5rQQsiDL4rNfHqgOjs9Adq4uyXe1QAyr6yoQ7eepdx0AcEE3UHtCwEjqu5QQN4SpeCTnqgXY6YdaaSw9MMyS3EVZ2ahcRKPF71O+ATGtzs5JW1Ut8gakepLTFDSlldqRZvQzj6luKoOM0CvfV2CPt3m0ULSCj4/K7gsnrMgG+wu3FwDgDxxmdQLGQ4yPn1/MJePtshMQydZqgT1AdYcBTslVe3i9eJGn4TdbW8+vaS5bisCORwXCpvpaLcD3ltdF/7FxdOdEPChTgMKzyUWJrh4jh0FNy2pq0JbiOfYal9A1J22NK5IxneJZZRXurhfQ3dixbbkiZn9ip0H/jYO10aTkbclJ2+ZLzCr8TPnfN0VUoCwGn7S4OPZuAjSY6mUeSaWHUQ+1nqL09/z16QWtfx/00TXo3y4VJeoVVmwh0+CO5AJGvFGEhjEdwie/zBIR76yadlbdV2cubtwV9+bPr1eOhtuiIveanA5DyNeU6NPnd7gxEPeWrNMLUa9GwsqzqZEh+IX4acSA6EQRT/cnUcsds3SSL2NOYx0bPepO1yPkfso7hEkCCO09g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        milano.app: vikunja
        milano.level: managed
      name: vikunja-credentials
      namespace: mgd-default
    type: Opaque
