apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: "Host(`home.trusted.nirmalhk7.com`)"
      kind: Rule
      services:
        - name: homepage
          port: 3000