apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - ingressroute.yaml
  - service.yaml
  - serviceaccount.yaml
  - secret-svc-token.yaml

labels:
  - pairs:
      milano.app: homepage