title: "Operations Center Boulder - MILANO"
description: "Welcome to Milano!"
background:
  image: /images/homepage/night.webp
  blur: sm
  opacity: 50
useEqualHeights: false
headerStyle: clean
statusStyle: dot
fullWidth: false
iconStyle: theme
disableIndexing: true
target: _blank
maxGroupColumns: 4
layout:
  Center1:
    style: column
    rows: 2
    Left1:
      style: column
      size: 3
      Networking:
        style: row
        columns: 3
      Observability:
        style: row
        columns: 3
      DevBench:
        style: row
        columns: 3
      Multimedia and Entertainment:
        style: row
        columns: 3
    Right1:
      style: column
      size: 1
      LLMs and AI:
        style: column
      Tools:
        style: column
      Bookmarks:
        style: column
