title: "Operations Center Boulder - MILANO"
description: "Welcome to Milano!"
background:
  image: /images/homepage/night.webp
  blur: sm
  opacity: 50
useEqualHeights: false
headerStyle: clean
statusStyle: dot
fullWidth: false
iconStyle: theme
disableIndexing: true
target: _blank
maxGroupColumns: 4
layout:
  Main:
    style: row
    Networking:
      style: row
      columns: 3
    Observability:
      style: row
      columns: 3
    DevBench:
      style: row
      columns: 3
    Multimedia and Entertainment:
      style: row
      columns: 3
  Right:
    style: column
    columns: 1
    LLMs and AI:
      style: column
      columns: 1
    Tools:
      style: column
      columns: 1
    Bookmarks:
      style: column
      columns: 1
    Utilities:
      style: column
      columns: 1
