- greeting:
    text_size: xl
    text: Operations Center Boulder
    font: bold
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
- resources:
    backend: resources
    expanded: true
    cpu: false
    memory: false
    network: default
