apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: mgd-llm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: milano-v2
  resources:
    requests:
      storage: 20Gi
