apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-metrics
  namespace: mgd-llm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ollama
  namespaceSelector:
    matchNames:
      - mgd-llm
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
