---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-db-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_PASSWORD: AgCpb6bpUlQv58gHAJ133kJCCeliFa/tRJ1gpVUnk6QDzAurQsX1S7nfEQ0EV4HrgSriHY2ACDLLFDuw6uyFo3fD3/5t3A1DkqNdiYNaYjWPrz0A5rcLUZluHRWWnrEqeLvALb+CvcwLDOkOlLk7pom4OhFWGynZUvZ5OcvM1oJvf7YJJtk2Kk6Ylzp0wMeSGAJexa4N24H8Jay82kw5QqJEKSHQnYmKMSuVksmiqQk7IXEjI/8OsmKGNEsUGgOjwwy5p6YechFtOiLBK7RmewWDTYDUyX0L+gy8kb8dePvtQPFRxgg08V9IlTBrS5tvxSmvC5G9DZid9UaKft936xk+HzcP5Y3hQCcTBjP2591Xu5q5JuM2eYbXwX85NnpwBe4/Y0Cr9O76j87x3R+7oxQ1Bi34fScObNVT+lFjJ3L6sqkpVhs+OgTJK6NywQl5l2DrMn6lXimHhOqatR+lNpXEBV+12ElL17/DIhTNhG6/LkzptIf0qMdVN6qYiKK75pTHH+Zlg5aLi7VOwacXPFHBvA5OrT4dhVyEdVNoZXLObKrBb1lLfRVaZRNCTsbZLyIAPC0NPTeWNVBleYf1pQW/WWB20X3MhUt3Qg/b86e+0g3rYxt2kRi7OCmCvoL+H2aGH7/u71eADKIe35JTG3pxBDL2uROCYdew5xlEpHgpeIueoylvQ0VCrTZ8YE7PGvANkc3TAyq/ibJBU0ES7FhX2t20a+6St+p/9L2xwjT2xH443wHRflrm
  template:
    metadata:
      name: outline-db-credentials
      namespace: mgd-default
    type: Opaque
