apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: outline
  annotations:
    gethomepage.dev/href: "https://outline.trusted.nirmalhk7.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Applications
    gethomepage.dev/icon: outline
    gethomepage.dev/app: outline # optional, may be needed if app.kubernetes.io/name != ingress metadata.name
    gethomepage.dev/name: Outline
    gethomepage.dev/pod-selector: "app.kubernetes.io/instance=outline"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`outline.trusted.nirmalhk7.com`)
      kind: Rule
      services:
        - name: outline
          port: 3000