apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-backup
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: milano-v3
  mountOptions:
    - nfsvers=4.1
    - hard
    - noresvport
  nfs:
    server: 172.16.0.107
    path: /mnt/2tbhdd/outline
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: milano-v3
  volumeName: outline-backup
