---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_PASSWORD: AgALpDVSR4d/f3Vt3lThNhaFAUAL50/uOx5ZCbh1c5dYrAZa52IMknCsZ6b7mt15kIGAfdZlO2Uc68LjFXhTLkOkaCaXuikmd7sTa8ALtnAbLOt3MHs/440AgVv5CWwlmCpSuQjOIbIX+1LuNA7ufBN6hKF3wUSqkPf8907khy7BWQZGNwWkvL2RVrtzIReLHAnE1KmBL7ommShC79W688TIh/yUruNJP/TB3E2DHlKjTvzCU4W3B9mc27D4G0XtHSqaLqDtk3L03pSebf6kmKKj2nugJfS554uEVdHPPSW+RJctvc4DrqU7yFRnvhGe5ib+6fsNOLkO4j8Hrn/hciycRzxb+CaYjmJ2wx8OxmfECebnv3urX+gI56FpG8vvW77AENwXaPjk9ivVJZ0ne01FwFzAfzcRSH3LO8MzSV04U5JV9zq27iqwUGUQNh8z/2nX1+3lOe+T1bY9zZS/+Pnyed+tyvfUAgizIYSdDb4BJYaxQcRXrgYxBxK8Bl8Y6B/34N3eItj/B7QZK6x00iWHslsAMeJTTLKJsZhTMcGvyAFHTQUpjSV/OrdoKq5byoNHdMPFQGIQNGLzCfkwMJbKIEw1EAClriZ3vxjEhO+luNx+HmAs9BSurKBs0F4E3Kwu2/3svoIdkhRwNtHrY+ZTpphlqP3TO9LgPXZexi4b1Sxy+G3+/KdhGnmQdjiEBcFnMKSWmztsb+HSIpE1gbp8vdMtyNVPXTcl
  template:
    metadata:
      creationTimestamp: null
      name: outline-credentials
      namespace: mgd-default
    type: Opaque
