---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: outline-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_PASSWORD: AgAoOPA7n6IeWBT+CneY2ls7BrAD4QUbNpSxRDm5WSeaNyWre0JM6+q9j4d15JXIrW/cAa1MRqR4xXsJoB+WArilUfxgoejR1eXdwF5XwmFShPACITuSoXXO1fpYbwS7taFVdp8vbo8f3TBUdAgft8kNNR4MPRUOe42on54pA1eLenXmJJziCjDWCX8JsX4jd8vA26Ajc6X9rfm+poeah6SBrFLtepjgwvpSylqpybEwolQ6OtNT7ZMRZBDERQ9LyCS7MzpZf7Al1xlj6BMQvgrk27bI8ezr+/n+saLzp9U36oYleCXmqEWyyTb7sJacghP44xYdgdA8CnPE+0q/Rbrf6/Danrhz1M2wXHYxz5tiz6H4g4faPdgortO5Yrpb7SCYPHWx8zqblhz+PNLsUcg34cWyJGetlt/wAKyhNRCCmxMXzFMtzu5qjzG3E/WuXaMyDn+aeuWLJoLZu0EQZ+PvkEUl4uFMf7iC0LcQB6skStRqRuzBpsAmowkQp4RkshhDa2Li68gDAxRoPlXWP+zwu/9Ho3Yd3gFZNXZbcU60ECC0rqf7UKJWF24HMGFyNSajmWw+VxKtPtg1K7zXrXR7MxzGnxjvnqQ37E2JQuaaGzn8l+eonBNKJAjerk5PbbX3WMfK51qn0UkJUxuorTShgGDt4hB8gLYThyzohwl1qbgIC83SPTfXhvon8zQPyQoLA3d9F4I+cIugX0RsruJlupNVYn6BJ1Q2
  template:
    metadata:
      creationTimestamp: null
      name: outline-credentials
      namespace: mgd-default
    type: Opaque
