---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_PASSWORD: AgBkP7vc/vuQwQDc3FFGJo6ka/QJIGtH8YlOOthzR4NYrF/mMmX+JYPw3+1GQdmxwP7Za4W2mckx55pPiS/y38qcWEdzK+mRhnsfladmiOgjjgmjqOQ8Wwh7OpBVJJKLZwsC5BMEZFEAUNNn0SVbOsv4IGpGsEsftMf/PfSMDoGll061Bojcd9XqEwf22xsSXTIuNJUsWwRkC7iaN3zlRrLqD9trA990o8Wvw9fX5PmrYFiMzBRdSjSOPt9VfgelIKG7oarlXV+KlrLw9ujcAevuZ9R1tu5BIh9zFM2W8pQ8GKdTutnVq9CmJbMpm5gV+pa0isuDJm3AARqaVC60Y6i3zz8AMCncdCbqhybZ7507zOovaZCa9p2hPUs+g5mM+a04xv6Neh8xhZ2V4Yx9tCp9aHPQk93D489xfE4wDqgexZNj83uFFjWqY22GbeoPXTWSwJshKPNeD5CuNOCkg/7H6k5wCAHS78hRD+svR2bI9tuKTDo9REh6wY0sb/n0svkLyTCnl2dijG63HQGOGulHFW0THk77cLbGM6z+pXU+y5Qyu8jEXWbBVcSJfgKpKu72Q7tRJD5rYEFLP4UkQZnPiQlZRirF1KR3PslLIOUqZXpMHTNqJ74EKyWbJi5yn8m3nruWs1N5mWofscGHgMEv616QRdDjEGK/7tESox4rXLufCxiOGKEhASRyjMohL+CBQROS24+2Ga0iROtliTjnA9imRLo729Rm
    OIDC_CLIENT_SECRET: AgBziUQp+Y5mc6KeBh4HqgWCuQWkn+Z9qCCM1bQAAi8JQR024MM8Fdt496upI3STvqoROASNWIGQn0SWWLmoVXelgqu8DSnhmyQrvSrENeBEC8IxII0Pk9xejCZ7e8nVn0iEuR345UR9rVgAy2cishpOnj6nWyVQhnKvl9mrr8VHBq+tinTjb2Ey1904TORj2eLkR0Z9ZcZO5LjvwaZjj5BUMkLN+bc0wXmihnXXMHEz4LndVA6e398pSHk2UoN/UJADxwQJ4EOU/d07g/Ei4f0MesTwG2tjUiatNVbiLGTgPDLf1HikhWzsqQRhEiaDtE+eMqGsrOTl+neSkAPEfZ9HiqLJVRHtgZgZBLpPW8Krz3IDGhH+RqHn56PARNaJBmJsLTiHQUXQsQwgl3NJhOdLOEE8hMzsiSFqU0jAuBjb5qZ/GFL6vDsz19SVvCtMJod0Pm3goS7+khLk+NfuIF8NKE4YYUYDgMBIV1PSh83jtT8Fk2j5MZXLYuKLKVXHhj4fOUgLW1BbvFv6DNS9Z7Mg3AgzRCA+8WTYNgqs7DWQCIURcH4ocMRqGIVXUFnAJHPVuDV8HtSxGoNC6NYQhsXo5QrJCeeR9zF39hVCwTyKmsVDmOEWrgZ2Vm5o7xH9qb9h2u4EgaCvAE+zI1Wr2mzE0zwUZTy07zhuOqIRyZDWYj0YjhHI2P66xVBpJ3zzPzz6Ns1cCGkg6YyupZSLALiG37lOFmiXioF0/bSUuRkdantuuIJa88Hc8bj+pNfd+2qJBgcSHj/P/9u0LAau61Z9ehQV/CbVeNw=
  template:
    metadata:
      name: outline-credentials
      namespace: mgd-default
    type: Opaque
