---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: outline-credentials
  namespace: mgd-security
spec:
  encryptedData:
    DB_PASSWORD: AgAHSX1TvVOB7iMs9nndXxkY1jhuON6g+e9gXTMKqLQP4XFXFFdvP6gHxEKOW4XYXNRzH2BAb7eFbCb95OKici2swuW9KHUSZpXnUEJxyNvFr4ht4AJpvB5pdtGO0QCRzsmKhTuh8RcqAHg4Kj/pJVODIyotbPC+A6nwVNDs3gR3bFP/2aurmAenY5KV3jf9yN4ZjQR9zFq9sfMDIFaDl+26+NaNLhBuwD+XvXR+COCJY1UoTqY0E7HkjFjXT7T7eBX+2Ow/R5PmYgThIyiVyaxDc0Jv+VABdqDRWh4yapes5fn0ARsGozcUkGAIzVoZe67zIixxAF0ZH5CaqgmSluHSRbhXChu4knHJ7YIw1TEcvETvVJ6OwEo25bDhONAKaOD0JcZL55EJvWqwZ8n9wdqy1cptpwqIf2cO8aoij2j+toH2+a+RzUwwXdtSkygj4xlABhmpO0FqOdFn5cnLusNgd6cASE3Sb+OLA8jyLNAPh3JAMy0v/UNAxtg1u8U/oMzALGqIaYK0sQUbLDOUO2jW7BEsgtF2sjUcIAENwVA+kTcAgnCnUp57LZwZOmOy2YVjk8RondYax18cKQKZMqbERDVELApk6oJ+96GZqgOt0vwJVCZF43uRKjT1mIyAFA1LMdCwh73BFQHERb6op7StjWWkWvq1NI1jd5q/w3Tptrrzw/Ymoo4qgsbYioX6MPn/f411sfmCNWMvi+/lHD2qqDQDrBiENfhG
    OIDC_CLIENT_SECRET: AgDXYAOH1doGpyLe4TZdzdzJBubP+hzOBlAtePNETB6yZ/BmwDe9bjpG238KFnP9C9yIxZ5mr5B8EMJ5edLf4AH85B1TtuOeNVQySlDe2nkNGW8WIXFLTNdAxMOUDQqyQSQvjwj4JsULdGqm/8NCHSOADBmOE7zRQ6JzWFHqIHXOxBh48b+70jN/Eqt1jPRzesO1dAyUk2hJFGRmOSDPT3WqqabR5Cvx61fOD9ZJtWY9y9dqmYYKIw1wvC9OHqjgJmmBVk0vOeEXizZIIAnPlrP7d+PM3bCMud5RwwVor2PKhLh25K7MWrJ5jYMU02zwlqWqtgC77wpSiWHP1ISAkOqnRhyZ6nGQZ9xkwqchMb+whum1cq/S49A6BmDKVufuihkEdIq2NlpzwNT1QxHC25Dvru7aS4ICduhLtxUF+DeuQmlvWgUl35Nd1YHp+RmpiFZ2AGrWodiRiPArV+rxw2drnnJWcwU0ytQfXAlJzkHknYQBj/Z7+alphmdXy/SPcCqCErBClNbclDevipQWDlk/hDp+Fb4iIkagJDIMtAZ4BG69wQQOe3+kJzNopVyyGiRDQc8bQLkJT+Ns7o/hO9YRJOBTsT7h5tt+Z/hyNMeN8Abtq/eDPJe0eNqf/gZNGS/HEJYUtfz1akn5zzqv8Q2HHLy8JI1DfnxKtKBGzK126IqLA89W+s2uECc2kioO3s5bGg2OrRY6CsVZ98h006DANkOuA+T1T+kiXDuVqfU1gjQ0vXGr/OJkZi8OBF7ammCopKIl1osxf8LS0I13KTC1
  template:
    metadata:
      name: outline-credentials
      namespace: mgd-security
    type: Opaque
