# tplink-exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app kasa-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        # renovate: depName=fffonion/tplink-plug-exporter
        image: fffonion/tplink-plug-exporter:latest
        ports:
        - containerPort: 9233
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9233
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi