---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kasa-secrets
  namespace: mgd-monitoring
spec:
  encryptedData:
    USERNAME: AgBy2tCZxVTVJU+zoa3xOcCuAofzhEj7pcKrnYYhwNbMp8muRZj8xxuCRomboE9DZ9wb9gV+o7DUaSad2HuN/55ksUSa5qYeN0OTd3dnsBtpWq33puLX2ZK2RpoKSy/bM/AOSxPTV0j5Lzb9Z+Oo0KHA/nmMFAs5wqjcaGwNbIhd6k8kAvc5Of4p25sOAdAKj34/mHFK8/RFJh8n5Ul3xjDkNMZudZ2A4mw8bVK94pz1SezkIbqXgc29TaOIgtXPZeUO5IIF8hndRO2rrIYtDf9h5y8K7sURihHUMlhXs6e+/ZqtGDOlcun/jUUMzLOIoMol7DT0Fq2pK6j4lSQzvqlNGnW4Gfx/gQQtXvSUylM+1/VqIMkEH2fi6qznu4kc2zXfRrAMPOXX//m13oTrc/vzpyapZrQgxUtLIViyfnwZenIxL9IrxJ4tsx/D9kTJp3W9Xg/FbsyU847Zww5jrZFFX0A3JGhVk4yUCHCqRNg8tbAPmHyyA7sbJaCqeLj712MLCI+MOmI9hfABB6J5Fira0vItqDLojtbY9Di5bgoE6GNo/wlpjgLmU40o6OWg8eTQSANVCbJigOgd/S1/c5PtY9PJkPKxHPFqCo5zNmG0YSIKpmLsGNiM1PhfPway9St8GCstHg7dLp/Ta+jVoBYKGGgk8iHMQC8TzKoDt9DuVzIN8sEN5CTXnFgrNJsPfJQ6Hu20QZWnNa7z7GEHS0mYc+Bm
    USERPSWD: AgAxGzmnwZKDJI/xLJ+iWUc0LBJKPdgxWg/zqEh7G0UE/jCi0GxUij2e1k+Nmq66q70wzyHOnpBtpSx/M8/M5daLa9qjkgpdmNsOi5r+9V2sATKORd9bhyLnqU5Yv1BohPYJ1dLCLLIRePhSZHrspVZcQVWsjA8T2nfkm5xp8JlqyjhqFA1HK0PwWZ3OgkDNJmGR82XTP558KWkzUQQJL0qGDKJ/W038xYU2Zl7nzx9jN5/62N9mMB/X5pzZ4AmX8vXeCjpGJClf/mvuOxww6DjdeJArrWT6AL4HQPswAzvLyt85o1LehPWVOsSYU47p2UaWhCngCnYhDNLDsG/BPXgNYfIbvFZcMCH4AgymTtOXpg3EwAyB1gJ6sKrKwgkYZkGGaMZjF5248eoSEnLGF+RgJbMJAaK4olzkGjzZ1Ogh/HAZAvxHrpVQGpGJ2z1NaIDaMQ/gWh5cr5pCo5+jQa2OR+FE+go0Z1z1gGaagHZ48TYI4mz2y4fwBGb7Sd5PEqammzbropepX1PFlo/1TVbR/iDABHOxVkM/zoOdVU4GctiqwtKRxqjsbZK8K0dt2GTN0IBKBHuMeXs50JT8u29GpeWnEKv1/s1xpduVD9yI1nSc5a+Opma+ghPgocGvsDWkw1QqoSU/xm2yL6FnPArwO3vLctG4dh0q30zObWboGSgd2IAZPZEV9pqXzv0Rv1kf5Y4bXpW9OGhZfpJYGOOY9c8v6uGsIVLe5HhJaZyZ8kOzD7E+kJTI
  template:
    metadata:
      name: kasa-secrets
      namespace: mgd-monitoring
    type: Opaque
