---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kasa-secrets
  namespace: mgd-monitoring
spec:
  encryptedData:
    USERNAME: AgAsJP0haPTdj+GaPXVEPXKb2crzoZSjyZsjV3lqrXUJok8sD6dAbvhZch4AsxcvSNQ96u1RNLXBpaV0Fk0OP3g7itFzQ6yn8Due/4OMR0dQURH/cM/BR9Pl+lpDLh1/faE3NRKtRy7XTaNkfUIz2ge7+12wZcKo4V81UdiQFJley2evDyZngd0jcaeLRyz57dp8wm1n9+qI/EahQWHwCvQBLnfSY0HE4US0LNg619WTDEmapUI3DaVsiwag+IszZ2IgMqU9t4te7fHLPMEKRL1DHR8X8FOE5zdrvRlKCny+iDNS09WLeJMQXKM8NRADr1rn3MmnS50nehqlA6/6tcrEs2wHFToRj6nK2ZQLXnEGK09fsvBil+YEmz6AUQzGM758d+VS/gOZMlcfb9hK7tntB8VmS0I1r77MRpDRD01dmPCY2y7s/TBEE8vWLqjPvYHOdgtl/Xtll9lMJCfwAwEQgYjXClK7fMk+5axlcDGM7IcdpUyEhb1vUDk9L/H3LryzOOb5acbjYN/svQmqm3XhYQ+0ZHIdgx0Wq6GDr1KKXGXS6TY1SFLzxL67TC+yKLqs38JctB9aZ1xqWrU9Zg4WjKLWeUccRMoBoo2WJzA755iHblm9HG7cziGnNcN5OTgO3tttTH3+6ZP6FIi/GemQbL5KmEFhdPUIhs9nCkY7ILozuycX6NPD2lm099bdgYNS6LIP3ygCmYAY/tNctno0E+RX
    USERPSWD: AgBeRPsbpaDIEzVCUc3IFIoM3Nujh9lbR1yAfo653/9cOOLvlufvOU8K3nYH7pQjtw9k8awpvem0+eTGV8kS6Qqs61OjB+t33VroQTlEQSnrwmx9Ja6zqwEou56w23dhxBTYBnj537uaxqEOC3CIXMjqHtogCTHNT22vkY36u3yJ8hviwmK2E6L5XGMrk1lxUPFjwA8eaySzAOOQFdDNVL8HnK6k48GnF37LwHr1w0tRU4NNwkQkF5t+80l63shRkqmSJ7OaJvAUKv/KGjBTQ0WupJklQZChVxj0srnzCpcS1ryN6u2kXFMCBgeVemcViKdXElbgX5xe+OiWsnpcuZZm8XDZafR51wHeSx7XWYcX5ksUG6i7kEkuwcK7qpV+AtHWnMRIrNGHDnn6KNM/x8JPRKwarLFEa7bi+YwuT1ZIsdQ5MbsA5YR77pYRWjQPfbIBm5xF7v79NorbJTkz/MGYwzLnElFPq1qqM9ls7lRrGbapz5E0BdtSbjxbh/qgA1bxiPm7BF9Qz3KL7HsF+M4JoE6zJgUN0mbGiksuwWvlpkHonpvEORqBafDrrNTril5AHu2D/IyvrQmlVPVVwAlDgMzzRR9yA/gGkuQ7HCJDG5sSBTVnkukgyF8w3qxiYoyDtMUTU+I+qf69YBDZ9hJm/qHbfWDqpvVsHccgwLc1HFjIfutKswCFoWomp9UtauoXKSs5aX/VVIQqJHQ1RAommWVg6Fbq4azfjftfYY1AQIBrQ83fYzna
  template:
    metadata:
      creationTimestamp: null
      name: kasa-secrets
      namespace: mgd-monitoring
    type: Opaque
