---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kasa-secrets
  namespace: mgd-monitoring
spec:
  encryptedData:
    USERNAME: AgDTEbjM/f5ek9R2ve4hx6BUvcS9Tsc+uQes8dE1pGCH+oWCr0BxrwHa06pBb1D9WBAvPOgobqNfzkE0UazBHeB1JS/AiqejQjpNAaJ84h0FFQiQS1yN8u6mdT+jd6oa/iopKVAbUvSXEQG1KSAkVWKlDs6IYHDtFBZXJ2CQW95soep6RoGicDbxRa1HBWQfzeqmI/zm3pMsFr9Qu8VlVf/9F8rduYqvOB/hczWL+dxqmIwCaBsj6Hokf4qWQSqV+WXnU38IdaMrsV+QTEVWoj2DqIW2j6zASZ3alLcq9C5pWbGP94WvylUjT9Y0peAYjn8ut4dGuU97qXK3b7e7uA9uaGd5HCUsJqYWBPDlhKkzGBkor7dx8Nl+Ffzz0SUTYTNWiPoFYgXBxGZXBvb25bFgCtORzJYNUx6Ea+hJgq4O7virgNLNvI40l0bd79j29RRns4Yi0E9rBH5C+vPg5LtevDCsyMiw77wEny7v+qv/7x3SgwRuYw8A5jsPsiqghRNxo7hoJ0DSFY7v+ar8Yep8hnGHJ6c+ehmUAAk3wZHeq7guFNTOrn4x0Z/Q9w+SHCzBYOuQ/h8zQqVmt4WUWM+33hKu91ktQbVdMVitnouKlHgtW0wptWyBp/KdFsYt+pLRCK3L4lRqtn6A304rdTRqOJcAyjhQYDro270uZ1xM8q1BfAVNNrbIIB4FEq86510FRCqqCOfQ2iQPqaz3KoKOQHlh
    USERPSWD: AgA03/2UH00o4ndwBinMXDogTM4nX2SR/uIeghcriksHCxzgULSJEo3feoBiHFOJG/ygZHvDXzCjx8MnvXJa2U/7aWJWxH7Zga7yCDGL8s4DELV9XeV2RclTivSmHfeyH8bDmwa0d7IcKyRhT2cs0OIrf0SmEBdpDzI7yS7b0m3ZdHQi9dO8SHGn1DV+0oKp5ka4wrx21sNBd9eyJ3bHY31eFE3boqnkDmYNjMtD89mdTnQ5OBQowqJYeC6jqJFZ/CQojdfBiDTCKpgTc3sZNBHs1ZGfwcS4+FgDR1f1VIK5E8ZbeaKiCx5QiSJUT2GbWHvZITPslRgMw0BMk9N+PXORTiz7ZLLNLPXFXfWXakXv6lTUcgIpsamC1pUtEcCikrHGlIftP0THGvZ1NMz66eD6zXLhj/tOSiStyTlgxFDBAMhaZhGqo+UZmE7WZmPUmZgYzYwG9cN/qk8kfOrr48eNUKg+7o5/Mk7Xf6UxHXhdJRZ5g9Cm1+xpGCsxOWCesdY+bb5UgLbJbzpV0mY49DMOnN0cc91hXA+OI7/HGZKKPIX05+iH2lCUAM8aW5iglimVQmG3/q+l8u2j5Sy3BXdvB8osCRC4zgm3IHpzpJ0paN5Xsm9ooq7vmpLEmycRPpYD2WZHucX5UqJUKIiKKQ6i9D7QATrXA39YoT+MV+VPMp4usDdUUnxWtRS+7AF1wYF4DUB5FvYPpRikVsd+lwnFVmMWwYiWi27vKdTqDrFX5ID0j8vPxN8K
  template:
    metadata:
      creationTimestamp: null
      name: kasa-secrets
      namespace: mgd-monitoring
    type: Opaque
