apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jackett
spec:
  chart: jackett
  repo: https://bananaspliff.github.io/geek-charts
  targetNamespace: mgd-entertain
  valuesContent: |-
    replicaCount: 1

    image:
      repository: "gjeanmart/jackettvpn" # Special image to use Jackett over a VPN
      tag: "arm-latest"
      pullPolicy: IfNotPresent

    env:
      - name: VPN_ENABLED
        value: "yes" # Enable Jackett over VPN
      - name: VPN_USERNAME
        valueFrom:
          secretKeyRef: # Reference to the secret | openvpn.username
            name: "openvpn"
            key: "username"
      - name: VPN_PASSWORD
        valueFrom:
          secretKeyRef: # Reference to the secret | openvpn.password
            name: "openvpn"
            key: "password"
      - name: LAN_NETWORK
        value: "192.168.0.0/24"
      - name: CREATE_TUN_DEVICE
        value: "true" # Needed for VPN
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: "entertainment-pvc"
        persistentVolumeClaim:
          claimName: "entertainment-pvc" # PersistentVolumeClaim created earlier
      - name: "dev-tun"  # Needed for VPN
        hostPath:
          path: "/dev/net/tun"

    volumeMounts:
      - name: "entertainment-pvc"
        mountPath: "/config"
        subPath: "configs/jackett"
      - name: "entertainment-pvc"
        mountPath: "/downloads"
        subPath: "downloads/jackett"

    securityContext:
      capabilities: # Needed for VPN
        add:
          - NET_ADMIN