
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jackett
  namespace: mgd-entertain
spec:
  interval: 10m
  chart:
    spec:
      chart: jackett
      sourceRef:
        kind: HelmRepository
        name: bananaspliff-geek-charts
      version: "*"
  values:
    replicaCount: 1

    image:
      repository: "gjeanmart/jackettvpn"
      tag: "arm-latest"
      pullPolicy: IfNotPresent

    env:
      - name: VPN_ENABLED
        value: "yes"
      - name: VPN_USERNAME
        valueFrom:
          secretKeyRef:
            name: "openvpn"
            key: "username"
      - name: VPN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "openvpn"
            key: "password"
      - name: LAN_NETWORK
        value: "192.168.0.0/24"
      - name: CREATE_TUN_DEVICE
        value: "true"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: "entertainment-pvc"
        persistentVolumeClaim:
          claimName: "entertainment-pvc"
      - name: "dev-tun"
        hostPath:
          path: "/dev/net/tun"

    volumeMounts:
      - name: "entertainment-pvc"
        mountPath: "/config"
        subPath: "configs/jackett"
      - name: "entertainment-pvc"
        mountPath: "/downloads"
        subPath: "downloads/jackett"

    securityContext:
      capabilities:
        add:
          - NET_ADMIN