apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nirmalhk7@gmail.com
    privateKeySecretRef:
      name: milano-prod-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
        selector: {}
      - dns01:
          cloudflare:
            email: nirmalhk7@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "trusted.nirmalhk7.com"