apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: mgd-entertain
spec:
  chart:
    spec:
      chart: plex-media-server
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: plex
  values:
    persistence: 
      media:
        existingClaim: entertainment-pvc

    commonLabels: 
      milano.app: plex

    extraEnv:
      PLEX_CLAIM: "testing"