apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - ingressroute.yaml


labels:
  - pairs:
      milano.app: plex