apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: *app
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 1h
  values:
    pod:
      extraVolumes:
          - name: authelia-credentials
            secret:
              secretName: authelia-credentials
      extraVolumeMounts:
        - name: authelia-credentials
          mountPath: /config/users_database.yaml
          subPath: users_database.yaml
          readOnly: true
    persistence:
      enabled: true
      storageClass: milano-v2
    secret:
      existingSecret: authelia-credentials
      additionalSecrets:
        authelia-credentials:
          items:
            - key: storage.encryption.key
              path: storage.encryption.key.txt
            - key: storage.mysql.password
              path: storage.mysql.password.txt
    configMap:
      identity_validation:
        reset_password:
          secret:
            secret_name: authelia-credentials
            path: jwt-secret
      access_control:
        default_policy: 'one_factor'
      theme: 'dark'
      telemetry:
        metrics:
          enabled: true
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yaml
        ldap:
          enabled: false
      session:
        cookies:
          - name: authelia_session
            domain: nirmalhk7.com
        redis:
          enabled: false
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
      storage:
        encryption_key:
          secret_name: authelia-credentials
        local:
          enabled: false
        postgres:
          enabled: false
        mysql:
          enabled: true
          address: 'tcp://172.16.0.106:3306'
          database: 'authelia'
          username: 'authelia_rw'
          password:
            secret_name: authelia-credentials
        