apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: authelia
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 1h
  releaseName: authelia
  values:
    pod:
      extraVolumes:
          - name: authelia-credentials
            secret:
              secretName: authelia-credentials
      extraVolumeMounts:
        - name: authelia-credentials
          mountPath: /config/users_database.yaml
          subPath: users_database.yaml
          readOnly: true
    persistence:
      enabled: true
      storageClass: milano-v2
    secret:
      existingSecret: authelia-app-secrets
      additionalSecrets:
        authelia-credentials:
          items:
            - key: storage.mysql.password
              path: storage.mysql.password.txt
    podLabels:
      milano.app: authelia
      milano.level: managed
    configMap:
      identity_validation: 
        reset_password:
          secret:
            secret_name: authelia-credentials
            path: jwt_secret
      identity_providers:
        oidc:
          enabled: true
          clients:
            - client_id: grafana
              client_secret: { path: /secrets/client-grafana/client_secret.txt }
              scopes: [ openid, email, profile, grafana ]
              client_name: Grafana
              redirect_uris: [ 'https://oidc.example.com/oauth2/callback' ]

              
      access_control:
        default_policy: 'one_factor'
      theme: 'dark'
      telemetry:
        metrics:
          enabled: true
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yaml
        ldap:
          enabled: false
      session:
        cookies:
          - name: authelia_session
            domain: nirmalhk7.com
            subdomain: security.trusted
        redis:
          enabled: false
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
      storage:
        local:
          enabled: false
        postgres:
          enabled: false
        mysql:
          enabled: true
          address: 'tcp://172.16.0.106:3306'
          database: 'authelia'
          username: 'authelia_rw'
          password:
            secret_name: authelia-credentials
        