apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: authelia
      version: 0.11.6
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: mgd-security
  interval: 1h
  values:
    pod:
      extraVolumes:
        - name: authelia-credentials
          secret:
            secretName: authelia-credentials
      extraVolumeMounts:
        - name: authelia-credentials
          mountPath: /config/users_database.yaml
          subPath: users_database.yaml
          readOnly: true
    persistence:
      enabled: true
      storageClass: milano-v2
    secret:
      existingSecret: authelia-credentials
      additionalSecrets:
        authelia-credentials:
          items:
            - key: storage.encryption.key
              path: storage.encryption.key
            - key: storage.mysql.password
              path: storage.mysql.password
            - key: session.encryption.key
              path: session.encryption.key
            - key: jwt-secret
              path: jwt-secret
            - key: users_database.yaml
              path: users_database.yaml
            - key: notifier.smtp.password
              path: notifier.smtp.password
            - key: oidc-hmac-secret
              path: oidc-hmac-secret
            - key: oidc-jwks-private-key.pem
              path: oidc-jwks-private-key.pem
        authelia-app-secrets:
          items:
            - key: client-secret-grafana
              path: client-secret-grafana
            - key: client-secret-nextcloud
              path: client-secret-nextcloud
            - key: client-secret-immich
              path: client-secret-immich
            - key: client-secret-gitea
              path: client-secret-gitea
            - key: client-secret-outline
              path: client-secret-outline
            - key: client-secret-open-webui
              path: client-secret-open-webui
            - key: client-secret-n8n
              path: client-secret-n8n
            - key: client-secret-sonarqube
              path: client-secret-sonarqube
    configMap:
      definitions:
        user_attributes:
          grafana_role:
            expression: '(email == "nirmalh7@gmail.com" || "admins" in groups || "grafana_admin" in groups) ? "admin" : "user"'
          immich_role:
            expression: '"admins" in groups ? "admin" : "user"'
          n8n_instance_role:
            expression: '(email == "nirmalhk7@gmail.com" || "admins" in groups) ? "global:admin" : "global:member"'
      identity_validation:
        reset_password:
          secret:
            secret_name: authelia-credentials
            path: jwt-secret
      access_control:
        default_policy: 'one_factor'
        rules:
          - domain: 'grafana.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'drive.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'immich.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'git.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'outline.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'llms.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'n8n.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'sonarqube.trusted.nirmalhk7.com'
            policy: 'one_factor'
      identity_providers:
        oidc:
          enabled: true
          claims_policies:
            grafana_policy:
              id_token:
                - email
                - groups
                - grafana_role
                - name
                - preferred_username
              custom_claims:
                grafana_role:
                  attribute: grafana_role
            immich_policy:
              custom_claims:
                immich_role:
                  attribute: immich_role
            n8n_policy:
              custom_claims:
                n8n_instance_role:
                  attribute: n8n_instance_role
          scopes:
            grafana_role:
              claims:
                - grafana_role
            immich_role:
              claims:
                - immich_role
            n8n:
              claims:
                - n8n_instance_role
          hmac_secret:
            secret_name: authelia-credentials
            path: oidc-hmac-secret
          jwks:
            - key_id: authelia-oidc-rs256
              use: sig
              algorithm: RS256
              key:
                path: /secrets/authelia-credentials/oidc-jwks-private-key.pem
          clients:
            - client_id: grafana
              client_name: Grafana
              claims_policy: grafana_policy
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-grafana
              redirect_uris:
                - https://grafana.trusted.nirmalhk7.com/login/generic_oauth
              scopes:
                - openid
                - profile
                - email
                - groups
                - grafana_role
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_policy: one_factor
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: nextcloud
              client_name: Nextcloud
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-nextcloud
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://drive.trusted.nirmalhk7.com/apps/user_oidc/code
              scopes:
                - openid
                - profile
                - email
                - groups
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
            - client_id: immich
              client_name: Immich
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-immich
              claims_policy: immich_policy
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://immich.trusted.nirmalhk7.com/auth/login
                - https://immich.trusted.nirmalhk7.com/user-settings
                - app.immich:///oauth-callback
              scopes:
                - openid
                - profile
                - email
                - immich_role
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              access_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
            - client_id: gitea
              client_name: Gitea
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-gitea
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://git.trusted.nirmalhk7.com/user/oauth2/authelia/callback
              scopes:
                - openid
                - profile
                - email
                - groups
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: outline
              client_name: Outline
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-outline
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://outline.trusted.nirmalhk7.com/auth/oidc.callback
              scopes:
                - openid
                - offline_access
                - profile
                - email
              response_types:
                - code
              grant_types:
                - authorization_code
                - refresh_token
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              access_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
            - client_id: open-webui
              client_name: Open WebUI
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-open-webui
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://llms.trusted.nirmalhk7.com/oauth/oidc/callback
              scopes:
                - openid
                - profile
                - email
                - groups
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
            - client_id: n8n
              client_name: n8n
              claims_policy: n8n_policy
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-n8n
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://n8n.trusted.nirmalhk7.com/rest/sso/oidc/callback
              scopes:
                - openid
                - profile
                - email
                - groups
                - n8n
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
            - client_id: sonarqube
              client_name: SonarQube
              client_secret:
                path: /secrets/authelia-app-secrets/client-secret-sonarqube
              public: false
              authorization_policy: one_factor
              redirect_uris:
                - https://sonarqube.trusted.nirmalhk7.com/oauth2/callback/oidc
              scopes:
                - openid
                - profile
                - email
                - groups
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_signed_response_alg: none
              id_token_signed_response_alg: none
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
      theme: 'dark'
      telemetry:
        metrics:
          enabled: true
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yaml
          search:
            email: true
        ldap:
          enabled: false
      session:
        encryption_key:
          secret_name: authelia-credentials
          path: session.encryption.key
        same_site: lax
        inactivity: 4h
        expiration: 12h
        remember_me: 30d
        cookies:
          - name: authelia_session
            domain: nirmalhk7.com
            subdomain: secure.trusted
        redis:
          enabled: false
      notifier:
        filesystem:
          enabled: false
        smtp:
          enabled: true
          address: 'submission://smtp.maileroo.com:587'
          username: nestor@nirmalhk7.com
          password:
            secret_name: authelia-credentials
            path: notifier.smtp.password
          sender: 'Nirmal - Authelia <nestor@nirmalhk7.com>'
          subject: 'Nirmal - {title}'
          startup_check_address: nestor@nirmalhk7.com
      storage:
        encryption_key:
          secret_name: authelia-credentials
          path: storage.encryption.key
        local:
          enabled: false
        postgres:
          enabled: false
        mysql:
          enabled: true
          address: 'tcp://172.16.0.106:3306'
          database: *app
          username: 'authelia_rw'
          password:
            secret_name: authelia-credentials
            path: storage.mysql.password
        
