apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app authelia
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: *app
      version: 0.10.49
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 1h
  values:
    pod:
      extraVolumes:
          - name: authelia-credentials
            secret:
              secretName: authelia-credentials
      extraVolumeMounts:
        - name: authelia-credentials
          mountPath: /config/users_database.yaml
          subPath: users_database.yaml
          readOnly: true
    persistence:
      enabled: true
      storageClass: milano-v2
    secret:
      existingSecret: authelia-credentials
      additionalSecrets:
        authelia-credentials:
          items:
            - key: storage.encryption.key
              path: storage.encryption.key
            - key: storage.mysql.password
              path: storage.mysql.password
            - key: session.encryption.key
              path: session.encryption.key
            - key: jwt-secret
              path: jwt-secret
            - key: users_database.yaml
              path: users_database.yaml
            - key: oidc-hmac-secret
              path: oidc-hmac-secret
            - key: oidc-jwks-private-key.pem
              path: oidc-jwks-private-key.pem
            
        authelia-app-secrets:
          items:
            - key: grafana-client-secret
              path: grafana-client-secret
    configMap:
      identity_validation:
        reset_password:
          secret:
            secret_name: authelia-credentials
            path: jwt-secret
      access_control:
        default_policy: 'one_factor'
        rules:
          - domain: 'grafana.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'drive.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'immich.trusted.nirmalhk7.com'
            policy: 'one_factor'
          - domain: 'git.trusted.nirmalhk7.com'
            policy: 'one_factor'
      identity_providers:
        oidc:
          enabled: true
          hmac_secret:
            secret_name: authelia-credentials
            path: oidc-hmac-secret
          jwks:
            - key_id: authelia-oidc-rs256
              use: sig
              algorithm: RS256
              key:
                path: /secrets/authelia-credentials/oidc-jwks-private-key.pem
          clients:
            - client_id: grafana
              client_name: Grafana
              client_secret:
                path: /secrets/authelia-app-secrets/grafana-client-secret
              redirect_uris:
                - https://grafana.trusted.nirmalhk7.com/login/generic_oauth
              post_logout_redirect_uris:
                - https://grafana.trusted.nirmalhk7.com/login/generic_oauth
              scopes:
                - openid
                - profile
                - email
                - groups
              response_types:
                - code
              grant_types:
                - authorization_code
              authorization_policy: one_factor
              token_endpoint_auth_method: client_secret_basic
      theme: 'dark'
      telemetry:
        metrics:
          enabled: true
      authentication_backend:
        file:
          enabled: true
          path: /config/users_database.yaml
        ldap:
          enabled: false
      session:
        cookies:
          - name: authelia_session
            domain: nirmalhk7.com
        redis:
          enabled: false
      notifier:
        filesystem:
          enabled: true
          filename: /config/notification.txt
      storage:
        encryption_key:
          secret_name: authelia-credentials
        local:
          enabled: false
        postgres:
          enabled: false
        mysql:
          enabled: true
          address: 'tcp://172.16.0.106:3306'
          database: 'authelia'
          username: 'authelia_rw'
          password:
            secret_name: authelia-credentials
        