apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scrutiny-cert
spec:
  secretName: scrutiny-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "scrutiny.trusted.nirmalhk7.com"
  dnsNames:
    - "scrutiny.trusted.nirmalhk7.com"