apiVersion: v1
kind: ConfigMap
metadata:
  name: scrutiny-collector
data:
  collector.yaml: |
    version: 1

    devices:
      - device: /dev/sda
        ignore: true
      - device: /dev/sdb
        ignore: true
