apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrutiny
spec:
  interval: 1h
  chart:
    spec:
      chart: scrutiny
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: scrutiny-repo
        namespace: mgd-monitoring