apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrutiny
  namespace: mgd-monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: scrutiny
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: vhdirk-helm-charts