---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scrutiny-config
  namespace: mgd-monitoring
spec:
  encryptedData:
    scrutiny.yaml: AgCp50LmX/ygKuAo3tVymv/HqanZnUbiTv+B1JKx/nJiVqcqDp+229L6WgnhCKELeglHGPWl98na2H0iggZ4UNyaQwywjRaxmlX+uZK7bGJdZ7pOduvf/Oz7Q85SVP+YLMpz3eScCN1/zO6SPjdkJ62P6LzI8Icq5zbEHvHRTXNJyam7jbZIbVDzJ1hkYMmdGBllDy6EaXFWJUrVXZvVAX8y9WlOXv/6pRKXmtu7nlx4tOB6QAW+8rP3PlzLH8CkfyVdnaI2FgW6/hku7teqJKeOcllvRPePm2cjR5JMhhxrJ8IbBJpnXvptrxLXkiKcn1gsbfN4R7P8+UG6txMXYALhkgrf8Q4pU6BEoB6IvJEUrViecsR5bc3HhZ6N/wdzOVWI/Z8w+WbVuhXcqYn/Mdnjb7rIHYKfGWDyF+NgLEJR6MwZ2rwrYC+gA5Cn7rr6TYdpAVD2lsgJJOY0kI9hopnVN3MMQld0Tqq16Y4aPgs5bx1X12KGiNTHN2n3ZdJCdX3oGt4LaJvzJYQ4YCo7RjqwiICNTR1Oziq2Aq+wXmmbzfjOdIrLWj8/QVfZSV2DnMSgrrzA0LhrNUC3NBpWHDCpYB4KbyA6geisrW7t4K/6Ar+cbVZBl7Eax6e0vbvcQ/tNM16fNn6ZVO09WRmLhY6fE//n5kw9328VsdwZO9tZcIjUI3SbMqgeLaH5D6yW+a5Vp630zpI9qCjEuyf2ZfZmEjRrzPKPLEHZ1vs9FiB+53seUIyZiVVvsJu83r7mMoj/qUzzxo7VJtMbcpZGYvP3MJZTBmwpoe6t62+M7cmvI0xGjWFt9CSoR85Puhca5V+RPIyKqb9kjomyOuK5xEzho5iaxse4COJv/hgQ20H+IrjgHvi9ic5kPb5tu8N4nL3mupMZWkw6sK0vXOBIlOaeq8afm4pLom2Y5h5Q8JkCmZkyZl5z1g==
  template:
    metadata:
      name: scrutiny-config
      namespace: mgd-monitoring
    type: Opaque
