---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scrutiny-config
  namespace: mgd-monitoring
spec:
  encryptedData:
    scrutiny.yaml: AgA4RG4hSUmOjTz5ioJxzKFPlrbn65sAFBU0L5gt+kIwtHPw5u+Vqy3NP0D4+N+31DHrvAGqYa+H06b9PlAP3r7cTSw+V7MseX3J89DTD+ysflNcJV8uBAQ/g/1/WuMayMtD7HfP4/7i9TrXqkWIFLeYn8dc4VQ174exU6dYI3DMr0XT9bvOfCejqtqK/GgHmoRwzmptjcOVE1BptaybFbYtxYn/11Dqgkb1B5vegfupxwBjeQFIFxQDeeL2yGWV6+EdQatZR4fgSMifsI1DWJK3MaEpiMEPa23KUzwSNtsJ1F1KVlellj8rT63yFTv3BWJ7pQPQ5XLA4weXTjCZlnoyj1Wi6G5G4KfjlRcJ//TgmIFwbSgckmgeB+8c0MI/O+eCFmt7rG2gQYRNUe62DhfbOQeFg8uKt3W9hePyDsEaGtbB1H0d0z18xdhcWxKSU/+cVljrvxyNO3RfujZn3XNu/bL9VTkHduzclc01pIzKc4W5zgpQKEotVAR+t7VsG32P8lTCYiHnFSjfixkjMeUBBI7+UD3w2wkHxiXBjNvRG6ASJfPG2OwpVQWBMNv6KuvCHRUu4bD130LAoje4LooC1CTu+iC118sEyW0iY8aRwXMBu23+PrbjtLu1P5QS4HW9/PabDTahlbC2wQhOREgR1rgueUiBMTdrz3iyajFbGSJZPiljj+W5G4PJtOtVNdqG4oVeYFqkw6+Zw1jgTYcW1QKcpHLW9OqrJ7sfJjCQsGFtGIw+faOSO6SA4cr+v7N5LE0vTlS4cERr2jns2b7VgomAXG1/PNY20f52X2qz9fu17Hrc1x5rjKZ0wEykbD8K/lsVknr51nBSKcpFIogDP6z6xToQUQjPvrVDeL2z6WbLiJrzGHkTZwpVgQdZ7NZa/mOqFjKFm54d4FAHrcouj4NbeDWH7U7uIxyAyCruOUSZW88Irw==
  template:
    metadata:
      name: scrutiny-config
      namespace: mgd-monitoring
    type: Opaque
