upstream sentinel_mgd {
    server 172.16.0.103:20211;
    keepalive 10;
}

upstream authelia_mgd {
    server 172.16.0.105:443;
    keepalive 10;
}

server {
    listen 80;
    server_name sentinel.trusted.nirmalhk7.com;

    include conf.d/_security.conf;
    include conf.d/_authelia_auth_server.conf;
    add_header Milano-Resource "OCB-sentinel";

    location / {
        include conf.d/_authelia_auth_location.conf;
        proxy_pass http://sentinel_mgd;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        include conf.d/_security_location.conf;
    }
}

server {
    listen 443 ssl;
    server_name sentinel.trusted.nirmalhk7.com;

    include conf.d/_security.conf;
    include conf.d/_security_https.conf;
    include conf.d/_authelia_auth_server.conf;
    add_header Milano-Resource "OCB-sentinel";

    location / {
        include conf.d/_authelia_auth_location.conf;
        proxy_pass http://sentinel_mgd;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        include conf.d/_security_location.conf;
    }
}
