# Server block for test.trusted.nirmalhk7.com
server {
    listen 80;
    server_name status.trusted.nirmalhk7.com;
    
    include conf.d/_security.conf;
    add_header Milano-Resource "OCB-status";

    location = / {
        limit_req zone=addr burst=20 nodelay;
        add_header Content-Type application/json;
        return 200 "{\"status\":true,\"timestamp\":\"$time_iso8601\"}";
    }
}

server {
    listen 443 ssl;
    server_name status.trusted.nirmalhk7.com;

    include conf.d/_security.conf;
    include conf.d/_security_https.conf;
    add_header Milano-Resource "OCB-status";

    location = / {
        limit_req zone=addr burst=20 nodelay;
        add_header Content-Type application/json;
        return 200 "{\"status\":true,\"timestamp\":\"$time_iso8601\"}";
    }
}