apiVersion: v1
kind: Secret
metadata:
  name: rahul-cluster-observer-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: rahul-cluster-observer
type: kubernetes.io/service-account-token
