---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: calendar-merge-secret
  namespace: mgd-default
spec:
  encryptedData:
    ICS_URLS: <user-must-provide-sealed-secret-here>
  template:
    metadata:
      creationTimestamp: null
      labels:
        milano.app: calendar-merge
        milano.level: managed
      name: calendar-merge-secret
      namespace: mgd-default
    type: Opaque
