apiVersion: v1
kind: Service
metadata:
  name: &app calendar-merge
  labels:
    app.kubernetes.io/name: calendar-merge
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 31217
  selector:
    app.kubernetes.io/name: calendar-merge
