apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mailu
spec:
  chart: mailu
  repo: https://mailu.github.io/helm-charts/
  version: 2.1.2
  targetNamespace: mgd-default
  valuesContent: |-
    commonLabels: 
      milano.app: mailu
      milano.level: managed
    
    hostnames:
      - trusted.nirmalhk7.com

    domain:
      - nirmalhk7.com
    
    existingSecret: mailu-credentials