apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: mgd-monitoring
spec:
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
  interval: 10m
  values:  
    service:
      type: ClusterIP
    persistence:
      storageClass: milano-v2
    env:
      - name: TRUSTED_ORIGINS
        value: "portainer.trusted.nirmalhk7.com"