apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - _storageclasses
  - db
  - default
  - devbench
  - flux-system
  - kube-system
  - llm
  - monitoring
  - multimedia
  - security
  - media

labels:
  - pairs:
      milano.level: managed