---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-actions-runner
  namespace: mgd-devbench
spec:
  encryptedData:
    token: AgCNfLQ59mfwe/7smWVqOLm+NRnzlOqOt5Zgu/jfEo7KBaOJ5otB2ZxKiTSENC8whva/xMrlHgqnu6K0Ii+pDk6UQrltBOGQgWLMgCKYxrk/5pOncCXROPvGmnoW2qgC2iEfoyB7FiriYG1/ALaItIlz15YUiHgU3a2eeZd2vi5h7K3IovtTXBITzBI2EXxhdDlTCHLpi7xRHvvl0IoHeLDap9CFexKGTi/yNSVlgj0cnLtsYlbcOwGXRFkIngP4750ET2yLfB0KqgZpVbiiLV95bzJqCrSItWsqNxXRdf7sJioc0ucd1GmOVM2J9Jo+nO+D+uyRDCcWTlmK1nAJtX6vNvPAX9X9CVNJEF/oJVpMBIBDBpnFeE4sgz8rz48HTR7716qp4x9FYUNGOe+bMaa3hjk1Zd9kFIlxEc+TrohmtzJha0SL7YOCQRr48adlqeUTOGHDnBrwUL3sp3pAIQGOqs7c8CG6PeKZAJ9If2fFrhcHvspXjgEVm9c8iyVdmbvqCN2kkfit3hZo1f2sFewcjxfJLNtArlkeusFtvCN8OI/yGy+7EAt8VWiBBPL1ijVxXkOQlTkDvPqe30mYKKMWoRAfH3ZVB6X+87yYLpMhu0G//gMBkWZHPHoJE/t/r50BBcnkHcW8XRnbLUkm5FEY/naAlOr+33gho57aXLUL88FbDdasUanJYqnJmEjUhhSplT1dROmmhdvofNN3V7P7cQc5stq+3QOASAkmLYU+PKAljPh9R3U7
  template:
    metadata:
      name: gitea-actions-runner
      namespace: mgd-devbench
    type: Opaque
