---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-actions-runner
  namespace: mgd-devbench
spec:
  encryptedData:
    token: AgAP3HAaOwSNkAp1Q8VioUbcH/g5TTV9+GMsnRefXg36JmPpF17kAIlr8NXvx4lENRHppmUD1xyvgpn4Y7M0oHPysM5/vC0c3fligz9KfUn7w2oXJaqoTt5hNK/waIq6ozY8vVJ8f5y2urLX7ZFYP4ZrhVPgRhE+jrZFEOmeYXOW+F3bllTEdRChnGDi50g5W+3jiXRrcmlB6JdXYiuQBAQdwIu/bC1R3D/6EEEmyp42M86gUWo0QrxY+4fsIgwL9J1AnD/la5QuKjJGiOGfZZi2GQEAdNt4iupLOQrUJ12suq2+qN/WZ6mw5mrT1ioWVvGHSuwNJXwVCkYsE8GW5L0WqnmUuJAE2RmBx1NSpclz2M8+SEUzfa+ETuVtpXGBm5Y8Mq3boaVohaE2DXQJi4aF5DUGaZdi7amR20n6jb5OoMpsqW3TmmsS6Sc4w3jMO2/dcsJQTbAE23RvurAJuwOQrbAG3L1jY7KAZQtF5Ve6kgE/R90Q/lhMO0jeuOWE91tIUuWJ7fEq0Y600Tf+alUDT6yA3/r32cBaOckEKPMKX22S5ytrlecOuPjnUoUHm8xxLXZv3NzxIWHMQ3jNPEsLOruSxdLfbw+EhstzNpcFtuppfOlV4NTiSuxub2UCU+dAzIa8Y30140x/xvmiaCgCHO5mDcemkTxwVZub108qJCDLtiwI5p6lXBGlCF6APyJvsuz+alIxZdknuGUQa6fmD3+ql9tFr4PREoVenYMr36XgajaOzI0Y
  template:
    metadata:
      name: gitea-actions-runner
      namespace: mgd-devbench
    type: Opaque
