apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
spec:
  chart:
    spec:
      chart: gitea
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 10m
  releaseName: gitea
  targetNamespace: mgd-devbench
  values:
    commonLabels:
      milano.app: gitea
      milano.level: managed
    postgresql:
      enabled: false

    postgresql-ha:
      enabled: false

    adminUsername: nirmalhk7
    adminEmail: nirmalhk7
    extraEnvVarsSecret: gitea-secrets
    
    rootURL: gitea.trusted.nirmalhk7.com
    externalDatabase:
      existingSecret: "gitea-secrets"
      existingSecretPasswordKey: "DB-PASSWORD"