apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea
  namespace: mgd-devbench
spec:
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: *app
  interval: 10m
  releaseName: *app
  values:
    postgresql-ha:
      enabled: false
    persistence:
      claimName: gitea-pvc-1
      storageClass: milano-v3
      size: 10Gi
      labels:
        milano.app: *app
    valkey:
      enabled: false
    valkey-cluster:
      enabled: false
    gitea:
      additionalConfigFromEnvs:
      - name: GITEA__database__DB_TYPE
        value: mysql
      - name: GITEA__database__NAME
        value: *app
      - name: GITEA__database__HOST
        value: 172.16.0.106:3306
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: gitea-credentials
            key: DB_USER
      - name: GITEA__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-credentials
            key: DB_PASSWORD