apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitea
  namespace: mgd-devbench
spec:
  chart:
    spec:
      chart: gitea
      version: 12.6.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: mgd-devbench
  interval: 10m
  releaseName: *app
  values:
    strategy:
      type: Recreate
    postgresql-ha:
      enabled: false
    persistence:
      claimName: gitea-app-pvc-1
      storageClass: milano-v2
      size: 10Gi
      labels:
        milano.app: *app
    extraVolumes:
      - name: user-content
        persistentVolumeClaim:
          claimName: gitea-user-content
    extraContainerVolumeMounts:
      - name: user-content
        mountPath: /data-nfs
    valkey:
      enabled: false
    valkey-cluster:
      enabled: false
    gitea:
      oauth:
      - name: authelia
        provider: openidConnect
        existingSecret: gitea-credentials
        useCustomUrls: true
        autoDiscoverUrl: http://authelia-oidc-proxy.mgd-security.svc.cluster.local/.well-known/openid-configuration
        customAuthUrl: https://secure.trusted.nirmalhk7.com/api/oidc/authorization
        customTokenUrl: http://authelia-oidc-proxy.mgd-security.svc.cluster.local/api/oidc/token
        customProfileUrl: http://authelia-oidc-proxy.mgd-security.svc.cluster.local/api/oidc/userinfo
        scopes: openid email profile groups
        groupClaimName: groups
        adminGroup: admins
      config:
        server:
          DOMAIN: git.trusted.nirmalhk7.com
          ROOT_URL: https://git.trusted.nirmalhk7.com/
          PROTOCOL: http
          SSH_DOMAIN: git.trusted.nirmalhk7.com
        repository:
          ROOT: /data-nfs/repositories
        lfs:
          STORAGE_TYPE: local
          PATH: /data-nfs/lfs
        attachment:
          STORAGE_TYPE: local
          PATH: /data-nfs/attachments
        picture:
          AVATAR_UPLOAD_PATH: /data-nfs/avatars
          REPOSITORY_AVATAR_UPLOAD_PATH: /data-nfs/repo-avatars
        storage.packages:
          STORAGE_TYPE: local
          PATH: /data-nfs/packages
        openid:
          ENABLE_OPENID_SIGNIN: false
          ENABLE_OPENID_SIGNUP: true
          WHITELISTED_URIS: secure.trusted.nirmalhk7.com
        service:
          DISABLE_REGISTRATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
          SHOW_REGISTRATION_BUTTON: false
      additionalConfigFromEnvs:
      - name: GITEA__database__DB_TYPE
        value: mysql
      - name: GITEA__database__NAME
        value: *app
      - name: GITEA__database__HOST
        value: 172.16.0.106:3306
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: gitea-credentials
            key: DB_USER
      - name: GITEA__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-credentials
            key: DB_PASSWORD
