apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
spec:
  chartRef:
    kind: HelpRepository
    name: gitea
  interval: 10m
  releaseName: gitea
  targetNamespace: mgd-devbench
  values:
    