apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroute.yaml
  - nfs-storage.yaml
  - helmrelease.yaml
  - secret.yaml
  - actions-runner-deployment.yaml
  - actions-runner-pvc.yaml
  - actions-runner-secret.yaml


labels:
  - pairs:
      milano.app: gitea
