---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-credentials
  namespace: mgd-default
spec:
  encryptedData:
    DB_PASSWORD: AgCrdeaXK8JPMQCBe4zUhf6/DfJftAAn8ASvhspqekVYkUzBFTxA56FIdKHri4rFtXa5DArQZcFKd/SUvthN4IfAgri84P/3C79Fmiy6X6q1zppoy19Quc/DUiKtiklR/pqe0ySxR74nRIMBxHcpUUk1SmepG1BtE3sachQ7ugAyLfxfTfkH3emTX0K05T2bXBe/YnoyxXIcdqNengZu7WCbP3e0iGpamKSv25ay4bY+IkHzZLg/W3W20GBSRlkLP4mrIQPX5ndDIfE2tBWa7JfZBYTbxNgVN/FUoZ7iepePDMAY0mV1qh2QvaohFBwoQwk9EEFMcv0hu4qkzBF8gkuGC7QvX5u0wSw+dUgJOOjc+qs8Nvp8VcDX6Z5ISExgZwcQx9LhL/tWT5WaKl5JCAAH4RGLMldRtFMd1Ou8M9sV9gHPLyrLI/gTx3KLywUlC1vlKajStHrmlkK0gOQgBZqtli7PooyYcRiPefcl6+gozYdonLznB7zsOvk0LeKli4G/66kdxSg0ma2Zfwazc4Ek2gC/vEzZMYouSVAKZ2rOods1LpIa6Xugqb9GLY3Ht4+ttIzq75vVv9bqhH7JYWV2Yt1v92y3QSIuX8L7U4XntqPZ+gtZHes1GVfxqe8C2Mf4wNGDGWkRmrCEeS0BjW1tICjR/UaS3XUXn1UjfG6ZYGCbR129uttnc5X6na4KMWWMJRE0DsMdJBppRMDF
    DB_USER: AgC4qG/RwLKMUylhy8JdwPOIukRHxg6x2aPERedde8sOEen4GOgKaREGDIW3TkqRzDSf3iI9OOpm430sJ8mYHJNgwIFbMNX8wkqULAUGeOmHLATVy5ILGG3hw3GZV1QQuWsx/0aUSceZLZkjwa5CEuJ/Q2Rr3W8R+T7wdGFDXMJgBovU4oAw20EmcrxpGcelzlEgt14MWGpLk0TuvMjlEVaJ40qkRyQdvdBvyzycxfp42Ln1ZOIbrPcWnzEtDDFkoMv6nYIa1wA2jhNegUjZIiuSxTsbzuHOudqUyyUc+J3wKP/2LxKDe5PIITb7mt4R8wqU/fv0RlH9xtBSaq6Y5j5V7jS05rk3ghkcyydk0Rc+JtuGcYHB9nfPiUbPz6p+gsTUCbfIYrP0Rd4pYiV98knnerSnhEuyfDtqllwx0V394/LslVmym8JBlE5AIjXQTkIDZrkgf96g5Xsf11AXbnEHGsAKaW9japrPLaT5U99iuVDVchjU+/Jc8dmD8+Wd4SqS8erQhrLxjw9kPHnRXQys21xRdgPdl5mrV8qjZa638UNAmKcb6FHAZsqNLYndbFRN0/jasYxMVV2/kMf9FKjpTgxZEKCh36KDeB/6RGe8pOQnK3zNltQ/Ezq4ACj4E45f/v24hADdeaWMLBXjHCT0N2nPkC6FHqbkVSbJHVo7+ExbSQvhjHDFDMOlgUQvSp678a/CL44UkA==
  template:
    metadata:
      name: gitea-credentials
      namespace: mgd-default
    type: Opaque
