upstream db_mariadb {
    server 172.16.0.106:3306;
}

upstream db_postgres {
    server 172.16.0.106:5432;
}

upstream db_mongodb {
    server 172.16.0.106:27017;
}

server {
    listen 3306;
    proxy_pass db_mariadb;
    proxy_connect_timeout 5s;
    proxy_timeout 24h;
}

server {
    listen 5432;
    proxy_pass db_postgres;
    proxy_connect_timeout 5s;
    proxy_timeout 24h;
}

server {
    listen 27017;
    proxy_pass db_mongodb;
    proxy_connect_timeout 5s;
    proxy_timeout 24h;
}
