upstream minecraft_java_wings {
    server 172.16.0.105:30901;
}

upstream minecraft_bedrock_wings {
    server 172.16.0.105:30902;
}

server {
    listen 6901;
    proxy_pass minecraft_java_wings;
    proxy_connect_timeout 5s;
    proxy_timeout 1h;
}

server {
    listen 6901 udp;
    proxy_pass minecraft_bedrock_wings;
    proxy_timeout 1h;
}
