
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bugsink-cert
spec:
  secretName: bugsink-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "bugs.trusted.nirmalhk7.com"
  dnsNames:
    - "bugs.trusted.nirmalhk7.com"