apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app bugsink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: bugsink/bugsink:2.1
        ports:
        - containerPort: 8000
        env:
        - name: BEHIND_HTTPS_PROXY
          value: "true"
        - name: DJANGO_SECURE_PROXY_SSL_HEADER
          value: "HTTP_X_FORWARDED_PROTO,https"
        envFrom:
        - secretRef:
            name: bugsink-credentials