apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugsink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugsink
  template:
    metadata:
      labels:
        app: bugsink
    spec:
      containers:
      - name: bugsink
        image: bugsink/bugsink:2.0
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: bugsink-credentials