apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: &app deliveryhero-helm-charts
  namespace: mgd-devbench
spec:
  url: https://deliveryhero.github.io/helm-charts
  interval: 1h
  type: oci 