apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: &app deliveryhero-helm-charts
  namespace: mgd-devbench
spec:
  type: oci
  url: oci://ghcr.io/deliveryhero/helm-charts
  interval: 1h