apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: &app deliveryhero-helm-charts
  namespace: mgd-devbench
spec:
  url: https://raw.githubusercontent.com/deliveryhero/helm-charts/master/
  interval: 1h