apiVersion: v1
kind: ConfigMap
metadata:
  name: pgvecto-init-script
data:
  init.sql: |

    CREATE DATABASE immich;
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'svc_immich') THEN
        CREATE USER svc_immich WITH PASSWORD '${SVC_APP_PASSWORD}';
      ELSE
        ALTER USER svc_immich WITH PASSWORD '${SVC_APP_PASSWORD}';
      END IF;
      GRANT ALL PRIVILEGES ON DATABASE immich TO svc_immich;
      CREATE EXTENSION IF NOT EXISTS vectors;
    END
    $$;

    CREATE DATABASE authentik;
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'svc_authentik') THEN
        CREATE USER svc_authentik WITH PASSWORD '${SVC_APP_PASSWORD}';
      ELSE
        ALTER USER svc_authentik WITH PASSWORD '${SVC_APP_PASSWORD}';
      END IF;
      GRANT ALL PRIVILEGES ON DATABASE authentik TO svc_authentik;
    END

    CREATE DATABASE docmost;
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'svc_docmost') THEN
        CREATE USER svc_docmost WITH PASSWORD '${SVC_APP_PASSWORD}';
      ELSE
        ALTER USER svc_docmost WITH PASSWORD '${SVC_APP_PASSWORD}';
      END IF;
      GRANT ALL PRIVILEGES ON DATABASE docmost TO svc_docmost;
    END
    $$;