apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvecto
  labels:
    app: pgvecto-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: milano-v2