apiVersion: v1
kind: Service
metadata:
  name: pgvecto
  labels:
    milano.level: managed
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32100 
  selector:
    app: pgvecto-db