apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tools
spec:
  chart: it-tools
  repo: https://charts.plcnk.net
  targetNamespace: mgd-devbench
  valuesContent: |-
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/sharevb/it-tools
              tag: nightly

    persistence:
      data:
        storageClass: milano-v2