
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tools
  namespace: mgd-devbench
spec:
  interval: 10m
  releaseName: *app
  chart:
    spec:
      chart: it-tools
      sourceRef:
        kind: HelmRepository
        name: plcnk
        namespace: mgd-devbench
      version: "*"
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/sharevb/it-tools
              tag: nightly

    persistence:
      data:
        storageClass: milano-v2