
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tools
spec:
  interval: 1h
  releaseName: tools
  chart:
    spec:
      chart: it-tools
      sourceRef:
        kind: HelmRepository
        name: plcnk
        namespace: flux-system
      version: "*"
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/sharevb/it-tools
              tag: nightly

    persistence:
      data:
        storageClass: milano-v2