
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: locust
spec:
  releaseName: locust
  chart:
    spec:
      chart: locust
      version: 0.32.4
      sourceRef:
        kind: HelmRepository
        name: locust
        namespace: flux-system
  interval: 1m
  values:
    image:
      repository: locustio/locust
      tag: 2.32.2
      pullPolicy: IfNotPresent
    extraLabels:
      milano.app: locust
      milano.level: managed