
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app locust
  namespace: mgd-devbench
spec:
  releaseName: *app
  chart:
    spec:
      chart: *app
      version: 0.32.4
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-helm-charts
  interval: 10m
  values:
    image:
      repository: locustio/locust
      tag: 2.43.2
      pullPolicy: IfNotPresent
    extraLabels:
      milano.app: locust
      milano.level: managed
