
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: locust
  namespace: mgd-devbench
spec:
  releaseName: locust
  chart:
    spec:
      chart: locust
      version: 0.32.4
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-helm-charts
  interval: 10m
  values:
    image:
      repository: locustio/locust
      tag: 2.42.6
      pullPolicy: IfNotPresent
    extraLabels:
      milano.app: locust
      milano.level: managed