apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-devbench

resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - ingressroute.yaml

labels:
  - pairs:
      milano.app: locust