apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mgd-devbench

resources:
  - helmrelease.yaml
  - ingressroute.yaml
  - locustfile-configmap.yaml
  - lib-configmap.yaml

labels:
  - pairs:
      milano.app: locust