apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &app pterodactyl-wings-volumes
  namespace: mgd-gaming
  labels:
    milano.app: *app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: milano-v3
  resources:
    requests:
      storage: 50Gi
