apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  chart:
    spec:
      chart: velero
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 1h
  releaseName: velero
  targetNamespace: mgd-security