apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: mgd-security
spec:
  chart:
    spec:
      chart: velero
      version: 8.4.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  interval: 1h
  releaseName: velero
  targetNamespace: mgd-security