---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pterodactyl-secrets
  namespace: mgd-gaming
spec:
  encryptedData:
    APP_KEY: AgBjFl0jTPntBZRtYTdVjWeU54LBAnKEcjEI/JzygApWp+VLsme6pZfHN1cr4Nw6UnNodoK3Ipkmh40O/egydXGbeIFJRbhWp0UfvHrqOioJtkfz6yPpHV+HQ8r7nUbiPXOz4OM7sfuRtLr1sjq098DDYJYgmSVi/FGPU5Eb8Bqi2SQXQj+sVSJb25f5rnzbVuReRzzCssM8TLP+SRRFbgHZnNzgpuiaHvniGAs06YkMdRnTzhCt0RqqsFQLgkD+gXAsxgZY2aHQwV/lA/Ymwf10a+0OGR0rAzCWRW3oY6wdhgmbNZe/qzPqHgw2HUSGXe0o/sgIpDOn+I8WUMR86m28Q681AaRG+2zAYQy+Mo/kIsyt7lvfqKjNubaKK8HObsinod0IH/zJxuR8g9v/t+eSF8LEz80vx20cvg2IEa9yhWCLxfeF97FBx67qGbGRCnbhtO8l90ocO+HRarzDjpmQ5H8OyjpWM3sPIIPfO1NW/vKiu4JKCdKNRQ8TER5CwYd5UQsyU/XZwHJsl3ICOpZ9uABkNog0BrkcqDgkcyNZP8Tqj4G+Qw1ykaOtCL1xPbdgukeS6+Ab6gNY5e26NiradiToiixl641o1aKFg7pCzDg7n8s2Z3tbcT0OhqEnPkd93w9TnnFD1yItvuP3JxEpfAzNt5Rdog5di+t8hpg2VKqJTskstGkoNOGC6iwAlYKJ6p+IoHh3enPpvXynLqt4aa06DXe0WBqgG1n9PoPv86FbZB/+mN1XdkL2xg==
    DB_USERNAME: AgBo2SijrdZad3A5ZPRTezCnx2S1yBbRsRNGBcVwaWj5sMXDKFqJ8YLQbGiVkHBoBGjm/HRVgC5u2WXpyM3FuPwzrhpcgLMcp9DpmWJFKZCWRV1yzhwk+IBpTyoBgpzttAloMxIqdH6GNKEqsM5EXD8tDacJagg6DqXYDmy8VMrLub1Y3rSOLWu2gjtGlSc6N6/g/NaEl+UvBlvzexp2qsq96mrpxjn2eYX7e61rAJQDmiNz7aZwDXk/VSSW5hUus4a9X42QAiCyCjhv1IPCFABatXqlGA0tuggSUBQRN3zHxPE45ysEqPZOHkcdo0att+ihi4ngWzUtolLk6/kIXIB3VOKiIFGrI3ie01SJxF/FRwnfeuUuh/Rv6Go90CPz/mcaAXYShJHLqEjta/ILjP9weJJq59Pp2bEa7g5gzLWSF3byjX8zzovrYF3PX6RrHHTqnHdm2F7BNyRRw0lbzg/7jWW150vlgpXjOZFhA5alU7BWq15q9cyHmmaupLrRL2qK4om/s2pnZmLAf2yi2gPO+tSbFumrVrda1auCn3x2x2RKNTuqWgm5TeUVlFmG4qRLP7Ujl16EZr7kyYQweDMrQyhGUepN1/3Rz+2o9W1/H6kOBF1vcvr1pEpK2NGH/xt/AP3rP+LgKo/vErDKHsGWI/Zg4jY4D6qpZG3hHWAJyT0A7O1vblu7aDnVSYpTpH3UUwWE7HE6gzkb1Oqf
  template:
    metadata:
      name: pterodactyl-secrets
      namespace: mgd-gaming
    type: Opaque
