apiVersion: v1
kind: Service
metadata:
  name: &app pterodactyl
  labels:
    milano.app: *app
    milano.level: managed
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    milano.app: *app