apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appwrite
  namespace: mgd-devbench
spec:
  releaseName: *app
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: appwrite-helm
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: appwrite-helm
        namespace: mgd-devbench
  values:
    global:
      storageClass: milano-v3
      security:
        allowInsecureImages: true
    podLabels:
      milano.app: *app
    environments:
      domain:
        app: dev.trusted.nirmalhk7.com
        target: dev.trusted.nirmalhk7.com
        functions: functions.dev.trusted.nirmalhk7.com
      database:
        host: 172.16.0.106
        port: 3306
        schema: appwrite
        username: appwrite_rw
      redis:
        # PHP Redis extension fails DNS lookup on *.svc.cluster.local FQDNs.
        host: appwrite-redis-master
      influxdb:
        host: appwrite-influxdb
      statsd:
        host: appwrite-telegraf
      usage:
        stats: enabled
      console:
        whitelist:
          emails: nirmalhk7@gmail.com
      options:
        forceHttps: disabled
        functions:
          forceHttps: disabled
      storage:
        device: Local
    components:
      core:
        test: []
        ingress:
          enabled: false
        podLabels:
          milano.app: *app
      console:
        ingress:
          enabled: false
        podLabels:
          milano.app: *app
      realtime:
        test: []
        ingress:
          enabled: false
        podLabels:
          milano.app: *app
      tasks:
        maintenance:
          test: []
      schedulers:
        functions:
          replicaCount: 0
          test: []
        executions:
          test: []
        messages:
          test: []
      workers:
        usage:
          test: []
        usagedump:
          test: []
        audits:
          test: []
        builds:
          replicaCount: 0
          test: []
        certificates:
          test: []
        databases:
          test: []
        deletes:
          test: []
        functions:
          replicaCount: 0
          test: []
        mails:
          test: []
        messaging:
          test: []
        migrations:
          test: []
        webhooks:
          test: []
    mariadb:
      enabled: false
    redis:
      enabled: true
      image:
        repository: bitnamilegacy/redis
        tag: 7.2.3-debian-11-r1
      metrics:
        enabled: false
      auth:
        enabled: false
      replica:
        replicaCount: 0
      master:
        persistence:
          enabled: true
          storageClass: milano-v2
          size: 8Gi
    influxdb:
      enabled: true
      image:
        repository: bitnamilegacy/influxdb
        tag: 2.7.4-debian-11-r0
      auth:
        admin:
          password: supersecret-influx-password
          token: supersecret-influx-token
          org: appwrite
          bucket: telegraf
      persistence:
        enabled: true
        storageClass: milano-v2
        size: 8Gi
    telegraf:
      enabled: true
      config:
        outputs:
          - influxdb_v2:
              urls:
                - http://appwrite-influxdb:8086
              token: supersecret-influx-token
              bucket: telegraf
              organization: appwrite
