apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app appwrite
  namespace: mgd-devbench
spec:
  releaseName: *app
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: appwrite
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: appwrite-helm
        namespace: mgd-devbench
  values:
    commonLabels:
      milano.app: appwrite
    appwrite:
      domain: dev.trusted.nirmalhk7.com
      existingSecret: appwrite-env
      existingSecretOpenSslKey: _APP_OPENSSL_KEY_V1
      usageStats: enabled
      storage:
        limit: "30000000"
      extraEnv:
        - name: _APP_OPTIONS_FORCE_HTTPS
          value: disabled
        - name: _APP_OPTIONS_ROUTER_FORCE_HTTPS
          value: disabled
        - name: _APP_CONSOLE_WHITELIST_EMAILS
          value: nirmalhk7@gmail.com
        - name: _APP_SMTP_HOST
          value: smtp.maileroo.com
        - name: _APP_SMTP_PORT
          value: "587"
        - name: _APP_SMTP_SECURE
          value: tls
        - name: _APP_SMTP_USERNAME
          value: nestor@nirmalhk7.com
        - name: _APP_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: appwrite-env
              key: _APP_SMTP_PASSWORD
        - name: _APP_SYSTEM_EMAIL_ADDRESS
          value: nestor@nirmalhk7.com
        - name: _APP_SYSTEM_EMAIL_NAME
          value: "Nirmal - Appwrite"
        - name: _APP_STORAGE_DEVICE
          value: Local
    api:
      podAnnotations:
        milano.app: appwrite
    realtime:
      podAnnotations:
        milano.app: appwrite
    workers:
      audits:
        enabled: true
      mails:
        enabled: true
      builds:
        enabled: false
      certificates:
        enabled: true
      functions:
        enabled: false
      statsResources:
        enabled: false
      statsUsage:
        enabled: true
    schedulers:
      executions:
        enabled: true
      functions:
        enabled: false
      messages:
        enabled: true
    persistence:
      enabled: true
      storageClass: milano-v3
      uploads:
        size: 10Gi
      cache:
        size: 2Gi
      certificates:
        size: 1Gi
      functions:
        size: 5Gi
      builds:
        size: 5Gi
      sites:
        size: 5Gi
    mariadb:
      enabled: false
    database:
      mode: external
      external:
        host: 172.16.0.106
        port: 3306
        rootUser: appwrite_rw
        name: appwrite
        existingSecret: appwrite-env
        existingSecretPasswordKey: _APP_DB_PASS
    redis:
      enabled: true
      image:
        repository: bitnamilegacy/redis
        tag: 7.2.4-debian-11-r1
      metrics:
        enabled: false
      auth:
        enabled: false
      replica:
        replicaCount: 0
      master:
        persistence:
          enabled: true
          storageClass: milano-v2
          size: 8Gi
    influxdb:
      enabled: true
      image:
        repository: bitnamilegacy/influxdb
        tag: 2.7.5-debian-11-r0
      auth:
        admin:
          password: supersecret-influx-password
          token: supersecret-influx-token
          org: appwrite
          bucket: telegraf
      persistence:
        enabled: true
        storageClass: milano-v2
        size: 8Gi
    telegraf:
      enabled: true
      config:
        outputs:
          - influxdb_v2:
              urls:
                - http://appwrite-influxdb:8086
              token: supersecret-influx-token
              bucket: telegraf
              organization: appwrite
