apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    milano.level: managed
data:
  secure.server: |
    secure.trusted.nirmalhk7.com:53 {
      errors
      cache 30
      hosts {
        10.43.134.196 secure.trusted.nirmalhk7.com
        fallthrough
      }
    }
