apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sonarr
spec:
  chart: sonarr
  repo: https://bananaspliff.github.io/geek-charts
  targetNamespace: mgd-entertain
  valuesContent: |-
    replicaCount: 1

    image:
      repository: linuxserver/sonarr
      tag: arm32v7-latest # ARM image
      pullPolicy: IfNotPresent

    env:
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: entertainment-pvc
        persistentVolumeClaim:
          claimName: "entertainment-pvc" # PersistentVolumeClaim created earlier

    volumeMounts:
      - name: entertainment-pvc
        mountPath: "/config"
        subPath: "configs/sonarr" # Path /mnt/ssd/media/configs/sonarr where sonarr writes the configuration
      - name: entertainment-pvc
        mountPath: "/downloads/transmission"
        subPath: "downloads/transmission" # Path /mnt/ssd/media/downloads/transmission where sonarr picks up downloaded episodes
      - name: entertainment-pvc
        mountPath: "/tv"
        subPath: "library/tv" # Path /mnt/ssd/media/library/tv where sonarr moves and renames the episodes