---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cn-postgres-secret
  namespace: mgd-db
spec:
  encryptedData:
    password: AgBL7mJm/+7hO3UfPAZncXkIsteE2+AAGiiJIeoxdaAR6YHzEswm11zKfxEc+rmKUGNTPg901lIr4xYjuGuPj+Ubu/FZpYuHq0mA90QKknjj6WrK2xFjQtAa9w6aX9R1j8o+dp/FSNI8LZnIGFd/t/5qb0e7PFmkd2H2JfCo2nwzUku6Xkvr/8t84lkTXgGmsnO1BVs4fchnHaOvhgKlJ7+U+xzaIv0odWf9Fr24R6PFXSc3caWvuaeYNF3zBuxfyiuyRkk3r71odeII3HTd/XkOSy5VpvD8tHAQOBxkrdrW+2LJT73l6KnEpuZr2NtLxC5uSONHl7gOkgPk1WL7l12Y7Io68EK343J6/+nAPG5H8b0okw1w+QA+kYsWlnME/JA3dSMJPUS0D7/Wlk6Hgc01jqxai4dKxuD85hfKMPdKYLEZDrYVPATcu7dgvvYgNALYy8XW6Kb/V6XfrXBqTC0cNG0Sduj8RmtGJRqu3gAP4PYWt9+901dqhIlQfxhb7vsoxNZCC608azbMfCTI1k1VWuteba+5/grWXNrS4c1Fiv2gYCjU9QGG/hlZvwAacpAusbuRyFFA9qf/Yyy5NxtnwJqcGnWceJHyegxHCZU7NhLimhIK0pUTiy4LaAJQ2S2u3acHi8+JdR43ybiDeACtuNPlp6OFPBFl3Two3xAmTvXH/rB5TswGxHLaOE/k+AMJ4WBqXpflI1afSrlpfs6uhQ==
    username: AgAUxEiF4tJKjDcVsh/Jb+i5nxC9mfwaP2wJCu8OhgKzWf7+/zCLrmVQsLMF4u7jX6+eawyyWjL18Jks+ffLT+wM76BQMP/QyhPfI3Yg1mX0FEq9oHmtjUxQvyjiuADWgF675L7UPc+TkNo5h7rei7/XV/CuwImSywOR3lP0WsSH+VLvlSsq7anlg9ppYXB2bnanyL5wY/s+FBIySQqLbPzOBRBluUZVvGiGa4fr8sdAs1sbs/CNS98m4jaACWPdEwrQUWpDKJf+Maubq4Yg9r3WwaGQ3sXQWNpLpY3kZKngpUFFrbRkiuEgggj1HjsVgEVw8ghtpkxfZrO4eWDklNaHRs0DKi7vH1m0xEC2BdSbfvAN9l7cdD83a1vmg7GtQa3EA43gHQniSVa0YkMqZNqlYkt8hQ2I7pGlkH9rz/olMZjkr6GfjbXTvzGH+addzq2fL8vPdW5mVwDBCooBDjnRzguenpbOwtRLXSgpmKr+B3fzYbPSuViYCF4SVcho8AwQzUGBpq53STNMtn3g02OIyynvIvwGI30EeVNTemAEkB6mTZRTOJzQ9PH+7P7VyROMlxwsvpvU9U+XRiBlRdImmjv7ne+PBzcWQbRBPb14/YG9w4F+TA5OTMVbpgv22bJFbS7RelEsW1YODPvlWpYojakJlthrks1LdB4POdlDmxE+OY5hc+5v0EygQUM/TxXYUQMv
  template:
    metadata:
      creationTimestamp: null
      name: cn-postgres-secret
      namespace: mgd-db
    type: Opaque
