apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgres
spec:
  instances: 3
  superuserSecret:
    name: secret-postgres
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.8
  storage:
    size: 2Gi
    storageClass: milano-v2
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  bootstrap: 
    initdb:
      owner: postgresql
      secret: 
        name: secret-postgres
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cn-postgres-np"
            spec:
              type: NodePort
              ports:
                - port: 5432
                  nodePort: 30555
    roles:
      - name: svc_authentik
        comment: Authentik Credentials
        ensure: present
        login: true
        passwordSecret:
          name: secret-other
      - name: svc_vaultwarden
        comment: Vaultwarden Credentials
        ensure: present
        login: true
        passwordSecret:
          name: secret-other
      - name: svc_docsmost
        comment: Docsmost Credentials
        ensure: present
        login: true
        passwordSecret:
          name: secret-other
  enableSuperuserAccess: true