apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgres
spec:
  instances: 3
  superuserSecret:
    name: cn-postgres-secret
  envFrom:
    - secretRef: 
        name: cn-postgres-secret
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.8
  storage:
    size: 2Gi
    storageClass: milano-v2
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cn-postgres-np"
            spec:
              type: NodePort
              ports:
                - port: 5432
                  nodePort: 30555
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      postInitTemplateSQLRefs:
        configMapRefs:
          - name: cn-postscriptscm
            key: setup.sql
        secretRefs:
          - name: cn-postgres-secret
            key: SVC_APP_PASSWORD