apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgres
spec:
  instances: 1
  superuserSecret:
    name: secret-postgres
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.8
  storage:
    size: 2Gi
    storageClass: milano-v2
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  bootstrap: 
    initdb:
      owner: postgresql
      secret: 
        name: secret-postgres
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cn-postgres-np"
            spec:
              type: NodePort
              ports:
                - port: 5432
                  nodePort: 30555
  enableSuperuserAccess: true