apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgres
spec:
  instances: 3
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.8
  storage:
    size: 2Gi
    storageClass: milano-v2
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  bootstrap:
    initdb:
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";