apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tesrt123
spec:
  interval: 10m
  releaseName: test
  chart:
    spec:
      chart: cnpg
      sourceRef:
        kind: HelmRepository
        name: cnpg