apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - cn-postscriptscm.yaml
  - helmrelease.yaml
  - dbcluster.yaml
  - db-authentik.yaml
  - db-docsmost.yaml
  - db-vaultwarden.yaml
  - secret-postgres.yaml
  - secret-other.yaml


labels:
  - pairs:
      milano.app: cloudnative-pg