apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - helmrelease.yaml
  - dbcluster.yaml
  - cn-postgres-secret.yaml
  - cn-postscriptscm.yaml

labels:
  - pairs:
      milano.app: cloudnative-pg