---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-other
  namespace: mgd-db
spec:
  encryptedData:
    password: AgAZqk929mPcymwm+DPlPI26sUiaQuONtwWI5erO69nOWHPZIoFySm+Qh1jGpNmKF66+l8EI2e/YKAOFJfu/fhvjtZFXaNYxGfQtzAUzBees9uoB6Z+JNPqhx+NYpLnQ/AEmbBtXm28paYAS7rsHy1e3Vnxtu4YQCJ2bXjZljTkb4bV8siH4eqoKmq2vvjwzTiUIk7jr2ePvSjFYHbaQYI/U3V+Zp8/6sr/DICI29OVKpqyaQDH6gmzLQhZ4axepKjmsjjQlq9FIz0afDLqcEwDaO7eCWgQHll0T8snS0RJB8kIs760chsxamluazVitD68LFGPpb4ZjaUKmzk9YMo9Hsxt+3Ru9lT/kg+1YIqMYSZ6bFTH0FOiHUQaLtrxzL8khJ2Gjq/gfAnLOG0ZKnxbJDZC4hb0156KvZTWR6GbcBf9wBMnFecIRiufQUsvomK8WzyaZGl+/X2oC2WMCfZEbL/OoV0UlA34wG4MBkmpv9jriR9l9Z+PPxT5iprNOIlUouZbixgKgze2t0SQUEk3QCva64oU0/aQn9syIFTcp3kQskjGnXzpacz3TVazAHNQuF1azZ/ZMLU3gckdbhd532Kt64HMQwMi+Ft1PMXqOKCkSgmQTUREjgcbslWwOEJhkaPbJTa6DeB/siUY6IZqZHHMfmHgQ3wA0TP5jnYDuSq0LDdtCHX6HcZVxneoLSB/uxF0Bl1E/qHCMT3egQ7pFyoTfhw==
  template:
    metadata:
      creationTimestamp: null
      name: secret-other
      namespace: mgd-db
    type: Opaque
