---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-postgres
  namespace: mgd-db
spec:
  encryptedData:
    password: AgCWIrMnbtQpY9FPftRtXdivDLAmEvYMrK0RFwik0sGlXaM1GDsyINMLrpC9D0hn+wy66MBe0Z7kbxolQRi+8Ip1iD2zCASUTrP/1onpZppNys1K6NTe5wmIR/tvbICD2bDDLyStVA9XIdOwBlo6qQaMJbY5gF5tQY9swIivgZIzt5jlJxzhWHln3Q1DCvSKtdVOULaCGbp7PbO4d3DnMFdmAetFz5DaEV7vsw0wKyT4otdgtDfBNf9NVvomE2ZGE3yGly1I/720qTYo6I2XLaYe0s5IwMmglhtiJVdfTY5DEfUYgc0yEjop+PEKLPB5NL/vRpdCzzjsNJXOAtAsaSe9AVZp2Oa683NiUmbv4v4uJrDhziKXYLNDNMibey0cr/bXNS5e+CJXWbI8IE1/ni4+c11tRRPPJQjCtkDEYmrOWGR/RKOl6B2uWh0ckly97ra40z4FyYWifCzWqKpqmsquSgiK4uYlptnRRco2YbeMIRnxnwEBk3zPaP53kWl1clQdfA4e9HT4laagHgXy/8ViBdzhYjIODYKm84z7LczfHA15l1sMBgoynfJmNW3xUHvCmw0cSsPQgdbdTe28ogntWR1G+vvZdfRkEf+JhBCkUPRng87pKkAaQ40EeuqZSC4CAO9pVUkXY3GFK4zzhkGmeOYsYgVX1cCiev1SlDx3YxhVjQU5XHImny2yXNM19cO3S+XK5Dxbfhlb
    username: AgBsgkJP99OqrluJESxIlLWhQKiwj7u994vdI3WAsoLINVUC+FmnsZIA0B/5kZnDFvKFAY+sy1ffmhzNxYC8mAijQU9MkdXUiV4oig4Lr3cYOe7j/qUtxburRobd8CQIa713yMaVLScYp9QsdSPPS5hNg8A7g2toXNDOUrSaPfA6sUylELLHvHZqMRa9vXINR8K7ijHNWZLDKbNLqIvemhgJ01QGD8SgGmmHNEG1hW8IrAH/9DebHHXYNMb/1PlEYux0vEAJKLoXdWdijQiCGa4P8E9MopB0TGT3Vb44wvNE8INm3ULyFpe1KqN2a/sanQg2Hx9LMyFZ65KJFRJW5OFD1ggLQ6iO4diEz+v1P1MKgkP85JAr+nWNEee61ju4dsPVr5bbjl6gl9w+urSOmDQqpNjkUiq+qDw6oSNir2S0HIam8LbkFRdzJ1tmt4SEArAfOUTKGFQf2g0pdNUXYmjY1uqdcygPzX/mWMZo41CoClRHKUchgyuQxO0OPJ1KTEwPppkheVC2BS+WjfmggdKrCF30YHOCRNcMlf+U8q7NPdwdIY8+wB5vDs28diqCq5ZkLZb0UBJknB+jDOhKTsNNSb+GXo4y9L52NNKR09Uyg788ZlbUK7Vn/8SPK5zZD8z5+Arg33LKz8TySlCQcR4EXHMVEL6IAjZzK7klmjua3NW73CidBMAttvfoz+HhxR8kXaOk+J79Pg==
  template:
    metadata:
      creationTimestamp: null
      name: secret-postgres
      namespace: mgd-db
    type: kubernetes.io/basic-auth
