apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tools-cert
spec:
  secretName: tools-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "tools.trusted.nirmalhk7.com"
  dnsNames:
    - "tools.trusted.nirmalhk7.com"