apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: mgd-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: milano-v2
