---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: mgd-llm
spec:
  encryptedData:
    SEARXNG_SECRET: AgCuJtNxw+EG92ASQY0OZ3ioE+d05lnuqPfXp4rLdjWZssLZkDVMkvnKEssFA0H4rxPLt+q7IwmY0GVAs78G092/6RG6y3gDGsh5HmQ4djcHPwxGVqiqnpmUEm6AKUDWjB12Nfw9C2shC4WTCNvoE9QxjEn/LEf2Ww5WX/QzUk/YwrNRKXHvRTAofjAeTRxGhdymwS+y355h2wTdR9EI5IcD+ePi7F0Ea38m30/JPVfVe0k96hR0WH0FPnWofK/0VLGu2w60GQYZsEi371gk3IR0f2RnoQmwwTqvfJInPqDSx76hRSjDne4dVSOxGn5GlNPU26G6X50uUN4ObDX26sLWfcgD//c5dkM0hq2jfRda/PXn2jxkuKdUGD5iSWLzJLN/k3UK2xX8QONwXqBJkCkHgPDAmv+s6NX0bh/X9wZ2mh7rK6MPT24VoI+iSmp9y4HmIwl99dOpmuIf8snXAZIBFeqR/dtJhzs9tAGlXbHgFW8+U/wNy40VIoFf18wuL++sYsO5yIx+vjXh2hzOgDe0s1mjLmNxVCcHV56jYtRw0UxoqmwMPAPTQOrp3i6HP4f5G7lzh+id9RQ8MzY8FN1WHzdGvM5dequdWAMPx87uf8R9xLgCg3w7SSzEt2qCgyfq4k8OCemquudjLdqGpKGj8r+oPxLcn8rStof8Z4fczyMMro/Oen2YHVE+SpZXHcqmY3KL36JlIfQd9nOpWiqxLcUuv66F4WzL/TF1+Figm9i+8UKgadICxR44b9eugk6wPUx2UyOagvRHCHMGhAiE
  template:
    metadata:
      name: searxng-secret
      namespace: mgd-llm
    type: Opaque
