---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operationscenter-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgBTZKml/z5cfi7xOWgvOLKTSP9/co9XJyc2T1cQUFNVxf/ncQGbHLwoswUPP07GBhIUcdtxYEfmwU5tLAJNSY9CDwzYx8zd2yr7ksbRELqUgaUjDA7Nuj+DZ+amhVIulTeTgA/NWsTiwKiaEc1Jks7RLWgrOk4bgecJAOsYSReW8Eb0FjKucAP70MjTbm9QUqg61fPyYuZRiAA+l0H1Vdd8qiqAohgWA3yNa420KoXEQ1+f5e5pYDuGfY/+ihIqyQtJb2scSxTZuomXTflrK6UAoi8jgTJq2qnZtQjZLIv4uYpMnUwJAJHcWDdRQPsJRKiyqJZ0MwY5ETRyUm2OlWqUP6DsxhRADW4nmAXXsN/BEfe1hPHbBP4JZI6pDcc9UCIFG3BEGfVV+JJ6nA6LiVN2dXITKrB7HwbeQlFe4ehGEGa4quX3+7twe8NWCUajIGuJApccspb/M1IqhjHiph2vg5F7Z9VE/mWt8YXaCyk0+ImSqQ+Csr3MIvMZ4mbXYABJqtb81kQn+n+R5YziGHsBcG1K55gTNW9yAVg1RF+L5Vq9GMk/sK5dVRiiSHxNQdS/1fte/eqUiwAYLE0IlkjwSTVGwDZarPoalcqtINxWHG4hz1ZMW5lZEPSo1SY/HXw3zBJ7qqi7WYX1dlzUvJgYxYBbwgg7Ab0v/fBfxQiQFDdMDcpqSs7QzacclZsPndGbOwZAOBS37DpB3ERXFdH0I62TkRHKa0nalZj0O8lDfaGCHGT6oHRNB4DY7sH/W5WWCj8FZxi0K8IqHJAMTCxVm0gyJlSDlz4Q2E/4RH6xqGq1q7w03XZ296KGlb4=
    username: AgCCJ7WHcwq61+IRJ0uoNoHywVpcO3TKtdoVDvPwKAmzjcX6cN4Aba7r4bKRtJ8NQE/bCkoUmGg5XLF5HMRjeB3VzTZfIeGPyYLKyTrb+yqQYs9lqdGP44DXfYpGqPM775J24v4ecStw033J8CmUkv0labBexm+cY2z24CCdhRPGBZ5NU9hkj4DcG6/vWv564LJTTimEIEdXiWrIooRTHq3audfQdF911nUvELJ15ezzABLqWK3WKS6IeIYHYbKAft8MJ3MVvyz+CqhlnPb8GFVF/8JcwYFRb/v+EVWFIqeXFL3kU8v4scjFcEu3JJqIk4oUyPT+v9NQ0NHQa8bVOUJiWSDJBKQsf6o7Umv5NMZZwUsqBgtm4DbjFyUcymoReeCjOOtU0//kb4ODDqTKE979DSoUbbyyRv2BPatoxRare6q0BuqU8Deng5Dhik09+PhnUFowqN0HsDPpGTqmpuLhnNSpft/Vmvunn9K86u5Krvak38ZSuctG5nLuiVRhAaDTZdBBGiYd1eKs83S7eu4oXJ8RytMyvLSm21RZmcEitC9BGMbXVPGOK5D/W8iyu/+KmbSRBRStc2frdwvtzJTkig0xutRqhhW/2WSH0oKEGgjNcy8cMZ6XZN+n5lszxp5qLFQSuUFg3OxrasdXh67QDpnYX3HXRTCWnDDQ8bIf5VPgEusVlwkNrFUvKEtQwyB+w6W46MovQls=
  template:
    metadata:
      creationTimestamp: null
      name: operationscenter-token
      namespace: flux-system
    type: Opaque
