---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operationscenter-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgCfw03LKw2MdOcMdw7wMUoib/JlT8ROoV2ziLpVDfv8YZ8hMRkyO1pxcC5XkyXqTHEkEmBf3Lga2eGMDPcerhnoHLvvJ2CXRfMW/s9vk4C2x2wesXt2/Rz/+k844z3OX1nLiUMnW8L84bTao6UN0wTCmBHLVu/ZxgRuRiMjElYs9Q/3L8WWniE4G7xIFQsZ1LxeQ5pf7Ox9gDohng84e2oeB8nTfLgvfGUb0sRdBHZK8wqEtN32y5lVdw4+tnp5ip8Y7heFNi5DXK/fo/Ut3PoXuDEK1uyO6Y/6KlZZN9YqiWE5WpFeKDxH1XdKZKqL+X3FxuvVbCfd9LpE2MFZkDWQ+sI1RC/5mfxp3iRaYbUAH52Ek3GXap/wWn9KjFlj8iJgUw3NUOUU8xxQm2ozB5W/Y8eYwPAGweZBCiYhhRIbo8TE2EzrD/mj1QKAtjXeKXMDeXfIDOsi9Lz+GbMaavostJMI43eHaFign9EPkFBEMP/hRzB4vwbX1aFYILZOsJfb+fHNdPZw7qEKy5ZZFtFxkqnz6PGBy8LBSrJaRnwdVBZz4JVNJb17AjcvMc1U1/GBOgOUZbrY/sLygj1wiS0L6zruwpIDJNNQ+YAz56SZIK2XOe0/V0pfAdeKWUyT3yYL5vRzH5be62jXUY2jbYD64KIMr1Vq44Gg3gkI61NpWLxV8r4pKEpFoIqmI/ZxFn7NE8EKuZYveJQpiX4/ml0zH+Hf7yeEEZWO86XILkOR17/fVF6oXgl1Q/ZvlJ/3VrhRZSGgEcZi2UGl7/5ZoSS+e3LHn43dMDJOfxoGoPOfYsa/aT7lzXneg8viIc4=
    username: AgCsemkc05MwaitCceFXMvQqcO8Xx2s9uppaDZR3qKi4wAr2ZM598AneHk1LfqlkKfY9vRYPxL6ufCy3ml5v6gUCUqVxtV71oAo2T0kXQtX70Tm8GKrqf7QebyfSUTHl5bUKAtK3TD/dPqiZDUYEnM/FGW3veKWZAxmIiyw21qAOihwW+SXbwR6LnMe7WlpvEYhQ7hhonyO5984x9EGsq2EYul4ql2S+zert8rzjjG2ymGRHnDknpMs2Sd69QFhWA+gsMv617ZbMEGqN0ihcq6OkefH3LDz59HIsVX1lE3x/GCyZ2JT5XyAXZAHdIUA3TNEW8NtxMSR5TN1vCkbziIbAY4O3OmSOqbvZk7A0yrW9KPCcBxmiNF83LCln+QSIP7W4BiP18VX05efSjMfbH41CN0Mfl4ED/g+S6hEO3XS8WBAhFL02FzdUWDmpeCZzizDFtoiSQEtMwKkkz7lCLbEcj61TpgQiDm3DP9e6DqTUNwjX+w9Jn1xvOEPHz8+yL4LpkdxS/BQyWVWFPjTqN0rnx1/Coab4xeTt1Ai9pR0RkevPZNYpfw+rZO0CeCn3gIIQcEOLQdzZZSEGR74tU3ysBO/wimAsDwvW5KDiN8/FoyUdQ3GpZfzMmtT0Pp8CHZZb6HmMATxn64EPr3E0vUTNBoZI7xwl5iH2rj51kTmNzZptdwoBIDGV/vSJgiAVv6NXaRT670XqD0g=
  template:
    metadata:
      name: operationscenter-token
      namespace: flux-system
    type: Opaque
