---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operationscenter-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgAI2YlMO7mp5sz+fGBW/mHHjmOVNhkN3+AqgNCydKnCyq+diM2QAfOac6NGLNZPiRggPWcewAx4gBb/dH09bW+3ehbeLd3A+4/CduVGIFcTxU/q/OqJUXDfJ5dzp3OCo4IAsCG7JAhtokAxoLRf0wEOoDjtkTRCvf1DK7qmAJagdv2hItLCLpOzo1jZm8kEP9Gh6z1Q+JGEPwW2jYPYib8yBpYw5yEcW7xErULOrL4r+KfZZ/zw+ghTPnLIzNI+2zya479v6uUtCP/w4wTsNCCCNo6o8AakV1K5/lLXRVpXNLVChIyRtY3k803jLbJSRK82iQ6esvXFTsFYGUbH+iUte3+OYHucOsMO1rYlaEjbFbY73qwSR7BHaYgWX1NkN8k0eEzkziGWEIdBoKF9awMjM7B+MnvF5TRO6o/FEniVK5QobECq1pHz8TvWcR5s3v0Oo17nd83SM+Fizwb38FwP3FgFfPjyj/u3vToB54c5SmbuvVj/N3IQV0X63KcZcKuj5yhB7xOPqxW7V29wYWe4chxywN+mcH8hpQu7SnPjAvj2XztfRxuPZTdqGO69p2NICBS+THr+o/ARElXL13dgKpWtdvoKritWlFkDvg7vHIWF5V6e0DyH4Y4eg+ts2GsZAIhJFuXOU37bxjmsJNBKlZm82s6RAkEpaha3pzUGX7BfCEWC9aAvRTQcdDKkog/ut87vcZlwToNFvp2yPD7h8jMNHXKr78qbs9LTJ76095kjiZikYEnbALvVxjyM9U8opJc64wwwGVwdmk4P9SkErJwlJNlgwtWu9ifBn1WYXtHVveScBknhQ/CnfNY=
    username: AgCozYn1uzP8Mq4T4QVGnLQmA8Hk+id2BeFFD7kMKNJQi5LnjgpMRgZ893ag96uutDa/hoNxfjA0VfUq7T1RT5Msr83OE5bauo8HLG31ikJsXWPbmorYzK4xfeydXAoEmvuCxv7hUMmjHOuAPbKUMnqey52Yv6pC3k7OWvngbLQbi74l7lzUaMbKPGj0qf1xRyulduLv9XTvQ91bTOf4er+aca8NaKocQ+SZpVS99rXWpvxkAh6gWgprm6vDDi7wTLee1u2UU7YsszFiQ5DCXtqfjWiW1lLZwmJif27yXv9XMS0AUciwvlkdsfSacSuPZTu0IOH/tlRUGqaeMGXvlSFqfnr6vo4wRyCOcLNU6lJr9pk6qeFwSH6oFetbENknRWg28J2x6Q2JbpQ/0H4NKqQ+tIrh/nyKIcE4qknVnaORkqv73yp6Z2Cy8KHy5G7PYxGLmpZrKxDEepOnBEstJL44mDVRZ1cRLKVr2hK+0xoTd3XQPH242tkLndH/6gFLaIxej5Zwv94gdkm32DSxhIkOrpxlanHfRdCn3rH2Q9abt149WOovB6WEuyDv3BQDX2Ez2gYP4H90Bn9T8dVdzOrGh0zRvBnJB0dwjcJ2IugBHPFuj8xkkODVTvpxdcDWJCcL6eaknuE0bZkq+nTy6RcAzIkYhAUl6DoPI5ENfNTp4XEttl0DIct0ZCOpj+u6o7tFidkHhP0vb7Y=
  template:
    metadata:
      creationTimestamp: null
      name: operationscenter-token
      namespace: flux-system
    type: Opaque
