---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operationscenter-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgCJ9nghHShcX+pEIN9/1aHwCYPeTog3VoMl3cVzvCPdWvJ69idQ950V+ZVmb2HOAtI+DIkOFzDHUj/izn0UlLAXg0pOF1ho1Fqzzj88aqy3p2V4c0AnF4El3bJujgkPuc9TZe+pIVB13Rb6J7FoCDAnCGe2PpbmQsYUJJ89DYOMn00MnWCV/SGcUJQ1yAf39COY/eVENozWiydv1Ps4YnH98gPXxHME1wspHU/90N0Ws5nEKnm5dxyN/H28/Q2XXfCgqc9lk8uPDPF9Wk8+NdsZk7UwLZY3ftQZ3ev7qeY8oHMcgGZC/8UM7lK8NPMJTvnMfHWZ7D7SzP0uZAmXy4IQsd7LzbLR1l/1WPaMXUkXDUCey7ig4Xjd5xU+f1UxzjzjNY3AXyY+S7d++PHgKl4fR1b6jC2T/khkYqon+Vd48W53s05CXXhjXCMZ654d4QH3hbSEop8BkiKxRM3T6PqVwThqOf8xGp4YhuZJ8rQ+4g5djEBitd3uHiH5YJpMrHG+vcao8R9dSGmhwVfcVYLJs0AlAK2p7OKkRTOFomBeGKKOfq7Ll18DJi2OG6GK3YESo/PGqw1VCrEL0xJgbYTFZX+uO3XTu44BWWuS+wev/uSIR9qVvHCDeJ4P8Ol+Sz0VnEpp3rhDXZnCVsV6CykHFVmbsjpapkSPdKualpEmbeokUyZdI6ioZEeVL7DEF2S1HXIYw5gcLCcKz1imDJlQjdOvQpOnQ2DGAtbf7rslL2TofY+h3o9t/nhKYNLZRf/eu1iM6WbBylzwHcXtB21MXrQiQOlsIFScBCWU49+fhEZEMVVqlG45V7QjcFg=
    username: AgAlBRrGVME1i4DbtXbcur2XAJQU2/yPgNo0+l0c5SjF5Qx1hiLEAs9SJPAYdiPqIxJhZjJTJZMLNPM/LSaiYOAFAS5d367mXoaD7ZIJgNxXW0LA6ZuWn2VTfbn/9XCfoIyG4Xnn6kCjsR5A9vOXUxYYT61KueA8afvEn5CrrqtwuWVTRd/CsWGq2HjILlfEGlzW095pG5y7GR+z0pfe2/BMi+JnkVO4u9nVYP+gwzfIvM54lCYW+aKvYb6rybXvocgA2zRz1OAN0P+av6B0dVM3tpHtZ3+Ozt093ItmA+2xFN98XEZY+1wcbs4QZN/VDNzvyNLqNPvh2B90JyTYLRMcqVvtAXgb/IR/WPW3K5wyLkuQiDKPXLu9EFks07lb3qyO9wEZF70zU+ofguJOx5KOLDrZS0J+srlGEIecD5XAYyRG8oSk7D2pZBYba61F75IRnH71XNHQSacN9I3juKAKDR8U/9txsBk8XbELVSuApsSHpMPU6q7aliCXbFsOquR1Kocf+9ldN2mdXPBLN6qZGFZyARHVtz76VwFiq9FfbLLtxswJEHFVYSy2Ptsz8nUdOVfCNQy/YLubhyF4wtLiuCBvr3sgKCQPPsmiphZgQowPHACjJMZxnrn4SwI3X+YfAhpuVStpSH/eRbx4+9W+/pNMlKy1DVp/qJK8CCD4Q9MxaPDt9L4dI6744+fl/0nsZXjgCx6x3T4=
  template:
    metadata:
      name: operationscenter-token
      namespace: flux-system
    type: Opaque
