---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operationscenter-token
  namespace: flux-system
spec:
  encryptedData:
    password: AgBZGk5C2J2PazEq3i0btvMSvRSs1soSg6+4r7dzx6YnDzUShy8B8RbNsm4Sh3R2YDYCNkVGMAaiZx1Z2OzD7uMv2KmUqkBVtuD9Q3wmPLX44gmnZcD2zlsk54cpWpCIMcptGwDB+jJ4RhbaBWHdTVQgf5n3p1vqHMuhXPtaNIpjpqkoJzPsUdsvApkQLpMtCK2R2hsuBW1rvZ/zw8NORrcOTnGYVJ6+PSPIvzzYrqYi07ewNpgYw05sBbpr7I/todlXobn2JdtpajBgeJxziQsIhLGp9LCQAu2AEU4iZvI/IKXPo3xOBQEgBAFZO1ci4AsyX34Arlmzx3WGKMpsetwy3gN2oTgZ80srpjeVqra+JEM89ABTCC+SFQ+zBPmQlW9S0kfkKmgB/xcc/+OU6/kPeWHxnrx/2JeljjXOR1eSJn7Scv2EN4aTtcyDxjMquP8XHxxgbZ3VHf/GBEfZScqFfbdc6F1p6hed3yrKy/mOIglX7PqyZ88nAp9x99c3C8L6ToM67QSCurFeTwr5P6XxnwiSS23R5yq1akd3g66vRMu3QZQ7PL1XHZqP4134/mfGfg157ReUJUIvkI6bS3hP8sMAaNitRu6Fbhb4AvKSx3Uxi9KuEaMBagGda5fuERIn3BF+nT2wxTf8nqXMYvLf5U4kIhhvRvD6ZlpRnQp+1gvWL3nFn+hi0i5tlFrckzCyHbxuP6qgHUylKJjkO8PSPzILhuKkZi3ao3x/usEKA7uMS/0PPSWc
    username: AgBh1Y5XTV8yuxnPCRql8RvDZxOyODYVpWQAW3+JmbrT/qXZQRol5rLLTc05r/VW92TxA0W2P+EV8vuGPbXs5I6mIwPbVNs7VGhSj5bUtbsePLYZqwSEzFc5ne9gnKZ0ykrodTSP3D20nGOzG80/RY3rzkc1MjYUv8DpRHTGl6wDu6D63Itr9A/YcgttpTrZslbH+yCtsls/wbawGOHh3X5KdiN9OtzJTuLlcSpqEI6I5lZwlyMxzSvTzDZkM2HlKFef4hFtXBz73clcy8SXHjLpMo/XdfLoIuo1v8NOzYJJJ9Wbp8PcKh/+J6284JyR1Wa3EdKG1FD1JM7iiM5tMtAJLMo8x7HI2aepT8DAE+ExZREtcXKmszD2LzDL4KR1dAYQ3MP9mkC5MAS9DLqhj47KGN4AAwu3saW88HdBtqDgtWQDEVA0b4UbvH63phs3CO7ZSGBjzuVfpLbj5qulpXmw/JUz8JWY8gs3OXpnFt619NVNzoiINnfBKCB9F4nPzaoavLoPZbNFFpJfl/H0faclMoHmlR0Mgw1rtdtU90i9np/9Q8DEVr8iEtnW0rV43xLixUdGY6gsgFbSN/gPmvDPqLqsKsm45xBkXgw8qqW7N9qBMkeWlp5WitBf6jY5W5EBTXGXj0bFgjUWSlZg1sy6dL8+BlNP1g/DE1cWsf3iLyLfFOe+J42f+V1etu85YLNH2BA2pckDyIdfFqybkQ==
  template:
    metadata:
      name: operationscenter-token
      namespace: flux-system
