apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app pterodactyl
  namespace: mgd-gaming
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - gaming.trusted.nirmalhk7.com
      secretName: pterodactyl-tls
  rules:
    - host: gaming.trusted.nirmalhk7.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: *app
                port:
                  number: 80
