apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: mgd-multimedia
spec:
  interval: 10m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud-helm
  values:
    deploymentLabels:
      milano.app: nextcloud
      milano.level: managed

    imaginary:
      podLabels:  
        milano.app: nextcloud
        milano.level: managed
      service:
        labels:
          milano.app: nextcloud
          milano.level: managed

    metrics:
      enabled: true
      podLabels:
        milano.app: nextcloud
        milano.level: managed
      serviceMonitor:
        labels:
          milano.app: nextcloud
          milano.level: managed

    persistence:  
      enabled: true
      size: 20Gi
      storageClass: milano-v2

    nextcloud:
      host: drive.trusted.nirmalhk7.com
      existingSecret:
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: nx-username
        passwordKey: nx-password

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: mysql
      database: nextcloud
      host: cn-mariadb.mgd-db.svc.cluster.local:3306
      existingSecret:
        enabled: true
        secretName: nextcloud-credentials
        usernameKey: db-username
        passwordKey: db-password