apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - secret.yaml
  - helmchart.yaml
  - ingressroute.yaml


labels:
  - pairs:
      milano.app: nextcloud