apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-facility
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: milano-v3
  mountOptions:
    - nfsvers=4.1
    - hard
    - noresvport
  nfs:
    server: 172.16.0.107
    path: /mnt/2tbhdd/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-facility
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  storageClassName: milano-v3
  volumeName: nextcloud-nfs-facility
