apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: plex
spec:
  chart: plex-media-server
  version: 0.9.1
  repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages 
  targetNamespace: mgd-media
  valuesContent: |-
    persistence: 
      media:
        existingClaim: media-pvc

    commonLabels: 
      milano.app: plex