apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: plex
spec:
  chart: plex-media-server
  version: 0.9.1
  repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages 
  targetNamespace: mgd-media
  valuesContent: |-
    image:
      registry: index.docker.io
      repository: plexinc/pms-docker
      pullPolicy: IfNotPresent

    pms:
      storageClassName: milano-v2
      configStorage: 2Gi

    persistence:
      data:
        existingClaim: media-pvc
      transcode:
        emptyDir: {}

    service:
      type: ClusterIP

    commonLabels: 
      milano.app: plex