apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_middlewares
  - namespace.yaml
  - media-pv.yaml
  - jackett
  - plex
  - radarr
  - sonarr
  - transmission
  
namespace: mgd-media