apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  storageClassName: milano-v2
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/ssd/media"