apiVersion: v1
kind: ConfigMap
metadata:
  name: paperclip-env
  namespace: mgd-llm
data:
  NODE_ENV: "production"
  PAPERCLIP_STORAGE_PATH: "/paperclip"
  PORT: "3100"
  PAPERCLIP_PUBLIC_URL: "https://paperclip.trusted.nirmalhk7.com"
  BETTER_AUTH_BASE_URL: "https://paperclip.trusted.nirmalhk7.com"
  PAPERCLIP_ALLOWED_HOSTNAMES: "paperclip.trusted.nirmalhk7.com"
