apiVersion: v1
kind: ConfigMap
metadata:
  name: paperclip-env
  namespace: mgd-llm
data:
  NODE_ENV: "production"
  PAPERCLIP_STORAGE_PATH: "/paperclip"
  PORT: "3100"
  PAPERCLIP_PUBLIC_URL: "https://paperclip.trusted.nirmalhk7.com"
  BETTER_AUTH_BASE_URL: "https://paperclip.trusted.nirmalhk7.com"
  PAPERCLIP_ALLOWED_HOSTNAMES: "paperclip.trusted.nirmalhk7.com"
  OPENCLAW_GATEWAY_URL: "ws://172.16.0.104:18789"
  PAPERCLIP_COMPANY_ID: "e0043b96-f425-425d-8fcf-b1d72a020994"
