apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperclip-ingress
  namespace: mgd-llm
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/href: "https://paperclip.trusted.nirmalhk7.com"
    gethomepage.dev/group: LLM
    gethomepage.dev/description: "Document assistant"
    gethomepage.dev/icon: "sh-paperclip"
    gethomepage.dev/app: "paperclip"
    gethomepage.dev/name: "Paperclip"
    gethomepage.dev/weight: "30"
    gethomepage.dev/pod-selector: "milano.app=paperclip"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`paperclip.trusted.nirmalhk7.com`)
      kind: Rule
      services:
        - name: paperclip
          port: 3100
