apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperclip-data
  namespace: mgd-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: milano-v2
