name: Test Nginx

on:
  push:
    branches:
      - main
    paths:
      - 'nginx/**'
      - '.github/workflows/test-nginx.yaml'
  pull_request:
    branches:
      - '**'
    paths:
      - 'nginx/**'
      - '.github/workflows/test-nginx.yaml'

jobs:
  test-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate dummy SSL certs
        run: |
          sudo mkdir -p /etc/letsencrypt/live/trusted.nirmalhk7.com/
          sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/letsencrypt/live/trusted.nirmalhk7.com/privkey.pem -out /etc/letsencrypt/live/trusted.nirmalhk7.com/fullchain.pem -subj "/CN=trusted.nirmalhk7.com"
      - name: Test Nginx config
        run: |
          cd nginx
          sudo nginx -t -c $(pwd)/nginx.conf -p $(pwd)
