
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-cert
spec:
  secretName: gitea-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "gitea.trusted.nirmalhk7.com"
  dnsNames:
    - "gitea.trusted.nirmalhk7.com"